//this file is autogenerated don't modify
define("jassijs_localserver/registry", ["require"], function (require) {
    return {
        default: {
            "jassijs_localserver/DatabaseSchema.ts": {
                "date": 1622984213677
            },
            "jassijs_localserver/DBManager.ts": {
                "date": 1624103920275,
                "jassi_localserver.DBManager": {}
            },
            "jassijs_localserver/Filesystem.ts": {
                "date": 1625946455001,
                "jassijs_localserver.Filessystem": {
                    "$Serverservice": [
                        {
                            "name": "filesystem"
                        }
                    ]
                }
            },
            "jassijs_localserver/Indexer.ts": {
                "date": 1627585602318
            },
            "jassijs_localserver/LocalProtocol.ts": {
                "date": 1624139285542
            },
            "jassijs_localserver/modul.ts": {
                "date": 1622998474045
            },
            "jassijs_localserver/RegistryIndexer.ts": {
                "date": 1624137198480,
                "jassijs_localserver.RegistryIndexer": {}
            },
            "jassijs_localserver/Testuser.ts": {
                "date": 1622984213666,
                "Testuser": {
                    "$DBObject": [],
                    "@members": {
                        "id": {
                            "PrimaryColumn": []
                        },
                        "firstname": {
                            "Column": []
                        },
                        "lastname": {
                            "Column": []
                        }
                    }
                }
            },
            "jassijs_localserver/TypeORMListener.ts": {
                "date": 1622998616949,
                "jassijs_localserver.TypeORMListener": {
                    "EventSubscriber": []
                }
            }
        }
    };
});
//# sourceMappingURL=registry.js.map