"use strict:";
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "$serverside/Hallo.ts": {
        "date": 1630962141130
    }
};
//# sourceMappingURL=registry.js.map