"use strict:";
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "de/remote/AR.ts": {
        "date": 1622985477990,
        "de.AR": {
            "$Rights": [
                [
                    {
                        "name": "Auftragswesen/Ausgangsrechnung/festschreiben"
                    },
                    {
                        "name": "Auftragswesen/Ausgangsrechnung/löschen"
                    }
                ]
            ],
            "$DBObject": []
        }
    },
    "de/remote/ARZeile.ts": {
        "date": 1622985479813,
        "de.ARZeile": {
            "$DBObject": []
        }
    },
    "de/remote/Kunde.ext.ts": {
        "date": 1622985482440
    },
    "de/remote/Kunde.ts": {
        "date": 1634384659871,
        "de.Kunde": {
            "$ParentRights": [
                [
                    {
                        "name": "Kundennummern",
                        "sqlToCheck": "me.id>=:i1 and me.id<=:i2",
                        "description": {
                            "text": "Kundennummern",
                            "i1": "von",
                            "i2": "bis"
                        }
                    }
                ]
            ],
            "$DBObject": [],
            "@members": {
                "id": {
                    "PrimaryColumn": []
                },
                "vorname": {
                    "Column": []
                },
                "nachname": {
                    "Column": []
                },
                "strasse": {
                    "Column": []
                },
                "PLZ": {
                    "Column": []
                },
                "ort": {
                    "Column": [
                        {
                            "nullable": true
                        }
                    ]
                },
                "hausnummer": {
                    "Column": []
                },
                "rechnungen": {
                    "OneToMany": [
                        "function",
                        "function"
                    ]
                },
                "alleKundenNachNachname": {
                    "$DBObjectQuery": [
                        {
                            "name": "Alle nach Namen",
                            "description": "Kundenliste nach Namen"
                        }
                    ]
                },
                "alleKundenNachNummer": {
                    "$DBObjectQuery": [
                        {
                            "name": "Alle nach Nummer",
                            "description": "Kundenliste nach Nummer"
                        }
                    ]
                },
                "land": {
                    "Column": [
                        {
                            "nullable": true
                        }
                    ]
                }
            }
        }
    },
    "de/remote/KundeExt.ts": {
        "date": 1626122322826,
        "de.KundeExt": {
            "$Extension": [
                "de.Kunde"
            ]
        }
    },
    "de/remote/KundeExt2.ts": {
        "date": 1626123322693,
        "de.KundeExt2": {
            "$Extension": [
                "de.Kunde"
            ]
        }
    },
    "de/remote/Lieferant.ts": {
        "date": 1622985489873,
        "de.Lieferant": {
            "$DBObject": []
        }
    },
    "de/remote/MyUser.ts": {
        "date": 1622985491688,
        "de.MyUser": {
            "$DBObject": [],
            "Entity": []
        }
    }
};
//# sourceMappingURL=registry.js.map