"use strict:";
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "local/remote/Book.ts": {
        "date": 1618335425588,
        "local.Book": {
            "$DBObject": []
        }
    }
};
//# sourceMappingURL=registry.js.map