"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"local/remote/Book.ts": {
		"date": 1622803502423,
		"local.Book": {
			"$DBObject": []
		}
	}
}