//this file is autogenerated don't modify
define("local/registry",["require"], function(require) {
 return {
  default: {
	"local/modul.ts": {
		"date": 1625396400000
	},
	"local/remote/Book.ts": {
		"date": 1622985546000,
		"local.Book": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"tt": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"t2": {
					"Column": []
				}
			}
		}
	}
}
 }
});