//this file is autogenerated don't modify
define("local/registry",["require"], function(require) {
 return {
  default: {
	"local/modul.ts": {
		"date": 1614616375403
	},
	"local/remote/Book.ts": {
		"date": 1622803502423,
		"local.Book": {
			"$DBObject": []
		}
	}
}
 }
});