"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"northwind/remote/Categories.ts": {
		"date": 1681228125821,
		"northwind.Categories": {
			"$DBObject": [],
			"@members": {
				"id": {
					"ValidateIsInt": [
						{
							"optional": true
						}
					],
					"PrimaryColumn": []
				},
				"CategoryName": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Description": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Picture": {
					"ValidateIsString": [],
					"Column": []
				},
				"Products": {
					"OneToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"northwind/remote/Customer.ts": {
		"date": 1681125122612,
		"northwind.Customer": {
			"$DBObject": [],
			"@members": {
				"id": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"PrimaryColumn": []
				},
				"CompanyName": {
					"ValidateIsString": [],
					"Column": []
				},
				"ContactName": {
					"ValidateIsString": [],
					"Column": []
				},
				"ContactTitle": {
					"ValidateIsString": [],
					"Column": []
				},
				"Address": {
					"ValidateIsString": [],
					"Column": []
				},
				"City": {
					"ValidateIsString": [],
					"Column": []
				},
				"Region": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"PostalCode": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Country": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Phone": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Fax": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"northwind/remote/Employees.ts": {
		"date": 1681302641560,
		"northwind.Employees": {
			"$DBObject": [],
			"@members": {
				"id": {
					"ValidateIsInt": [
						{
							"optional": true
						}
					],
					"PrimaryColumn": []
				},
				"LastName": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"FirstName": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Title": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"TitleOfCourtesy": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Address": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"City": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Region": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"PostalCode": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Country": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"HomePhone": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Extension": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Photo": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Notes": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"PhotoPath": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ReportsTo": {
					"ValidateIsInstanceOf": [
						{
							"type": "Employees",
							"optional": true
						}
					],
					"JoinColumn": [],
					"ManyToOne": [
						"function"
					]
				},
				"BirthDate": {
					"ValidateIsDate": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"HireDate": {
					"ValidateIsDate": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"northwind/remote/OrderDetails.ts": {
		"date": 1681235233082,
		"northwind.OrderDetails": {
			"$DBObject": [],
			"@members": {
				"id": {
					"ValidateIsInt": [
						{
							"optional": true
						}
					],
					"PrimaryGeneratedColumn": []
				},
				"Order": {
					"ValidateIsInstanceOf": [
						{
							"type": "Orders"
						}
					],
					"ManyToOne": [
						"function",
						"function"
					]
				},
				"Product": {
					"ValidateIsInstanceOf": [
						{
							"type": "Products"
						}
					],
					"ManyToOne": [
						"function"
					]
				},
				"UnitPrice": {
					"ValidateIsNumber": [],
					"Column": [
						{
							"nullable": false,
							"type": "decimal"
						}
					]
				},
				"Quantity": {
					"ValidateIsNumber": [],
					"Column": []
				},
				"Discount": {
					"ValidateIsNumber": [],
					"Column": [
						{
							"nullable": true,
							"type": "decimal"
						}
					]
				}
			}
		}
	},
	"northwind/remote/Orders.ts": {
		"date": 1681235896083,
		"northwind.Orders": {
			"$DBObject": [],
			"@members": {
				"id": {
					"ValidateIsNumber": [
						{
							"optional": true
						}
					],
					"PrimaryColumn": []
				},
				"Customer": {
					"ValidateIsInstanceOf": [
						{
							"type": "Customer"
						}
					],
					"ManyToOne": [
						"function"
					]
				},
				"Employee": {
					"ValidateIsInstanceOf": [
						{
							"type": "Employees"
						}
					],
					"ManyToOne": [
						"function"
					]
				},
				"OrderDate": {
					"ValidateIsDate": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"RequiredDate": {
					"ValidateIsDate": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShippedDate": {
					"ValidateIsDate": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipVia": {
					"ValidateIsInstanceOf": [
						{
							"type": "Shippers"
						}
					],
					"ManyToOne": [
						"function"
					]
				},
				"Freight": {
					"ValidateIsNumber": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true,
							"type": "decimal"
						}
					]
				},
				"ShipName": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipAddress": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipCity": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipRegion": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipPostalCode": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipCountry": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Details": {
					"ValidateIsArray": [
						{
							"type": "OrderDetails"
						}
					],
					"OneToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"northwind/remote/Products.ts": {
		"date": 1681236399113,
		"northwind.Products": {
			"$DBObject": [],
			"@members": {
				"id": {
					"ValidateIsInt": [
						{
							"optional": true
						}
					],
					"PrimaryColumn": []
				},
				"ProductName": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Supplier": {
					"ValidateIsInstanceOf": [
						{
							"type": "Suppliers"
						}
					],
					"ManyToOne": [
						"function"
					]
				},
				"Category": {
					"ValidateIsInstanceOf": [
						{
							"type": "Categories"
						}
					],
					"ManyToOne": [
						"function",
						"function"
					]
				},
				"QuantityPerUnit": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"UnitPrice": {
					"ValidateIsNumber": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true,
							"type": "decimal"
						}
					]
				},
				"UnitsInStock": {
					"ValidateIsNumber": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"UnitsOnOrder": {
					"ValidateIsNumber": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ReorderLevel": {
					"ValidateIsNumber": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Discontinued": {
					"ValidateIsBoolean": [],
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"northwind/remote/Shippers.ts": {
		"date": 1681236441210,
		"northwind.Shippers": {
			"$DBObject": [],
			"@members": {
				"id": {
					"ValidateIsInt": [
						{
							"optional": true
						}
					],
					"PrimaryColumn": []
				},
				"CompanyName": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Phone": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"northwind/remote/Suppliers.ts": {
		"date": 1681236514330,
		"northwind.Suppliers": {
			"$DBObject": [],
			"@members": {
				"id": {
					"ValidateIsInt": [
						{
							"optional": true
						}
					],
					"PrimaryColumn": []
				},
				"CompanyName": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ContactName": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ContactTitle": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Address": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"City": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Region": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"PostalCode": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Country": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Phone": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Fax": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"HomePage": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"northwind/SampleServerReport.ts": {
		"date": 1624805092000
	}
}