//this file is autogenerated don't modify
define("jassijs_editor/registry",["require"], function(require) {
 return {
  default: {
	"jassijs_editor/AcePanel.ts": {
		"date": 1656073135815,
		"jassijs.ui.AcePanel": {}
	},
	"jassijs_editor/AcePanelSimple.ts": {
		"date": 1656022299019,
		"jassijs.ui.AcePanelSimple": {}
	},
	"jassijs_editor/ChromeDebugger.ts": {
		"date": 1655584741932,
		"jassijs_editor.ChromeDebugger": {}
	},
	"jassijs_editor/CodeEditor.ts": {
		"date": 1656337058050,
		"jassijs_editor.CodeEditorSettingsDescriptor": {
			"$SettingsDescriptor": [],
			"@members": {}
		},
		"jassijs_editor.CodeEditor": {
			"@members": {}
		}
	},
	"jassijs_editor/CodeEditorInvisibleComponents.ts": {
		"date": 1655928743384,
		"jassijs_editor.CodeEditorInvisibleComponents": {}
	},
	"jassijs_editor/CodePanel.ts": {
		"date": 1655661688870,
		"jassijs_editor.CodePanel": {}
	},
	"jassijs_editor/ComponentDesigner.ts": {
		"date": 1656185726677,
		"jassijs_editor.ComponentDesigner": {}
	},
	"jassijs_editor/ComponentExplorer.ts": {
		"date": 1656022470991,
		"jassijs_editor.ComponentExplorer": {}
	},
	"jassijs_editor/ComponentPalette.ts": {
		"date": 1656017272626,
		"jassijs_editor.ComponentPalette": {}
	},
	"jassijs_editor/Debugger.ts": {
		"date": 1656019585644,
		"jassijs_editor.Debugger": {}
	},
	"jassijs_editor/modul.ts": {
		"date": 1654273312166
	},
	"jassijs_editor/MonacoPanel.ts": {
		"date": 1656073118850,
		"jassijs_editor.MonacoPanel": {}
	},
	"jassijs_editor/StartEditor.ts": {
		"date": 1623098600000
	},
	"jassijs_editor/util/DragAndDropper.ts": {
		"date": 1655929645867,
		"jassijs_editor.util.DragAndDropper": {}
	},
	"jassijs_editor/util/Parser.ts": {
		"date": 1656955313898,
		"jassijs_editor.util.Parser": {}
	},
	"jassijs_editor/util/Resizer.ts": {
		"date": 1656018239890,
		"jassijs_editor.util.Resizer": {}
	},
	"jassijs_editor/util/TSSourceMap.ts": {
		"date": 1655556792363,
		"jassijs_editor.util.TSSourceMap": {}
	},
	"jassijs_editor/util/Typescript.ts": {
		"date": 1656537319888,
		"jassijs_editor.util.Typescript": {}
	}
}
 }
});