//this file is autogenerated don't modify
define("jassijs_editor/registry",["require"], function(require) {
 return {
  default: {
	"jassijs_editor/AcePanel.ts": {
		"date": 1740653429301.0798,
		"jassijs.ui.AcePanel": {}
	},
	"jassijs_editor/AcePanelSimple.ts": {
		"date": 1719757301492.3672,
		"jassijs.ui.AcePanelSimple": {}
	},
	"jassijs_editor/ChromeDebugger.ts": {
		"date": 1681488352000,
		"jassijs_editor.ChromeDebugger": {}
	},
	"jassijs_editor/CodeEditor.ts": {
		"date": 1740761803088.7715,
		"jassijs_editor.CodeEditorSettingsDescriptor": {
			"$SettingsDescriptor": [],
			"@members": {}
		},
		"jassijs_editor.CodeEditor": {
			"@members": {}
		}
	},
	"jassijs_editor/CodeEditorInvisibleComponents.ts": {
		"date": 1740651512713.9685,
		"jassijs_editor.CodeEditorInvisibleComponents": {}
	},
	"jassijs_editor/CodePanel.ts": {
		"date": 1655661690000,
		"jassijs_editor.CodePanel": {}
	},
	"jassijs_editor/ComponentDesigner.ts": {
		"date": 1740828811263.884,
		"jassijs_editor.ComponentDesigner": {}
	},
	"jassijs_editor/ComponentExplorer.ts": {
		"date": 1740518126597.6243,
		"jassijs_editor.ComponentExplorer": {}
	},
	"jassijs_editor/ComponentPalette.ts": {
		"date": 1740651439292.9773,
		"jassijs_editor.ComponentPalette": {}
	},
	"jassijs_editor/ComponentSpy.ts": {
		"date": 1740510338564.4038,
		"jassijs_editor.ui.ComponentSpy": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"dummy": {
					"$Action": [
						{
							"name": "Administration",
							"icon": "mdi mdi-account-cog-outline"
						}
					]
				},
				"showDialog": {
					"$Action": [
						{
							"name": "Administration/Spy Components",
							"icon": "mdi mdi-police-badge"
						}
					]
				}
			}
		}
	},
	"jassijs_editor/DatabaseDesigner.ts": {
		"date": 1740518198514.8262,
		"jassijs_editor/DatabaseDesigner": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"showDialog": {
					"$Action": [
						{
							"name": "Administration/Database Designer",
							"icon": "mdi mdi-database-edit"
						}
					]
				}
			}
		}
	},
	"jassijs_editor/Debugger.ts": {
		"date": 1656019586000,
		"jassijs_editor.Debugger": {}
	},
	"jassijs_editor/ErrorPanel.ts": {
		"date": 1720116488294.8394,
		"jassijs_editor.ui.ErrorPanel": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"showDialog": {
					"$Action": [
						{
							"name": "Administration/Errors",
							"icon": "mdi mdi-emoticon-confused-outline"
						}
					]
				}
			}
		}
	},
	"jassijs_editor/ext/monaco.ts": {
		"date": 1720105252684.6934
	},
	"jassijs_editor/ext/monaco2.ts": {
		"date": 1720090850426.468
	},
	"jassijs_editor/ext/typescriptservices.ts": {
		"date": 1720556246507.595
	},
	"jassijs_editor/FileExplorer.ts": {
		"date": 1683575950000,
		"jassijs_editor.ui.FileActions": {
			"$ActionProvider": [
				"jassijs.remote.FileNode"
			],
			"@members": {
				"newFile": {
					"$Action": [
						{
							"name": "New/File",
							"icon": "mdi mdi-file",
							"isEnabled": "function"
						}
					]
				},
				"download": {
					"$Action": [
						{
							"name": "Download",
							"isEnabled": "function"
						}
					]
				},
				"newFolder": {
					"$Action": [
						{
							"name": "New/Folder",
							"isEnabled": "function"
						}
					]
				},
				"newModule": {
					"$Action": [
						{
							"name": "New/Module",
							"isEnabled": "function"
						}
					]
				},
				"dodelete": {
					"$Action": [
						{
							"name": "Delete"
						}
					]
				},
				"mapLocalFolder": {
					"$Action": [
						{
							"name": "Map local folder",
							"isEnabled": "function"
						}
					]
				},
				"closeLocalFolder": {
					"$Action": [
						{
							"name": "Close local folder",
							"isEnabled": "function"
						}
					]
				},
				"rename": {
					"$Action": [
						{
							"name": "Rename"
						}
					]
				},
				"refresh": {
					"$Action": [
						{
							"name": "Refresh"
						}
					]
				},
				"open": {
					"$Action": [
						{
							"name": "Open",
							"isEnabled": "function"
						}
					]
				}
			}
		},
		"jassijs.ui.FileExplorer": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"show": {
					"$Action": [
						{
							"name": "Windows/Development/Files",
							"icon": "mdi mdi-file-tree"
						}
					]
				}
			}
		}
	},
	"jassijs_editor/HtmlDesigner.ts": {
		"date": 1740742771963.561,
		"jassijs_editor.HtmlDesigner": {}
	},
	"jassijs_editor/modul.ts": {
		"date": 1720612634385.9824
	},
	"jassijs_editor/MonacoPanel.ts": {
		"date": 1720101262364.5872,
		"jassijs_editor.MonacoPanel": {}
	},
	"jassijs_editor/SearchExplorer.ts": {
		"date": 1720256623984.0022,
		"jassijs_editor.ui.SearchExplorer": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"show": {
					"$Action": [
						{
							"name": "Windows/Development/Search",
							"icon": "mdi mdi-folder-search-outline"
						}
					]
				}
			}
		}
	},
	"jassijs_editor/StartEditor.ts": {
		"date": 1720115090825.8567
	},
	"jassijs_editor/template/TemplateDBDialog.ts": {
		"date": 1721659030283.6165,
		"jassijs_editor.template.TemplateDBDialogProperties": {
			"@members": {}
		},
		"jassijs.template.TemplateDBDialog": {
			"$ActionProvider": [
				"jassijs.remote.FileNode"
			],
			"@members": {
				"newFile": {
					"$Action": [
						{
							"name": "New/DBDialog",
							"isEnabled": "function"
						}
					]
				}
			}
		}
	},
	"jassijs_editor/template/TemplateDBObject.ts": {
		"date": 1681570394000,
		"jassijs_editor.template.TemplateDBObjectProperties": {
			"@members": {}
		},
		"jassijs.template.TemplateDBObject": {
			"$ActionProvider": [
				"jassijs.remote.FileNode"
			],
			"@members": {
				"newFile": {
					"$Action": [
						{
							"name": "New/DBObject",
							"isEnabled": "function"
						}
					]
				}
			}
		}
	},
	"jassijs_editor/template/TemplateEmptyDialog.ts": {
		"date": 1740567736806.9265,
		"jassijs_editor.template.TemplateEmptyDialog": {
			"$ActionProvider": [
				"jassijs.remote.FileNode"
			],
			"@members": {
				"newFile": {
					"$Action": [
						{
							"name": "New/Dialog.ts",
							"isEnabled": "function"
						}
					]
				}
			}
		}
	},
	"jassijs_editor/template/TemplateRemoteObject.ts": {
		"date": 1750577040067.4404,
		"jassijs_editor.template.TemplateRemoteObject": {
			"$ActionProvider": [
				"jassijs.remote.FileNode"
			],
			"@members": {
				"newFile": {
					"$Action": [
						{
							"name": "New/RemoteObject",
							"isEnabled": "function"
						}
					]
				}
			}
		}
	},
	"jassijs_editor/util/DatabaseSchema.ts": {
		"date": 1720101271019.9363,
		"jassijs_editor.util.DatabaseSchema": {}
	},
	"jassijs_editor/util/DragAndDropper.ts": {
		"date": 1657925428000,
		"jassijs_editor.util.DragAndDropper": {}
	},
	"jassijs_editor/util/Parser.ts": {
		"date": 1740570775364.1863,
		"jassijs_editor.util.Parser": {}
	},
	"jassijs_editor/util/Resizer.ts": {
		"date": 1740742895352.4688,
		"jassijs_editor.util.Resizer": {}
	},
	"jassijs_editor/util/Tests.ts": {
		"date": 1739727794640.8933,
		"jassijs_editor.ui.TestAction": {
			"$ActionProvider": [
				"jassijs.remote.FileNode"
			],
			"@members": {
				"testNode": {
					"$Action": [
						{
							"name": "Run Tests"
						}
					]
				}
			}
		}
	},
	"jassijs_editor/util/TSSourceMap.ts": {
		"date": 1720117379608.988,
		"jassijs_editor.util.TSSourceMap": {}
	},
	"jassijs_editor/util/Typescript.ts": {
		"date": 1750449152303.9917,
		"jassijs_editor.util.Typescript": {}
	},
	"jassijs_editor/template/TemplateEmptyTSXDialog.ts": {
		"date": 1740589015740.2244,
		"jassijs_editor.template.TemplateEmptyTSXDialog": {
			"$ActionProvider": [
				"jassijs.remote.FileNode"
			],
			"@members": {
				"newFile": {
					"$Action": [
						{
							"name": "New/Dialog.tsx",
							"isEnabled": "function"
						}
					]
				}
			}
		}
	},
	"jassijs_editor/ext/Monaco.ts": {
		"date": 1720105252684.6934
	}
}
 }
});