"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"jassijs/index.d.ts": {
		"date": 1681918736000
	},
	"jassijs/remote/Classes.ts": {
		"date": 1686759604000,
		"jassijs.remote.JassiError": {},
		"jassijs.remote.Classes": {}
	},
	"jassijs/remote/ClientError.ts": {
		"date": 1655556930000,
		"jassijs.remote.ClientError": {}
	},
	"jassijs/remote/Config.ts": {
		"date": 1719331708682.118
	},
	"jassijs/remote/Database.ts": {
		"date": 1655556796000,
		"jassijs.remote.Database": {}
	},
	"jassijs/remote/DatabaseTools.ts": {
		"date": 1750577290597.1262,
		"jassijs.remote.DatabaseTools": {
			"@members": {
				"runSQL": {
					"ValidateFunctionParameter": []
				}
			}
		}
	},
	"jassijs/remote/DBArray.ts": {
		"date": 1655556796000,
		"jassijs.remote.DBArray": {}
	},
	"jassijs/remote/DBObject.ts": {
		"date": 1752176823845.5918,
		"jassijs.remote.DBObject": {}
	},
	"jassijs/remote/DBObjectQuery.ts": {
		"date": 1623876714000
	},
	"jassijs/remote/Extensions.ts": {
		"date": 1626209336000
	},
	"jassijs/remote/FileNode.ts": {
		"date": 1655556796000,
		"jassijs.remote.FileNode": {}
	},
	"jassijs/remote/hallo.ts": {
		"date": 1622985410000
	},
	"jassijs/remote/Jassi.ts": {
		"date": 1697209123749.7214
	},
	"jassijs/remote/JassijsGlobal.ts": {
		"date": 1655549782000
	},
	"jassijs/remote/Modules.ts": {
		"date": 1682799476000
	},
	"jassijs/remote/ObjectTransaction.ts": {
		"date": 1622985414000
	},
	"jassijs/remote/Registry.ts": {
		"date": 1753729243466.9514
	},
	"jassijs/remote/RemoteObject.ts": {
		"date": 1750788682336.6975,
		"jassijs.remote.RemoteObject": {}
	},
	"jassijs/remote/RemoteProtocol.ts": {
		"date": 1753949539547.0193,
		"jassijs.remote.RemoteProtocol": {}
	},
	"jassijs/remote/security/Group.ts": {
		"date": 1682888736000,
		"jassijs.security.Group": {
			"$DBObject": [
				{
					"name": "jassijs_group"
				}
			],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"name": {
					"Column": []
				},
				"parentRights": {
					"ManyToMany": [
						"function",
						"function"
					]
				},
				"rights": {
					"ManyToMany": [
						"function",
						"function"
					]
				},
				"users": {
					"ManyToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"jassijs/remote/security/ParentRight.ts": {
		"date": 1681581398000,
		"jassijs.security.ParentRight": {
			"$DBObject": [
				{
					"name": "jassijs_parentright"
				}
			],
			"@members": {
				"id": {
					"PrimaryGeneratedColumn": []
				},
				"name": {
					"Column": []
				},
				"classname": {
					"Column": []
				},
				"i1": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"i2": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"s1": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"s2": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"groups": {
					"ManyToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"jassijs/remote/security/Right.ts": {
		"date": 1681322768000,
		"jassijs.security.Right": {
			"$DBObject": [
				{
					"name": "jassijs_right"
				}
			],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"name": {
					"Column": []
				},
				"groups": {
					"ManyToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"jassijs/remote/security/Rights.ts": {
		"date": 1750088842327.8132,
		"jassijs.security.Rights": {}
	},
	"jassijs/remote/security/Setting.ts": {
		"date": 1749964183518.1116,
		"jassijs.security.Setting": {
			"$DBObject": [
				{
					"name": "jassijs_setting"
				}
			],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"data": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"jassijs/remote/security/User.ts": {
		"date": 1681329604000,
		"jassijs.security.User": {
			"$DBObject": [
				{
					"name": "jassijs_user"
				}
			],
			"@members": {
				"id": {
					"PrimaryGeneratedColumn": []
				},
				"email": {
					"Column": []
				},
				"password": {
					"Column": [
						{
							"select": false
						}
					]
				},
				"groups": {
					"ManyToMany": [
						"function",
						"function"
					]
				},
				"isAdmin": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"jassijs/remote/Server.ts": {
		"date": 1750536455548.542,
		"jassijs.remote.Server": {
			"@members": {
				"dir": {
					"ValidateFunctionParameter": []
				},
				"zip": {
					"ValidateFunctionParameter": []
				},
				"loadFiles": {
					"ValidateFunctionParameter": []
				},
				"loadFile": {
					"ValidateFunctionParameter": []
				},
				"saveFiles": {
					"ValidateFunctionParameter": []
				},
				"saveFile": {
					"ValidateFunctionParameter": []
				},
				"testServersideFile": {
					"ValidateFunctionParameter": []
				},
				"removeServerModul": {
					"ValidateFunctionParameter": []
				},
				"delete": {
					"ValidateFunctionParameter": []
				},
				"rename": {
					"ValidateFunctionParameter": []
				},
				"createFile": {
					"ValidateFunctionParameter": []
				},
				"createFolder": {
					"ValidateFunctionParameter": []
				},
				"createModule": {
					"ValidateFunctionParameter": []
				},
				"mytest": {
					"ValidateFunctionParameter": []
				}
			}
		}
	},
	"jassijs/remote/Serverservice.ts": {
		"date": 1750503957693.7708
	},
	"jassijs/remote/Settings.ts": {
		"date": 1750539223887.9446,
		"jassijs.remote.Settings": {
			"@members": {
				"remove": {
					"ValidateFunctionParameter": []
				},
				"save": {
					"ValidateFunctionParameter": []
				},
				"saveAll": {
					"ValidateFunctionParameter": []
				}
			}
		}
	},
	"jassijs/remote/Test.ts": {
		"date": 1655556930000,
		"jassijs.remote.Test": {}
	},
	"jassijs/remote/Transaction.ts": {
		"date": 1750792975505.7617,
		"jassijs.remote.Transaction": {},
		"jassijs.remote.TransactionTest": {
			"@members": {
				"hi": {
					"UseServer": []
				}
			}
		}
	},
	"jassijs/remote/Validator.ts": {
		"date": 1750544362041.928
	},
	"jassijs/server/Compile.ts": {
		"date": 1749969355673.02
	},
	"jassijs/server/Cookies.ts": {
		"date": 1682364420000
	},
	"jassijs/server/CreatePackage.ts": {
		"date": 1682971612000
	},
	"jassijs/server/DatabaseSchema.ts": {
		"date": 1682241710000
	},
	"jassijs/server/DBManager.ts": {
		"date": 1753948011624.183,
		"jassijs/server/DBManager": {
			"$Serverservice": [
				{
					"name": "db",
					"getInstance": "function"
				}
			]
		}
	},
	"jassijs/server/DBManagerExt.ts": {
		"date": 1682717756000
	},
	"jassijs/server/DoRemoteProtocol.ts": {
		"date": 1754463599103.0662
	},
	"jassijs/server/ext/EmpyDeclaration.ts": {
		"date": 1682275348000
	},
	"jassijs/server/ext/jszip.ts": {
		"date": 1657714030000
	},
	"jassijs/server/Filesystem.ts": {
		"date": 1753961284581.5793,
		"jassijs.server.Filesystem": {
			"$Serverservice": [
				{
					"name": "filesystem",
					"getInstance": "function"
				}
			]
		}
	},
	"jassijs/server/FileTools.ts": {
		"date": 1753965873995.915
	},
	"jassijs/server/Indexer.ts": {
		"date": 1722612829860.7268
	},
	"jassijs/server/JassiServer.ts": {
		"date": 1754140962527.3452
	},
	"jassijs/server/LocalProtocol.ts": {
		"date": 1697207752396.3682
	},
	"jassijs/server/NativeAdapter.ts": {
		"date": 1720182392512.7004
	},
	"jassijs/server/PassportLoginRegister.ts": {
		"date": 1754463581383.8677
	},
	"jassijs/server/PassportSetup.ts": {
		"date": 1680946688000
	},
	"jassijs/server/RawBody.ts": {
		"date": 1654195782000
	},
	"jassijs/server/RegistryIndexer.ts": {
		"date": 1753727085400.3452
	},
	"jassijs/server/Reloader.ts": {
		"date": 1684435442000
	},
	"jassijs/server/Testuser.ts": {
		"date": 1655556794000,
		"Testuser": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"firstname": {
					"Column": []
				},
				"lastname": {
					"Column": []
				}
			}
		}
	},
	"jassijs/server/TypeORMListener.ts": {
		"date": 1697207709231.553,
		"jassijs.server.TypeORMListener": {
			"EventSubscriber": []
		}
	},
	"jassijs/server/UpdatePackage.ts": {
		"date": 1754133064195.6643
	},
	"jassijs/server/Zip.ts": {
		"date": 1622984046000
	},
	"jassijs/UserModel.ts": {
		"date": 1622984046000
	},
	"jassijs/util/DatabaseSchema.ts": {
		"date": 1611490792000
	},
	"jassijs/remote/RemoteTest.ts": {
		"date": 1750787386563.1096,
		"jassijs.remote.RemoteTest": {
			"@members": {
				"createFolder2": {
					"UseServer": []
				},
				"mytest2": {
					"UseServer": []
				}
			}
		}
	},
	"jassijs/remote/Context.ts": {
		"date": 1750451805597.2747
	},
	"jassijs/remote/Context2.ts": {
		"date": 1749959261684.3096
	},
	"jassijs/remote/StackContext.ts": {
		"date": 1749958831997.4402
	},
	"jassijs/server/PackServerFiles.ts": {
		"date": 1753955421011.6997
	},
	"jassijs/server/Events.ts": {
		"date": 1751803698056.834
	},
	"jassijs/remote/Runlocalserver.ts": {
		"date": 1753970675254.8625
	},
	"jassijs/remote/Testlocalserver.ts": {
		"date": 1753729472429.9197
	},
	"jassijs/remote/Npm.ts": {
		"date": 1753558429561.62
	},
	"jassijs/remote/PatchTTP.ts": {
		"date": 1753968322370.392
	}
}