"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"northwind/remote/Customer.ts": {
		"date": 1615052487959,
		"northwind.Customer": {
			"$DBObject": []
		}
	},
	"northwind/remote/Employees.ts": {
		"date": 1615492081804,
		"northwind.Employees": {
			"$DBObject": []
		}
	}
}