//this file is autogenerated don't modify
define("de/registry",["require"], function(require) {
 return {
  default: {
	"de/DialogKunde.ts": {
		"date": 1654120560798,
		"de.DialogKunde": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"value": {
					"$Property": [
						{
							"isUrlTag": true,
							"id": true,
							"editor": "jassijs.ui.PropertyEditors.DBObjectEditor"
						}
					]
				},
				"dummy": {
					"$Action": [
						{
							"name": "Demo",
							"icon": "mdi mdi-television-play"
						}
					]
				},
				"showDialog": {
					"$Action": [
						{
							"name": "Demo/Kunden",
							"icon": "mdi mdi-account"
						}
					]
				}
			}
		}
	},
	"de/KundeView.ts": {
		"date": 1654466242688,
		"de.KundeView": {
			"$DBObjectView": [
				{
					"classname": "de.Kunde"
				}
			],
			"@members": {
				"value": {
					"$Property": [
						{
							"isUrlTag": true,
							"id": true,
							"editor": "jassijs.ui.PropertyEditors.DBObjectEditor"
						}
					]
				}
			}
		}
	},
	"de/modul.ts": {
		"date": 1626121322000
	},
	"de/remote/AR.ts": {
		"date": 1622985478000,
		"de.AR": {
			"$Rights": [
				[
					{
						"name": "Auftragswesen/Ausgangsrechnung/festschreiben"
					},
					{
						"name": "Auftragswesen/Ausgangsrechnung/löschen"
					}
				]
			],
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"strasse": {
					"Column": []
				},
				"nummer": {
					"Column": []
				},
				"ort": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"kunde": {
					"$CheckParentRight": [],
					"ManyToOne": [
						"function",
						"function"
					]
				},
				"zeilen": {
					"OneToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"de/remote/ARZeile.ts": {
		"date": 1622985480000,
		"de.ARZeile": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryGeneratedColumn": []
				},
				"text": {
					"Column": []
				},
				"position": {
					"Column": []
				},
				"preis": {
					"Column": [
						{
							"nullable": true,
							"type": "decimal"
						}
					]
				},
				"ar": {
					"$CheckParentRight": [],
					"ManyToOne": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"de/remote/Kunde.ext.ts": {
		"date": 1622985484000
	},
	"de/remote/Kunde.ts": {
		"date": 1634384660000,
		"de.Kunde": {
			"$ParentRights": [
				[
					{
						"name": "Kundennummern",
						"sqlToCheck": "me.id>=:i1 and me.id<=:i2",
						"description": {
							"text": "Kundennummern",
							"i1": "von",
							"i2": "bis"
						}
					}
				]
			],
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"vorname": {
					"Column": []
				},
				"nachname": {
					"Column": []
				},
				"strasse": {
					"Column": []
				},
				"PLZ": {
					"Column": []
				},
				"ort": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"hausnummer": {
					"Column": []
				},
				"rechnungen": {
					"OneToMany": [
						"function",
						"function"
					]
				},
				"alleKundenNachNachname": {
					"$DBObjectQuery": [
						{
							"name": "Alle nach Namen",
							"description": "Kundenliste nach Namen"
						}
					]
				},
				"alleKundenNachNummer": {
					"$DBObjectQuery": [
						{
							"name": "Alle nach Nummer",
							"description": "Kundenliste nach Nummer"
						}
					]
				},
				"land": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"de/remote/KundeExt.ts": {
		"date": 1626122324000,
		"de.KundeExt": {
			"$Extension": [
				"de.Kunde"
			]
		}
	},
	"de/remote/KundeExt2.ts": {
		"date": 1654120297933,
		"de.KundeExt2": {
			"$Extension": [
				"de.Kunde"
			]
		}
	},
	"de/remote/Lieferant.ts": {
		"date": 1622985490000,
		"de.Lieferant": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"name": {
					"Column": [
						{
							"nullable": false
						}
					]
				}
			}
		}
	},
	"de/remote/MyUser.ts": {
		"date": 1622985492000,
		"de.MyUser": {
			"$DBObject": [],
			"Entity": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"firstName": {
					"Column": []
				},
				"lastName": {
					"Column": []
				},
				"age": {
					"Column": []
				}
			}
		}
	},
	"de/ReportKunde.ts": {
		"date": 1631970006000,
		"de.ReportKunde": {
			"@members": {
				"value": {
					"$Property": [
						{
							"isUrlTag": true,
							"id": true,
							"editor": "jassijs.ui.PropertyEditors.DBObjectEditor"
						}
					]
				}
			}
		}
	},
	"de/TestExtension.ts": {
		"date": 1624293156000
	},
	"de/Dialog.ts": {
		"date": 1654630361579,
		"de/Dialog": {}
	},
	"de/TTDialog.ts": {
		"date": 1654630413588,
		"de/TTDialog": {}
	},
	"de/MyDialog.ts": {
		"date": 1654631976092,
		"de/MyDialog": {}
	}
}
 }
});