//this file is autogenerated don't modify
define("de/registry", ["require"], function (require) {
    return {
        default: {
            "de/Dialog.ts": {
                "date": 1624143167811,
                "de/Dialog": {}
            },
            "de/DialogKunde.ts": {
                "date": 1627562582252,
                "de.DialogKunde": {
                    "$ActionProvider": [
                        "jassijs.base.ActionNode"
                    ],
                    "@members": {
                        "value": {
                            "$Property": [
                                {
                                    "isUrlTag": true,
                                    "id": true,
                                    "editor": "jassijs.ui.PropertyEditors.DBObjectEditor"
                                }
                            ]
                        },
                        "dummy": {
                            "$Action": [
                                {
                                    "name": "Demo",
                                    "icon": "mdi mdi-television-play"
                                }
                            ]
                        },
                        "showDialog": {
                            "$Action": [
                                {
                                    "name": "Demo/Kunden",
                                    "icon": "mdi mdi-account"
                                }
                            ]
                        }
                    }
                }
            },
            "de/KundeView.ts": {
                "date": 1624207911110,
                "de.KundeView": {
                    "$DBObjectView": [
                        {
                            "classname": "de.Kunde"
                        }
                    ],
                    "@members": {
                        "value": {
                            "$Property": [
                                {
                                    "isUrlTag": true,
                                    "id": true,
                                    "editor": "jassijs.ui.PropertyEditors.DBObjectEditor"
                                }
                            ]
                        }
                    }
                }
            },
            "de/modul.ts": {
                "date": 1626121321303
            },
            "de/remote/AR.ts": {
                "date": 1622985477990,
                "de.AR": {
                    "$Rights": [
                        [
                            {
                                "name": "Auftragswesen/Ausgangsrechnung/festschreiben"
                            },
                            {
                                "name": "Auftragswesen/Ausgangsrechnung/löschen"
                            }
                        ]
                    ],
                    "$DBObject": [],
                    "@members": {
                        "id": {
                            "PrimaryColumn": []
                        },
                        "strasse": {
                            "Column": []
                        },
                        "nummer": {
                            "Column": []
                        },
                        "ort": {
                            "Column": [
                                {
                                    "nullable": true
                                }
                            ]
                        },
                        "kunde": {
                            "$CheckParentRight": [],
                            "ManyToOne": [
                                "function",
                                "function"
                            ]
                        },
                        "zeilen": {
                            "OneToMany": [
                                "function",
                                "function"
                            ]
                        }
                    }
                }
            },
            "de/remote/ARZeile.ts": {
                "date": 1622985479813,
                "de.ARZeile": {
                    "$DBObject": [],
                    "@members": {
                        "id": {
                            "PrimaryGeneratedColumn": []
                        },
                        "text": {
                            "Column": []
                        },
                        "position": {
                            "Column": []
                        },
                        "preis": {
                            "Column": [
                                {
                                    "nullable": true,
                                    "type": "decimal"
                                }
                            ]
                        },
                        "ar": {
                            "$CheckParentRight": [],
                            "ManyToOne": [
                                "function",
                                "function"
                            ]
                        }
                    }
                }
            },
            "de/remote/Kunde.ts": {
                "date": 1626122987760,
                "de.Kunde": {
                    "$ParentRights": [
                        [
                            {
                                "name": "Kundennummern",
                                "sqlToCheck": "me.id>=:i1 and me.id<=:i2",
                                "description": {
                                    "text": "Kundennummern",
                                    "i1": "von",
                                    "i2": "bis"
                                }
                            }
                        ]
                    ],
                    "$DBObject": [],
                    "@members": {
                        "id": {
                            "PrimaryColumn": []
                        },
                        "vorname": {
                            "Column": []
                        },
                        "nachname": {
                            "Column": []
                        },
                        "strasse": {
                            "Column": []
                        },
                        "PLZ": {
                            "Column": []
                        },
                        "ort": {
                            "Column": [
                                {
                                    "nullable": true
                                }
                            ]
                        },
                        "hausnummer": {
                            "Column": []
                        },
                        "rechnungen": {
                            "OneToMany": [
                                "function",
                                "function"
                            ]
                        },
                        "alleKundenNachNachname": {
                            "$DBObjectQuery": [
                                {
                                    "name": "Alle nach Namen",
                                    "description": "Kundenliste nach Namen"
                                }
                            ]
                        },
                        "alleKundenNachNummer": {
                            "$DBObjectQuery": [
                                {
                                    "name": "Alle nach Nummer",
                                    "description": "Kundenliste nach Nummer"
                                }
                            ]
                        },
                        "land": {
                            "Column": [
                                {
                                    "nullable": true
                                }
                            ]
                        }
                    }
                }
            },
            "de/remote/KundeExt.ts": {
                "date": 1626122322826,
                "de.KundeExt": {
                    "$Extension": [
                        "de.Kunde"
                    ]
                }
            },
            "de/remote/KundeExt2.ts": {
                "date": 1626123322693,
                "de.KundeExt2": {
                    "$Extension": [
                        "de.Kunde"
                    ]
                }
            },
            "de/remote/Lieferant.ts": {
                "date": 1622985489873,
                "de.Lieferant": {
                    "$DBObject": [],
                    "@members": {
                        "id": {
                            "PrimaryColumn": []
                        },
                        "name": {
                            "Column": [
                                {
                                    "nullable": false
                                }
                            ]
                        }
                    }
                }
            },
            "de/remote/MyUser.ts": {
                "date": 1622985491688,
                "de.MyUser": {
                    "$DBObject": [],
                    "Entity": [],
                    "@members": {
                        "id": {
                            "PrimaryColumn": []
                        },
                        "firstName": {
                            "Column": []
                        },
                        "lastName": {
                            "Column": []
                        },
                        "age": {
                            "Column": []
                        }
                    }
                }
            },
            "de/ReportKunde.ts": {
                "date": 1624208090062,
                "de.ReportKunde": {
                    "@members": {
                        "value": {
                            "$Property": [
                                {
                                    "isUrlTag": true,
                                    "id": true,
                                    "editor": "jassijs.ui.PropertyEditors.DBObjectEditor"
                                }
                            ]
                        }
                    }
                }
            },
            "de/T.ts": {
                "date": 1626210632530
            },
            "de/TestExtension.ts": {
                "date": 1624293154792
            },
            "de/remote/Kunde.ext.ts": {
                "date": 1622985482440
            }
        }
    };
});
//# sourceMappingURL=registry.js.map