import { Calendar } from "jassi/ui/Calendar";
import { ObjectChooser } from "jassi/ui/ObjectChooser";
import { HTMLPanel } from "jassi/ui/HTMLPanel";
import { NumberConverter } from "jassi/ui/converters/NumberConverter";
import { Textbox } from "jassi/ui/Textbox";
import { $Class } from "jassi/remote/Jassi";
import { Panel } from "jassi/ui/Panel";
import { $Property } from "jassi/ui/Property";
import { Orders } from "northwind/remote/Orders";
import { Databinder } from "jassi/ui/Databinder";
import { DBObjectView, $DBObjectView, DBObjectViewMe } from "jassi/ui/DBObjectView";
import { DBObjectDialog } from "jassi/ui/DBObjectDialog";
import { Customer } from "northwind/remote/Customer";
type Me = {
    id?: Textbox;
    customername?: HTMLPanel;
    employeename?: HTMLPanel;
    chooseEmployee?: ObjectChooser;
    choosecustomer?: ObjectChooser;
    orderDate?: Calendar;
    requiredDate?: Calendar;
    shippedDate?: Calendar;
    shipVia?: HTMLPanel;
    shipviaChooser?: ObjectChooser;
    freight?: Textbox;
    shipName?: Textbox;
    shipAddress?: Textbox;
    shipPostalCode?: Textbox;
    shipCity?: Textbox;
    shipCountry?: Textbox;
    shipRegion?: Textbox;
} & DBObjectViewMe;
@$DBObjectView({ classname: "northwind.Orders", actionname: "Northwind/Orders", icon: "mdi mdi-script-text" })
@$Class("northwind.OrdersView")
export class OrdersView extends DBObjectView {
    me: Me;
    @$Property({ isUrlTag: true, id: true, editor: "jassi.ui.PropertyEditors.DBObjectEditor" })
    value: Orders;
    constructor() {
        super();
        //this.me = {}; this is called in objectdialog
        this.layout(this.me);
    }
    get title() {
        return this.value === undefined ? "OrdersView" : "OrdersView " + this.value.id;
    }
    layout(me: Me) {
        me.id = new Textbox();
        me.customername = new HTMLPanel();
        me.employeename = new HTMLPanel();
        me.chooseEmployee = new ObjectChooser();
        me.choosecustomer = new ObjectChooser();
        me.orderDate = new Calendar();
        me.requiredDate = new Calendar();
        me.shippedDate = new Calendar();
        me.shipVia = new HTMLPanel();
        me.shipviaChooser = new ObjectChooser();
        me.freight = new Textbox();
        me.shipName = new Textbox();
        me.shipAddress = new Textbox();
        me.shipPostalCode = new Textbox();
        me.shipCity = new Textbox();
        me.shipCountry = new Textbox();
        me.shipRegion = new Textbox();
        me.main.isAbsolute = true;
        me.main.height = "500";
        me.main.width = 735;
        me.main.add(me.id);
        me.main.add(me.customername);
        me.main.add(me.shippedDate);
        me.main.add(me.requiredDate);
        me.main.add(me.orderDate);
        me.main.add(me.choosecustomer);
        me.main.add(me.chooseEmployee);
        me.main.add(me.employeename);
        me.main.add(me.shipVia);
        me.main.add(me.shipviaChooser);
        me.main.add(me.freight);
        me.main.add(me.shipName);
        me.main.add(me.shipAddress);
        me.main.add(me.shipPostalCode);
        me.main.add(me.shipCity);
        me.main.add(me.shipRegion);
        me.main.add(me.shipCountry);
        me.id.x = 5;
        me.id.y = 10;
        me.id.converter = new NumberConverter();
        me.id.bind(me.databinder, "id");
        me.id.label = "Order ID";
        me.id.width = 70;
        me.customername.x = 425;
        me.customername.y = 10;
        me.customername.width = 265;
        me.customername.template = "{{id}} {{CompanyName}}";
        me.customername.bind(me.databinder, "Customer");
        me.customername.value = "VINET Vins et alcools Chevalier";
        me.customername.label = "Customer";
        me.employeename.x = 425;
        me.employeename.y = 100;
        me.employeename.bind(me.databinder, "Employee");
        me.employeename.label = "Employee";
        me.employeename.width = 265;
        me.employeename.value = "5 Steven Buchanan";
        me.employeename.template = "{{id}} {{FirstName}} {{LastName}}";
        me.chooseEmployee.x = 695;
        me.chooseEmployee.y = 115;
        me.chooseEmployee.bind(me.databinder, "Employee");
        me.chooseEmployee.items = "northwind.Employees";
        me.choosecustomer.x = 695;
        me.choosecustomer.y = 25;
        me.choosecustomer.items = "northwind.Customer";
        me.choosecustomer.bind(me.databinder, "Customer");
        me.choosecustomer.onchange(function (event) {
            let cust = <Customer>me.choosecustomer.value;
            me.shipName.value = cust.CompanyName;
            me.shipAddress.value = cust.Address;
            me.shipPostalCode.value = cust.PostalCode;
            me.shipCity.value = cust.City;
            me.shipCountry.value = cust.Country;
            me.shipRegion.value = cust.Region;
        });
        me.orderDate.x = 425;
        me.orderDate.y = 140;
        me.orderDate.bind(me.databinder, "OrderDate");
        me.orderDate.label = "Order Date";
        me.orderDate.width = 70;
        me.requiredDate.x = 510;
        me.requiredDate.y = 140;
        me.requiredDate.bind(me.databinder, "RequiredDate");
        me.requiredDate.label = "Required Date";
        me.requiredDate.width = 75;
        me.shippedDate.x = 600;
        me.shippedDate.y = 140;
        me.shippedDate.bind(me.databinder, "ShippedDate");
        me.shippedDate.width = 75;
        me.shippedDate.label = "Shipped Date";
        me.shipVia.x = 425;
        me.shipVia.y = 55;
        me.shipVia.bind(me.databinder, "ShipVia");
        me.shipVia.template = "{{id}} {{CompanyName}}";
        me.shipVia.label = "Ship via";
        me.shipVia.value = "3 Federal Shipping";
        me.shipVia.width = 265;
        me.shipviaChooser.x = 695;
        me.shipviaChooser.y = 70;
        me.shipviaChooser.bind(me.databinder, "ShipVia");
        me.shipviaChooser.items = "northwind.Shippers";
        me.freight.x = 85;
        me.freight.y = 10;
        me.freight.bind(me.databinder, "Freight");
        me.freight.width = 60;
        me.freight.label = "Freight";
        me.shipName.x = 5;
        me.shipName.y = 60;
        me.shipName.bind(me.databinder, "ShipName");
        me.shipName.width = 220;
        me.shipName.label = "Ship Name";
        me.shipAddress.x = 5;
        me.shipAddress.y = 105;
        me.shipAddress.bind(me.databinder, "ShipAddress");
        me.shipAddress.width = 220;
        me.shipAddress.label = "Ship Address";
        me.shipPostalCode.x = 5;
        me.shipPostalCode.y = 150;
        me.shipPostalCode.bind(me.databinder, "ShipPostalCode");
        me.shipPostalCode.width = 55;
        me.shipPostalCode.label = "Postal Code";
        me.shipCity.x = 75;
        me.shipCity.y = 150;
        me.shipCity.bind(me.databinder, "ShipCity");
        me.shipCity.label = "Ship City";
        me.shipCity.width = 150;
        me.shipCountry.x = 135;
        me.shipCountry.y = 195;
        me.shipCountry.bind(me.databinder, "ShipCountry");
        me.shipCountry.label = "Ship Country";
        me.shipCountry.width = 90;
        me.shipRegion.x = 5;
        me.shipRegion.y = 195;
        me.shipRegion.bind(me.databinder, "ShipRegion");
        me.shipRegion.label = "Ship Region";
        me.shipRegion.width = 120;
    }
}
export async function test() {
    var ret = new OrdersView;
    ret["value"] = <Orders>await Orders.findOne({ id: 10250, relations: ["*"] });
    return ret;
}
