//this file is autogenerated don't modify
define("northwind/registry",["require"], function(require) {
 return {
  default: {
	"northwind/CategoriesView.ts": {
		"date": 1656505473915,
		"northwind.CategoriesView": {
			"$DBObjectView": [
				{
					"classname": "northwind.Categories",
					"actionname": "Northwind/Categories",
					"icon": "mdi mdi-cube"
				}
			],
			"@members": {}
		}
	},
	"northwind/CustomerView.ts": {
		"date": 1656682768374,
		"northwind/CustomerView": {
			"$DBObjectView": [
				{
					"classname": "northwind.Customer",
					"actionname": "Northwind/Customers",
					"icon": "mdi mdi-nature-people"
				}
			],
			"@members": {}
		}
	},
	"northwind/DetailTest.ts": {
		"date": 1656073047502,
		"northwind.DetailTest": {
			"$DBObjectView": [
				{
					"classname": "northwind.OrderDetails"
				}
			],
			"@members": {}
		}
	},
	"northwind/EmployeesView.ts": {
		"date": 1656682851796,
		"northwind.EmployeesView": {
			"$DBObjectView": [
				{
					"classname": "northwind.Employees",
					"actionname": "Northwind/Employees",
					"icon": "mdi mdi-account-tie"
				}
			],
			"@members": {}
		}
	},
	"northwind/ImportData.ts": {
		"date": 1656501504887,
		"northwind.ImportData": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"dummy": {
					"$Action": [
						{
							"name": "Northwind",
							"icon": "mdi mdi-warehouse"
						}
					]
				},
				"showDialog": {
					"$Action": [
						{
							"name": "Northwind/Import sample data",
							"icon": "mdi mdi-database-import"
						}
					]
				}
			}
		}
	},
	"northwind/modul.ts": {
		"date": 1613551044000
	},
	"northwind/OrdersView.ts": {
		"date": 1656682898118,
		"northwind.OrdersView": {
			"$DBObjectView": [
				{
					"classname": "northwind.Orders",
					"actionname": "Northwind/Orders",
					"icon": "mdi mdi-script-text"
				}
			],
			"@members": {}
		}
	},
	"northwind/ProductView.ts": {
		"date": 1656683100932,
		"northwind.ProductView": {
			"$DBObjectView": [
				{
					"classname": "northwind.Products",
					"actionname": "Northwind/Products",
					"icon": "mdi mdi-reproduction"
				}
			],
			"@members": {}
		}
	},
	"northwind/remote/Categories.ts": {
		"date": 1656072698870,
		"northwind.Categories": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"CategoryName": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Description": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Picture": {
					"Column": []
				},
				"Products": {
					"OneToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"northwind/remote/Customer.ts": {
		"date": 1656072702725,
		"northwind.Customer": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"CompanyName": {
					"Column": []
				},
				"ContactName": {
					"Column": []
				},
				"ContactTitle": {
					"Column": []
				},
				"Address": {
					"Column": []
				},
				"City": {
					"Column": []
				},
				"Region": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"PostalCode": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Country": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Phone": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Fax": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"northwind/remote/Employees.ts": {
		"date": 1656072706426,
		"northwind.Employees": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"LastName": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"FirstName": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Title": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"TitleOfCourtesy": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Address": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"City": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Region": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"PostalCode": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Country": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"HomePhone": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Extension": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Photo": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Notes": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"PhotoPath": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ReportsTo": {
					"JoinColumn": [],
					"ManyToOne": [
						"function"
					]
				},
				"BirthDate": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"HireDate": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"northwind/remote/OrderDetails.ts": {
		"date": 1656072709725,
		"northwind.OrderDetails": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryGeneratedColumn": []
				},
				"Order": {
					"ManyToOne": [
						"function",
						"function"
					]
				},
				"Product": {
					"ManyToOne": [
						"function"
					]
				},
				"UnitPrice": {
					"Column": [
						{
							"nullable": false,
							"type": "decimal"
						}
					]
				},
				"Quantity": {
					"Column": []
				},
				"Discount": {
					"Column": [
						{
							"nullable": true,
							"type": "decimal"
						}
					]
				}
			}
		}
	},
	"northwind/remote/Orders.ts": {
		"date": 1656072712907,
		"northwind.Orders": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"Customer": {
					"ManyToOne": [
						"function"
					]
				},
				"Employee": {
					"ManyToOne": [
						"function"
					]
				},
				"OrderDate": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"RequiredDate": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShippedDate": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipVia": {
					"ManyToOne": [
						"function"
					]
				},
				"Freight": {
					"Column": [
						{
							"nullable": true,
							"type": "decimal"
						}
					]
				},
				"ShipName": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipAddress": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipCity": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipRegion": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipPostalCode": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipCountry": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Details": {
					"OneToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"northwind/remote/Products.ts": {
		"date": 1656072718206,
		"northwind.Products": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"ProductName": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Supplier": {
					"ManyToOne": [
						"function"
					]
				},
				"Category": {
					"ManyToOne": [
						"function",
						"function"
					]
				},
				"QuantityPerUnit": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"UnitPrice": {
					"Column": [
						{
							"nullable": true,
							"type": "decimal"
						}
					]
				},
				"UnitsInStock": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"UnitsOnOrder": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ReorderLevel": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Discontinued": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"northwind/remote/Shippers.ts": {
		"date": 1656072722755,
		"northwind.Shippers": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"CompanyName": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Phone": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"northwind/remote/Suppliers.ts": {
		"date": 1656072727295,
		"northwind.Suppliers": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"CompanyName": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ContactName": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ContactTitle": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Address": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"City": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Region": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"PostalCode": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Country": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Phone": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Fax": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"HomePage": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"northwind/ShippersView.ts": {
		"date": 1656683116417,
		"northwind.ShippersView": {
			"$DBObjectView": [
				{
					"classname": "northwind.Shippers",
					"actionname": "Northwind/Shippers",
					"icon": "mdi mdi-truck-delivery"
				}
			],
			"@members": {}
		}
	},
	"northwind/SuppliersView.ts": {
		"date": 1656683257685,
		"northwind.SuppliersView": {
			"$DBObjectView": [
				{
					"classname": "northwind.Suppliers",
					"actionname": "Northwind/Suppliers",
					"icon": "mdi mdi-office-building-outline"
				}
			],
			"@members": {}
		}
	},
	"northwind/CustomerOrders.ts": {
		"date": 1656502357465,
		"northwind/CustomerOrders": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"showDialog": {
					"$Action": [
						{
							"name": "Northwind/Customer Orders",
							"icon": "mdi-script-text-play-outline"
						}
					]
				}
			}
		}
	},
	"northwind/reports/CustomerLabels.ts": {
		"date": 1656456455632,
		"nothwind.CustomerLabels": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"$Report": [
				{
					"name": "nothwind/Customer Labels",
					"actionname": "Northwind/Reports/Customer Labels",
					"icon": "mdi mdi-file-chart-outline"
				}
			],
			"@members": {
				"dummy": {
					"$Action": [
						{
							"name": "Northwind/Reports",
							"icon": "mdi mdi-file-chart-outline"
						}
					]
				}
			}
		}
	},
	"northwind/CustomerPhoneList.ts": {
		"date": 1656504951707,
		"northwind/CustomerPhoneList": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"showDialog": {
					"$Action": [
						{
							"name": "Northwind/Customer Phone List",
							"icon": "mdi-script-text-play-outline"
						}
					]
				}
			}
		}
	},
	"northwind/ProductList.ts": {
		"date": 1656508354146,
		"northwind/ProductList": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"showDialog": {
					"$Action": [
						{
							"name": "Northwind/Product List",
							"icon": "mdi mdi-reproduction"
						}
					]
				}
			}
		}
	}
}
 }
});