//this file is autogenerated don't modify
define("northwind/registry",["require"], function(require) {
 return {
  default: {
	"northwind/CustomerView.ts": {
		"date": 1613583380375,
		"northwind/CustomerView": {
			"$DBObjectView": [
				{
					"classname": "northwind.Customer",
					"actionname": "Northwind/Customers",
					"icon": "mdi mdi-nature-people"
				}
			]
		}
	},
	"northwind/EmployeesView.ts": {
		"date": 1614439057694,
		"northwind.EmployeesView": {
			"$DBObjectView": [
				{
					"classname": "northwind.Employees",
					"actionname": "Northwind/Employees",
					"icon": "mdi mdi-account-tie"
				}
			]
		}
	},
	"northwind/ImportData.ts": {
		"date": 1613935445224,
		"northwind.ImportData": {
			"$ActionProvider": [
				"jassi.base.ActionNode"
			]
		}
	},
	"northwind/modul.ts": {
		"date": 1613551043267
	},
	"northwind/remote/Customer.ts": {
		"date": 1615052487959,
		"northwind.Customer": {
			"$DBObject": []
		}
	},
	"northwind/remote/Employees.ts": {
		"date": 1614966827636,
		"northwind.Employees": {
			"$DBObject": []
		}
	}
}
 }
});