"use strict:";
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "qw/remote/Hallo.ts": {
        "date": 1622797443385,
        "qw.Hallo": {
            "$DBObject": []
        }
    },
    "qw/remote/MyRemoteObject.ts": {
        "date": 1622797098879,
        "qw/remote/MyRemoteObject": {}
    }
};
//# sourceMappingURL=registry.js.map