//this file is autogenerated don't modify
define("de/registry", ["require"], function (require) {
    return {
        default: {
            "de/d2de.ts": {
                "date": 1587933243841
            },
            "de/dd.ts": {
                "date": 1615239782948
            },
            "de/del.ts": {
                "date": 1613922613218
            },
            "de/Dialog.ts": {
                "date": 1616805942324,
                "de/Dialog": {}
            },
            "de/DialogKunde.ts": {
                "date": 1615590194855,
                "de.DialogKunde": {
                    "$ActionProvider": [
                        "jassijs.base.ActionNode"
                    ]
                }
            },
            "de/modul.ts": {
                "date": 1612818328924
            },
            "de/oo/dd.ts": {
                "date": 1588091991590
            },
            "de/pp/aa/a.ts": {
                "date": 1588092762645
            },
            "de/q.ts": {
                "date": 1588091498058
            },
            "de/remote/AR.ts": {
                "date": 1614458857516,
                "de.AR": {
                    "$Rights": [
                        [
                            {
                                "name": "Auftragswesen/Ausgangsrechnung/festschreiben"
                            },
                            {
                                "name": "Auftragswesen/Ausgangsrechnung/löschen"
                            }
                        ]
                    ],
                    "$DBObject": []
                }
            },
            "de/remote/ARZeile.ts": {
                "date": 1616791096258,
                "de.ARZeile": {
                    "$DBObject": []
                }
            },
            "de/remote/Kunde.ext.ts": {
                "date": 1613332025514
            },
            "de/remote/Kunde.ts": {
                "date": 1614464285841,
                "de.Kunde": {
                    "$ParentRights": [
                        [
                            {
                                "name": "Kundennummern",
                                "sqlToCheck": "me.id>=:i1 and me.id<=:i2",
                                "description": {
                                    "text": "Kundennummern",
                                    "i1": "von",
                                    "i2": "bis"
                                }
                            }
                        ]
                    ],
                    "$DBObject": []
                }
            },
            "de/remote/KundeExt.ts": {
                "date": 1613923393172,
                "de.KundeExt": {
                    "$Extension": [
                        "de.Kunde"
                    ]
                }
            },
            "de/remote/KundeExt2.ts": {
                "date": 1613332035281
            },
            "de/remote/Lieferant.ts": {
                "date": 1614464290662,
                "de.Lieferant": {
                    "$DBObject": []
                }
            },
            "de/remote/MyUser.ts": {
                "date": 1613330861054,
                "de.MyUser": {
                    "$DBObject": [],
                    "Entity": []
                }
            }
        }
    };
});
//# sourceMappingURL=registry.js.map
//# sourceMappingURL=registry.js.map