"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"de/remote/AR.ts": {
		"date": 1750088588608.2544,
		"de.AR": {
			"$Rights": [
				[
					{
						"name": "Auftragswesen/Ausgangsrechnung/festschreiben"
					},
					{
						"name": "Auftragswesen/Ausgangsrechnung/löschen"
					}
				]
			],
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"strasse": {
					"Column": []
				},
				"nummer": {
					"Column": []
				},
				"ort": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"kunde": {
					"ManyToOne": [
						"function",
						"function"
					]
				},
				"zeilen": {
					"OneToMany": [
						"function",
						"function"
					]
				},
				"myfind": {
					"UseServer": []
				}
			}
		}
	},
	"de/remote/ARZeile.ts": {
		"date": 1749963543806.5596,
		"de.ARZeile": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryGeneratedColumn": []
				},
				"text": {
					"Column": []
				},
				"position": {
					"Column": []
				},
				"preis": {
					"Column": [
						{
							"nullable": true,
							"type": "decimal"
						}
					]
				},
				"ar": {
					"ManyToOne": [
						"function",
						"function"
					]
				},
				"find": {
					"UseServer": []
				}
			}
		}
	},
	"de/remote/Kunde.ext.ts": {
		"date": 1622985484000
	},
	"de/remote/Kunde.ts": {
		"date": 1749964322573.4482,
		"de.Kunde": {
			"$ParentRights": [
				[
					{
						"name": "Kundennummern",
						"sqlToCheck": "me.id>=:i1 and me.id<=:i2",
						"description": {
							"text": "Kundennummern",
							"i1": "von",
							"i2": "bis"
						}
					}
				]
			],
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"vorname": {
					"Column": []
				},
				"nachname": {
					"Column": []
				},
				"strasse": {
					"Column": []
				},
				"PLZ": {
					"Column": []
				},
				"ort": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"hausnummer": {
					"Column": []
				},
				"rechnungen": {
					"OneToMany": [
						"function",
						"function"
					]
				},
				"alleKundenNachNachname": {
					"$DBObjectQuery": [
						{
							"name": "Alle nach Namen",
							"description": "Kundenliste nach Namen"
						}
					]
				},
				"alleKundenNachNummer": {
					"$DBObjectQuery": [
						{
							"name": "Alle nach Nummer",
							"description": "Kundenliste nach Nummer"
						}
					]
				},
				"find": {
					"UseServer": []
				},
				"land": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"test": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"de/remote/KundeExt.ts": {
		"date": 1655556796000,
		"de.KundeExt": {
			"$Extension": [
				"de.Kunde"
			]
		}
	},
	"de/remote/KundeExt2.ts": {
		"date": 1655556796000,
		"de.KundeExt2": {
			"$Extension": [
				"de.Kunde"
			]
		}
	},
	"de/remote/Lieferant.ts": {
		"date": 1656072674000,
		"de.Lieferant": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"name": {
					"Column": [
						{
							"nullable": false
						}
					]
				}
			}
		}
	},
	"de/remote/MyRemoteObject.ts": {
		"date": 1750546788159.0122,
		"de.remote.MyRemoteObject": {
			"@members": {
				"sayHello": {
					"ValidateFunctionParameter": []
				},
				"sayHello2": {
					"ValidateFunctionParameter": []
				}
			}
		}
	},
	"de/remote/MyUser.ts": {
		"date": 1656072680000,
		"de.MyUser": {
			"$DBObject": [],
			"Entity": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"firstName": {
					"Column": []
				},
				"lastName": {
					"Column": []
				},
				"age": {
					"Column": []
				}
			}
		}
	},
	"de/remote/DelRemoteObject.ts": {
		"date": 1750088961591.24,
		"de.remote.DelRemoteObject": {}
	},
	"de/remote/MyRemoteObject2.ts": {
		"date": 1750547089612.7952,
		"de.remote.MyRemoteObject2": {},
		"de.remote.MyRemoteObject": {
			"@members": {
				"sayHello": {
					"ValidateFunctionParameter": []
				},
				"sayHello2": {
					"ValidateFunctionParameter": []
				}
			}
		}
	},
	"de/remote/Loch.ts": {
		"date": 1750547500344.0847,
		"de.remote.Loch": {},
		"de.remote.MyRemoteObject": {
			"@members": {
				"sayHello": {
					"ValidateFunctionParameter": []
				},
				"sayHello2": {
					"ValidateFunctionParameter": []
				}
			}
		}
	},
	"de/remote/ll.ts": {
		"date": 1750547610214.476,
		"de.remote.ll": {
			"@members": {
				"sayHello": {
					"ValidateFunctionParameter": []
				},
				"info": {
					"UseServer": []
				}
			}
		}
	}
}