import { Tree } from "jassijs/ui/Tree";
import { Textarea } from "jassijs/ui/Textarea";
import { Table } from "jassijs/ui/Table";
import { Style } from "jassijs/ui/Style";
import { Repeater } from "jassijs/ui/Repeater";
import { Image } from "jassijs/ui/Image";
import { HTMLPanel } from "jassijs/ui/HTMLPanel";
import { Databinder } from "jassijs/ui/Databinder";
import { Checkbox } from "jassijs/ui/Checkbox";
import { BoxPanel } from "jassijs/ui/BoxPanel";
import { Textbox } from "jassijs/ui/Textbox";
import { Button } from "jassijs/ui/Button";
import { Panel } from "jassijs/ui/Panel";
export function test() {
    var ret = new Panel();
    var button = new Button();
    var textbox = new Textbox();
    var boxpanel = new BoxPanel();
    var checkbox = new Checkbox();
    var databinder = new Databinder();
    var htmlpanel = new HTMLPanel();
    var image = new Image();
    var repeater = new Repeater();
    var style = new Style();
    var table = new Table();
    var textarea = new Textarea();
    var tree = new Tree();
    ret.add(button);
    ret.add(textbox);
    ret.add(boxpanel);
    ret.add(image);
    ret.add(repeater);
    ret.add(style);
    ret.add(table);
    ret.add(textarea);
    ret.add(tree);
    button.text = "button";
    boxpanel.add(checkbox);
    boxpanel.add(databinder);
    boxpanel.add(htmlpanel);
    htmlpanel.value = "ddd";
    image.src = "";
    return ret;
}
document.body.append(test().dom);
