//this file is autogenerated don't modify
define("demo/registry",["require"], function(require) {
 return {
  default: {
	"demo/DelTest.ts": {
		"date": 1681563014000
	},
	"demo/Dialog.ts": {
		"date": 1655851716000,
		"demo/Dialog": {}
	},
	"demo/Dialog2.ts": {
		"date": 1695239901541.8835,
		"demo/Dialog2": {}
	},
	"demo/EmptyDialog.ts": {
		"date": 1655556796000,
		"demo.EmptyDialog": {}
	},
	"demo/LargeReport.ts": {
		"date": 1634240084000
	},
	"demo/MemoryTest.ts": {
		"date": 1681590024000
	},
	"demo/modul.ts": {
		"date": 1612818334000
	},
	"demo/MyTest.ts": {
		"date": 1655757462000
	},
	"demo/Report1.ts": {
		"date": 1656018452000
	},
	"demo/ReportInvoice.ts": {
		"date": 1681590034000,
		"demo.ReportInvoice": {}
	},
	"demo/ReportInvoice2.ts": {
		"date": 1681590038000,
		"demo.ReportInvoice": {}
	},
	"demo/ReportStyle.ts": {
		"date": 1681590044000
	},
	"demo/StyleDialog.ts": {
		"date": 1655556794000,
		"demo/StyleDialog": {}
	},
	"demo/TableContextmenu.ts": {
		"date": 1681590828000
	},
	"demo/TestComponent.ts": {
		"date": 1655843270000,
		"demo.TestComponent": {
			"$UIComponent": [
				{
					"fullPath": "common/TestComponent",
					"editableChildComponents": [
						"this",
						"me.button4"
					]
				}
			]
		}
	},
	"demo/Testcontextmenu.ts": {
		"date": 1655843288000,
		"demo.Testcontextmenu": {}
	},
	"demo/Testdatatable.ts": {
		"date": 1681590288000
	},
	"demo/Testdatatable1.ts": {
		"date": 1681590298000
	},
	"demo/Testdatatable2.ts": {
		"date": 1681590306000
	},
	"demo/Testdatatable3.ts": {
		"date": 1681590314000
	},
	"demo/TestImage.ts": {
		"date": 1633792454000
	},
	"demo/TestList.ts": {
		"date": 1635803026000
	},
	"demo/Testmenu.ts": {
		"date": 1655726456000,
		"demo.Testmenu": {}
	},
	"demo/TestProTable.ts": {
		"date": 1681563006000
	},
	"demo/Testtable.ts": {
		"date": 1681590322000
	},
	"demo/TestTree.ts": {
		"date": 1655843318000,
		"demo.TestTree": {}
	},
	"demo/TestUpload.ts": {
		"date": 1657656094000,
		"demo/TestUpload": {}
	},
	"demo/TreeContextmenu.ts": {
		"date": 1634384688000
	},
	"demo/TreeTable.ts": {
		"date": 1681590900000,
		"demo.TreeTable": {}
	},
	"demo/_test1.ts": {
		"date": 1670673960000
	},
	"demo/TestContent.ts": {
		"date": 1695418663423.5051
	}
}
 }
});