//this file is autogenerated don't modify
define("demo/registry",["require"], function(require) {
 return {
  default: {
	"demo/DBTest.ts": {
		"date": 1597411843712
	},
	"demo/Dialog.ts": {
		"date": 1613218544157,
		"demo/Dialog": {}
	},
	"demo/DialogKunde.ts": {
		"date": 1613218544158,
		"demo.DialogKunde": {}
	},
	"demo/DialogKunde2.ts": {
		"date": 1613218544157,
		"demo.DialogKunde2": {}
	},
	"demo/DK.ts": {
		"date": 1613218544161,
		"demo.DK": {}
	},
	"demo/EmptyDialog.ts": {
		"date": 1613218544157,
		"demo.EmptyDialog": {}
	},
	"demo/HalloPhillip.ts": {
		"date": 1613218544160,
		"demo.HalloPhillip": {}
	},
	"demo/KundeView.ts": {
		"date": 1613218544157,
		"demo.KundeView": {
			"$DBObjectView": [
				{
					"classname": "de.Kunde"
				}
			]
		}
	},
	"demo/MemoryTest.ts": {
		"date": 1613218609627
	},
	"demo/modul.ts": {
		"date": 1612818333557
	},
	"demo/ParentRightCheck.ts": {
		"date": 1613218819988
	},
	"demo/ReportKunde.ts": {
		"date": 1613218544157,
		"demo.ReportKunde": {}
	},
	"demo/ReportRechnung.ts": {
		"date": 1613218544157,
		"demo.ReportRechnung": {}
	},
	"demo/StyleDialog.ts": {
		"date": 1613218544157,
		"demo/StyleDialog": {}
	},
	"demo/TableContextmenu.ts": {
		"date": 1588526093408
	},
	"demo/TestComponent.ts": {
		"date": 1613218544158,
		"demo.TestComponent": {
			"$UIComponent": [
				{
					"fullPath": "common/TestComponent",
					"editableChildComponents": [
						"this",
						"me.button4"
					]
				}
			]
		}
	},
	"demo/Testcontextmenu.ts": {
		"date": 1613218544157,
		"demo.Testcontextmenu": {}
	},
	"demo/TestExtension.ts": {
		"date": 1588013367734
	},
	"demo/Testmenu.ts": {
		"date": 1613218544157,
		"demo.Testmenu": {}
	},
	"demo/TestTab.ts": {
		"date": 1613218544160,
		"de.KK3": {
			"$ActionProvider": [
				"3"
			]
		},
		"de.KK4": {
			"$ActionProvider": [
				"4"
			]
		}
	},
	"demo/TestTree.ts": {
		"date": 1613218544157,
		"demo.TestTree": {}
	},
	"demo/TestUpload.ts": {
		"date": 1613218544157,
		"demo/TestUpload": {}
	},
	"demo/TreeContextmenu.ts": {
		"date": 1612387959952
	},
	"demo/TreeTable.ts": {
		"date": 1613218544157,
		"demo.TreeTable": {}
	}
}
 }
});