//this file is autogenerated don't modify
define("demo/registry",["require"], function(require) {
 return {
  default: {
	"demo/DelTest.ts": {
		"date": 1681563014000
	},
	"demo/LargeReport.ts": {
		"date": 1634240084000
	},
	"demo/MemoryTest.ts": {
		"date": 1681590024000
	},
	"demo/modul.ts": {
		"date": 1612818334000
	},
	"demo/Report1.ts": {
		"date": 1699287691047.1409
	},
	"demo/ReportInvoice.ts": {
		"date": 1681590034000,
		"demo.ReportInvoice": {}
	},
	"demo/ReportInvoice2.ts": {
		"date": 1681590038000,
		"demo.ReportInvoice": {}
	},
	"demo/ReportStyle.ts": {
		"date": 1681590044000
	},
	"demo/StyleDialog.ts": {
		"date": 1655556794000,
		"demo/StyleDialog": {}
	},
	"demo/TableContextmenu.ts": {
		"date": 1697199411562.5796
	},
	"demo/TestComponent.ts": {
		"date": 1740651071484.972,
		"demo.TestComponent": {
			"$UIComponent": [
				{
					"fullPath": "common/TestComponent",
					"editableChildComponents": [
						"this",
						"me.button4"
					]
				}
			]
		}
	},
	"demo/TestContent.ts": {
		"date": 1695418663423.5051
	},
	"demo/Testcontextmenu.ts": {
		"date": 1740079362172.345,
		"demo.Testcontextmenu": {}
	},
	"demo/Testdatatable.ts": {
		"date": 1681590288000
	},
	"demo/Testdatatable1.ts": {
		"date": 1681590298000
	},
	"demo/Testdatatable2.ts": {
		"date": 1681590306000
	},
	"demo/Testdatatable3.ts": {
		"date": 1681590314000
	},
	"demo/TestImage.ts": {
		"date": 1633792454000
	},
	"demo/TestList.ts": {
		"date": 1635803026000
	},
	"demo/Testmenu.ts": {
		"date": 1655726456000,
		"demo.Testmenu": {}
	},
	"demo/TestProTable.ts": {
		"date": 1697201359946.1306
	},
	"demo/Testtable.ts": {
		"date": 1681590322000
	},
	"demo/TestTree.ts": {
		"date": 1655843318000,
		"demo.TestTree": {}
	},
	"demo/TestUpload.ts": {
		"date": 1698507857256.2214,
		"demo/TestUpload": {}
	},
	"demo/TreeContextmenu.ts": {
		"date": 1719756458964.0796
	},
	"demo/TreeTable.ts": {
		"date": 1697199554705.8606,
		"demo.TreeTable": {}
	},
	"demo/_test1.ts": {
		"date": 1670673960000
	},
	"demo/Dialog7.ts": {
		"date": 1740651060516.4475,
		"demo/M1": {
			"$UIComponent": [
				{
					"fullPath": "common/M1"
				}
			],
			"$Property": [
				{
					"name": "text",
					"type": "string"
				}
			]
		},
		"demo/Dialog7": {}
	},
	"demo/Dialog8.ts": {
		"date": 1740651364663.8745
	},
	"demo/TestStatebinder.ts": {
		"date": 1740069816818.0576
	},
	"demo/hallo.tsx": {
		"date": 1740575668495.1196
	},
	"demo/hallo2.tsx": {
		"date": 1720092336379.0627
	},
	"demo/hallo3.tsx": {
		"date": 1740490301824.4006
	},
	"demo/hallo4.tsx": {
		"date": 1740921953482.349
	},
	"demo/hallo5.tsx": {
		"date": 1740490330935.17
	},
	"demo/hallo6.tsx": {
		"date": 1740744395569.9814
	},
	"demo/TestJSX.tsx": {
		"date": 1719778647927.916
	},
	"demo/TestComputedState.tsx": {
		"date": 1740490457021.1514
	},
	"demo/ExistsIfTest.ts": {
		"date": 1740651376709.344
	},
	"demo/ExistsIfTest2.tsx": {
		"date": 1740490173291.3179
	},
	"demo/TestContextmenu2.tsx": {
		"date": 1740312744239.8494
	},
	"demo/Dialog1.ts": {
		"date": 1740595660483.8047,
		"demo/Dialog1": {}
	},
	"demo/Dialog2.tsx": {
		"date": 1740732548116.1436
	},
	"demo/Testreport.ts": {
		"date": 1740920946369.223
	}
}
 }
});