"use strict:";
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "hhh/remote/MyRemoteObject.ts": {
        "date": 1682795674570.1785,
        "hhh.remote.MyRemoteObject": {}
    }
};
//# sourceMappingURL=registry.js.map