//this file is autogenerated don't modify
define("jassijs_editor/registry", ["require"], function (require) {
    return {
        default: {
            "jassijs_editor/AcePanel.ts": {
                "date": 1720101244987.3042,
                "jassijs.ui.AcePanel": {}
            },
            "jassijs_editor/AcePanelSimple.ts": {
                "date": 1719757301492.3672,
                "jassijs.ui.AcePanelSimple": {}
            },
            "jassijs_editor/ChromeDebugger.ts": {
                "date": 1681488352000,
                "jassijs_editor.ChromeDebugger": {}
            },
            "jassijs_editor/CodeEditor.ts": {
                "date": 1721763750903.6765,
                "jassijs_editor.CodeEditorSettingsDescriptor": {
                    "$SettingsDescriptor": [],
                    "@members": {}
                },
                "jassijs_editor.CodeEditor": {
                    "@members": {}
                }
            },
            "jassijs_editor/CodeEditorInvisibleComponents.ts": {
                "date": 1719757407652.6265,
                "jassijs_editor.CodeEditorInvisibleComponents": {}
            },
            "jassijs_editor/CodePanel.ts": {
                "date": 1655661690000,
                "jassijs_editor.CodePanel": {}
            },
            "jassijs_editor/ComponentDesigner.ts": {
                "date": 1722610308085.8442,
                "jassijs_editor.ComponentDesigner": {}
            },
            "jassijs_editor/ComponentExplorer.ts": {
                "date": 1721763138779.0403,
                "jassijs_editor.ComponentExplorer": {}
            },
            "jassijs_editor/ComponentPalette.ts": {
                "date": 1721754620068.305,
                "jassijs_editor.ComponentPalette": {}
            },
            "jassijs_editor/ComponentSpy.ts": {
                "date": 1719755727631.165,
                "jassijs_editor.ui.ComponentSpy": {
                    "$ActionProvider": [
                        "jassijs.base.ActionNode"
                    ],
                    "@members": {
                        "dummy": {
                            "$Action": [
                                {
                                    "name": "Administration",
                                    "icon": "mdi mdi-account-cog-outline"
                                }
                            ]
                        },
                        "showDialog": {
                            "$Action": [
                                {
                                    "name": "Administration/Spy Components",
                                    "icon": "mdi mdi-police-badge"
                                }
                            ]
                        }
                    }
                }
            },
            "jassijs_editor/DatabaseDesigner.ts": {
                "date": 1698507857253.23,
                "jassijs_editor/DatabaseDesigner": {
                    "$ActionProvider": [
                        "jassijs.base.ActionNode"
                    ],
                    "@members": {
                        "showDialog": {
                            "$Action": [
                                {
                                    "name": "Administration/Database Designer",
                                    "icon": "mdi mdi-database-edit"
                                }
                            ]
                        }
                    }
                }
            },
            "jassijs_editor/Debugger.ts": {
                "date": 1656019586000,
                "jassijs_editor.Debugger": {}
            },
            "jassijs_editor/ErrorPanel.ts": {
                "date": 1720116488294.8394,
                "jassijs_editor.ui.ErrorPanel": {
                    "$ActionProvider": [
                        "jassijs.base.ActionNode"
                    ],
                    "@members": {
                        "showDialog": {
                            "$Action": [
                                {
                                    "name": "Administration/Errors",
                                    "icon": "mdi mdi-emoticon-confused-outline"
                                }
                            ]
                        }
                    }
                }
            },
            "jassijs_editor/ext/monaco.ts": {
                "date": 1720105252684.6934
            },
            "jassijs_editor/ext/monaco2.ts": {
                "date": 1720090850426.468
            },
            "jassijs_editor/ext/typescriptservices.ts": {
                "date": 1720556246507.595
            },
            "jassijs_editor/FileExplorer.ts": {
                "date": 1683575950000,
                "jassijs_editor.ui.FileActions": {
                    "$ActionProvider": [
                        "jassijs.remote.FileNode"
                    ],
                    "@members": {
                        "newFile": {
                            "$Action": [
                                {
                                    "name": "New/File",
                                    "icon": "mdi mdi-file",
                                    "isEnabled": "function"
                                }
                            ]
                        },
                        "download": {
                            "$Action": [
                                {
                                    "name": "Download",
                                    "isEnabled": "function"
                                }
                            ]
                        },
                        "newFolder": {
                            "$Action": [
                                {
                                    "name": "New/Folder",
                                    "isEnabled": "function"
                                }
                            ]
                        },
                        "newModule": {
                            "$Action": [
                                {
                                    "name": "New/Module",
                                    "isEnabled": "function"
                                }
                            ]
                        },
                        "dodelete": {
                            "$Action": [
                                {
                                    "name": "Delete"
                                }
                            ]
                        },
                        "mapLocalFolder": {
                            "$Action": [
                                {
                                    "name": "Map local folder",
                                    "isEnabled": "function"
                                }
                            ]
                        },
                        "closeLocalFolder": {
                            "$Action": [
                                {
                                    "name": "Close local folder",
                                    "isEnabled": "function"
                                }
                            ]
                        },
                        "rename": {
                            "$Action": [
                                {
                 