//this file is autogenerated don't modify
define("demoreports/registry",["require"], function(require) {
 return {
  default: {
	"demoreports/01-Simpledata.ts": {
		"date": 1655640800970
	},
	"demoreports/10-Foreach.ts": {
		"date": 1655407641261
	},
	"demoreports/11-Foreach.ts": {
		"date": 1656025255234
	},
	"demoreports/12-Foreach.ts": {
		"date": 1634336976000
	},
	"demoreports/21-Datatable.ts": {
		"date": 1655407847485
	},
	"demoreports/22-Datatable.ts": {
		"date": 1655407875091
	},
	"demoreports/23-Datatable.ts": {
		"date": 1656024793633
	},
	"demoreports/30-Format.ts": {
		"date": 1655407998923
	},
	"demoreports/Empty.ts": {
		"date": 1655408032703
	},
	"demoreports/Invoice.ts": {
		"date": 1655408066557
	},
	"demoreports/pdfmake-playground/Basics.ts": {
		"date": 1655408093593
	},
	"demoreports/pdfmake-playground/Columns.ts": {
		"date": 1655408107807
	},
	"demoreports/pdfmake-playground/Images.ts": {
		"date": 1655408119438
	},
	"demoreports/pdfmake-playground/Lists.ts": {
		"date": 1655408133565
	},
	"demoreports/pdfmake-playground/Margin.ts": {
		"date": 1655408161243
	},
	"demoreports/pdfmake-playground/Styles1.ts": {
		"date": 1655408172956
	},
	"demoreports/pdfmake-playground/Styles2.ts": {
		"date": 1655408180437
	},
	"demoreports/pdfmake-playground/Styles3.ts": {
		"date": 1655408187427
	},
	"demoreports/pdfmake-playground/Tables.ts": {
		"date": 1655408197639
	},
	"demoreports/modul.ts": {
		"date": 1655641244993
	}
}
 }
});