//this file is autogenerated don't modify
define("jassijs_reportdefinition/registry", ["require"], function (require) {
    return {
        default: {
            "jassijs_reportdefinition/modul.ts": {
                "date": 1655637506035
            },
            "jassijs_reportdefinition/pdfMake-interface.ts": {
                "date": 1655637557493
            },
            "jassijs_reportdefinition/ReportDesignGlobal.ts": {
                "date": 1655397712425
            }
        }
    };
});
//# sourceMappingURL=registry.js.map