//this file is autogenerated don't modify
define("a/registry",["require"], function(require) {
 return {
  default: {
	"a/Dialog.ts": {
		"date": 1613218544157,
		"$/Dialog": {}
	},
	"a/modul.ts": {
		"date": 1612818323489
	},
	"a/monaco.ts": {
		"date": 1613148104582
	},
	"a/rep.ts": {
		"date": 1613218544157
	},
	"a/testreport.ts": {
		"date": 1613218544157
	}
}
 }
});