//this file is autogenerated don't modify
define("jassijs/registry",["require"], function(require) {
 return {
  default: {
	"jassijs/base/ActionNode.ts": {
		"date": 1655556796000,
		"jassijs.base.ActionNode": {}
	},
	"jassijs/base/Actions.ts": {
		"date": 1681570168000,
		"jassijs.base.Actions": {}
	},
	"jassijs/base/CurrentSettings.ts": {
		"date": 1655740040000
	},
	"jassijs/base/Errors.ts": {
		"date": 1655726580000
	},
	"jassijs/base/Extensions.ts": {
		"date": 1655549184000
	},
	"jassijs/base/LoginDialog.ts": {
		"date": 1683051936000
	},
	"jassijs/base/PropertyEditorService.ts": {
		"date": 1657571268000,
		"jassijs.base.PropertyEditorService": {}
	},
	"jassijs/base/Router.ts": {
		"date": 1655556796000,
		"jassijs.base.Router": {}
	},
	"jassijs/base/Windows.ts": {
		"date": 1657655076000,
		"jassijs.base.Windows": {}
	},
	"jassijs/ext/goldenlayout.ts": {
		"date": 1657655070000
	},
	"jassijs/ext/jquerylib.ts": {
		"date": 1657655350000
	},
	"jassijs/ext/papaparse.ts": {
		"date": 1657656072000
	},
	"jassijs/ext/spectrum.ts": {
		"date": 1657656778000
	},
	"jassijs/ext/tabulator.ts": {
		"date": 1683657412000
	},
	"jassijs/ext/tinymce.ts": {
		"date": 1657658562000
	},
	"jassijs/modul.ts": {
		"date": 1683648574000
	},
	"jassijs/remote/Classes.ts": {
		"date": 1686759604000,
		"jassijs.remote.JassiError": {},
		"jassijs.remote.Classes": {}
	},
	"jassijs/remote/ClientError.ts": {
		"date": 1655556930000,
		"jassijs.remote.ClientError": {}
	},
	"jassijs/remote/Config.ts": {
		"date": 1686853238000
	},
	"jassijs/remote/Database.ts": {
		"date": 1655556796000,
		"jassijs.remote.Database": {}
	},
	"jassijs/remote/DatabaseTools.ts": {
		"date": 1681309882000,
		"jassijs.remote.DatabaseTools": {
			"@members": {
				"runSQL": {
					"ValidateFunctionParameter": []
				}
			}
		}
	},
	"jassijs/remote/DBArray.ts": {
		"date": 1655556796000,
		"jassijs.remote.DBArray": {}
	},
	"jassijs/remote/DBObject.ts": {
		"date": 1681317356000,
		"jassijs.remote.DBObject": {}
	},
	"jassijs/remote/DBObjectQuery.ts": {
		"date": 1623876714000
	},
	"jassijs/remote/Extensions.ts": {
		"date": 1626209336000
	},
	"jassijs/remote/FileNode.ts": {
		"date": 1655556796000,
		"jassijs.remote.FileNode": {}
	},
	"jassijs/remote/hallo.ts": {
		"date": 1622985410000
	},
	"jassijs/remote/Jassi.ts": {
		"date": 1695580332624.7742
	},
	"jassijs/remote/jassijsGlobal.ts": {
		"date": 1655549782000
	},
	"jassijs/remote/Modules.ts": {
		"date": 1682799476000
	},
	"jassijs/remote/ObjectTransaction.ts": {
		"date": 1622985414000
	},
	"jassijs/remote/Registry.ts": {
		"date": 1686762490000
	},
	"jassijs/remote/RemoteObject.ts": {
		"date": 1655556866000,
		"jassijs.remote.RemoteObject": {}
	},
	"jassijs/remote/RemoteProtocol.ts": {
		"date": 1655556796000,
		"jassijs.remote.RemoteProtocol": {}
	},
	"jassijs/remote/security/Group.ts": {
		"date": 1682888736000,
		"jassijs.security.Group": {
			"$DBObject": [
				{
					"name": "jassijs_group"
				}
			],
			"@members": {
				"id": {
					"ValidateIsInt": [
						{
							"optional": true
						}
					],
					"PrimaryColumn": []
				},
				"name": {
					"ValidateIsString": [],
					"Column": []
				},
				"parentRights": {
					"ValidateIsArray": [
						{
							"optional": true,
							"type": "function"
						}
					],
					"JoinTable": [],
					"ManyToMany": [
						"function",
						"function"
					]
				},
				"rights": {
					"ValidateIsArray": [
						{
							"optional": true,
							"type": "function"
						}
					],
					"JoinTable": [],
					"ManyToMany": [
						"function",
						"function"
					]
				},
				"users": {
					"ValidateIsArray": [
						{
							"optional": true,
							"type": "function"
						}
					],
					"ManyToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"jassijs/remote/security/ParentRight.ts": {
		"date": 1681581398000,
		"jassijs.security.ParentRight": {
			"$DBObject": [
				{
					"name": "jassijs_parentright"
				}
			],
			"@members": {
				"id": {
					"ValidateIsInt": [
						{
							"optional": true
						}
					],
					"PrimaryGeneratedColumn": []
				},
				"name": {
					"ValidateIsString": [],
					"Column": []
				},
				"classname": {
					"ValidateIsString": [],
					"Column": []
				},
				"i1": {
					"ValidateIsNumber": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"i2": {
					"ValidateIsNumber": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"s1": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"s2": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"groups": {
					"ValidateIsArray": [
						{
							"optional": true,
							"type": "function"
						}
					],
					"ManyToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"jassijs/remote/security/Right.ts": {
		"date": 1681322768000,
		"jassijs.security.Right": {
			"$DBObject": [
				{
					"name": "jassijs_right"
				}
			],
			"@members": {
				"id": {
					"ValidateIsInt": [
						{
							"optional": true
						}
					],
					"PrimaryColumn": []
				},
				"name": {
					"ValidateIsString": [],
					"Column": []
				},
				"groups": {
					"ValidateIsArray": [
						{
							"optional": true,
							"type": "function"
						}
					],
					"ManyToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"jassijs/remote/security/Rights.ts": {
		"date": 1655556796000,
		"jassijs.security.Rights": {}
	},
	"jassijs/remote/security/Setting.ts": {
		"date": 1681316436000,
		"jassijs.security.Setting": {
			"$DBObject": [
				{
					"name": "jassijs_setting"
				}
			],
			"@members": {
				"id": {
					"ValidateIsInt": [
						{
							"optional": true
						}
					],
					"PrimaryColumn": []
				},
				"data": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"jassijs/remote/security/User.ts": {
		"date": 1681329604000,
		"jassijs.security.User": {
			"$DBObject": [
				{
					"name": "jassijs_user"
				}
			],
			"@members": {
				"id": {
					"ValidateIsNumber": [
						{
							"optional": true
						}
					],
					"PrimaryGeneratedColumn": []
				},
				"email": {
					"ValidateIsString": [],
					"Column": []
				},
				"password": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"select": false
						}
					]
				},
				"groups": {
					"ValidateIsArray": [
						{
							"optional": true,
							"type": "function"
						}
					],
					"JoinTable": [],
					"ManyToMany": [
						"function",
						"function"
					]
				},
				"isAdmin": {
					"ValidateIsBoolean": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"jassijs/remote/Server.ts": {
		"date": 1695399507170.7808,
		"jassijs.remote.Server": {
			"@members": {
				"dir": {
					"ValidateFunctionParameter": []
				},
				"zip": {
					"ValidateFunctionParameter": []
				},
				"loadFiles": {
					"ValidateFunctionParameter": []
				},
				"loadFile": {
					"ValidateFunctionParameter": []
				},
				"saveFiles": {
					"ValidateFunctionParameter": []
				},
				"saveFile": {
					"ValidateFunctionParameter": []
				},
				"testServersideFile": {
					"ValidateFunctionParameter": []
				},
				"removeServerModul": {
					"ValidateFunctionParameter": []
				},
				"delete": {
					"ValidateFunctionParameter": []
				},
				"rename": {
					"ValidateFunctionParameter": []
				},
				"createFile": {
					"ValidateFunctionParameter": []
				},
				"createFolder": {
					"ValidateFunctionParameter": []
				},
				"createModule": {
					"ValidateFunctionParameter": []
				}
			}
		}
	},
	"jassijs/remote/Serverservice.ts": {
		"date": 1682715264000
	},
	"jassijs/remote/Settings.ts": {
		"date": 1681315776000,
		"jassijs.remote.Settings": {
			"@members": {
				"remove": {
					"ValidateFunctionParameter": []
				},
				"save": {
					"ValidateFunctionParameter": []
				},
				"saveAll": {
					"ValidateFunctionParameter": []
				}
			}
		}
	},
	"jassijs/remote/Test.ts": {
		"date": 1655556930000,
		"jassijs.remote.Test": {}
	},
	"jassijs/remote/Transaction.ts": {
		"date": 1655556866000,
		"jassijs.remote.Transaction": {}
	},
	"jassijs/remote/Validator.ts": {
		"date": 1681322648000
	},
	"jassijs/security/GroupView.ts": {
		"date": 1681328192000,
		"jassijs/security/GroupView": {
			"$DBObjectView": [
				{
					"classname": "jassijs.security.Group",
					"icon": "mdi mdi-account-group",
					"actionname": "Administration/Security/Groups"
				}
			],
			"@members": {}
		}
	},
	"jassijs/security/UserView.ts": {
		"date": 1681330006000,
		"jassijs/security/UserView": {
			"$DBObjectView": [
				{
					"classname": "jassijs.security.User",
					"actionname": "Administration/Security/Users",
					"icon": "mdi mdi-account-key-outline",
					"queryname": "findWithRelations"
				}
			],
			"@members": {}
		}
	},
	"jassijs/server/Compile.ts": {
		"date": 1684400488000
	},
	"jassijs/server/DatabaseSchema.ts": {
		"date": 1682241710000
	},
	"jassijs/server/DBManager.ts": {
		"date": 1682710552000,
		"jassijs/server/DBManager": {
			"$Serverservice": [
				{
					"name": "db",
					"getInstance": "function"
				}
			]
		}
	},
	"jassijs/server/DBManagerExt.ts": {
		"date": 1683399518000
	},
	"jassijs/server/DoRemoteProtocol.ts": {
		"date": 1686853328000
	},
	"jassijs/server/ext/EmpyDeclaration.ts": {
		"date": 1682275348000
	},
	"jassijs/server/ext/jszip.ts": {
		"date": 1657714030000
	},
	"jassijs/server/Filesystem.ts": {
		"date": 1684401442000,
		"jassijs.server.Filesystem": {
			"$Serverservice": [
				{
					"name": "filesystem",
					"getInstance": "function"
				}
			]
		}
	},
	"jassijs/server/FS.ts": {
		"date": 1684358274000
	},
	"jassijs/server/Indexer.ts": {
		"date": 1684515212000
	},
	"jassijs/server/Installserver.ts": {
		"date": 1682930464000
	},
	"jassijs/server/LocalFS.ts": {
		"date": 1684358616000
	},
	"jassijs/server/LocalProtocol.ts": {
		"date": 1686757420000
	},
	"jassijs/server/NativeAdapter.ts": {
		"date": 1686927798000
	},
	"jassijs/server/RegistryIndexer.ts": {
		"date": 1682799792000
	},
	"jassijs/server/Testuser.ts": {
		"date": 1655556794000,
		"Testuser": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"firstname": {
					"Column": []
				},
				"lastname": {
					"Column": []
				}
			}
		}
	},
	"jassijs/server/TypeORMListener.ts": {
		"date": 1682885926000,
		"jassijs.server.TypeORMListener": {
			"EventSubscriber": []
		}
	},
	"jassijs/ui/ActionNodeMenu.ts": {
		"date": 1655556796000,
		"jassijs/ui/ActionNodeMenu": {}
	},
	"jassijs/ui/BoxPanel.ts": {
		"date": 1657715388000,
		"jassijs.ui.BoxPanel": {
			"$UIComponent": [
				{
					"fullPath": "common/BoxPanel",
					"icon": "mdi mdi-view-sequential-outline",
					"editableChildComponents": [
						"this"
					]
				}
			],
			"$Property": [
				{
					"name": "isAbsolute",
					"hide": true,
					"type": "boolean"
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/Button.ts": {
		"date": 1657569478000,
		"jassijs.ui.Button": {
			"$UIComponent": [
				{
					"fullPath": "common/Button",
					"icon": "mdi mdi-gesture-tap-button",
					"initialize": {
						"text": "button"
					}
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/Calendar.ts": {
		"date": 1656016860000,
		"jassijs.ui.Calendar": {
			"$UIComponent": [
				{
					"fullPath": "common/Calendar",
					"icon": "mdi mdi-calendar-month"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "string"
				}
			]
		}
	},
	"jassijs/ui/Checkbox.ts": {
		"date": 1655587866000,
		"jassijs.ui.Checkbox": {
			"$UIComponent": [
				{
					"fullPath": "common/Ceckbox",
					"icon": "mdi mdi-checkbox-marked-outline"
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/Component.ts": {
		"date": 1695588862649.9673,
		"jassijs.ui.Component": {
			"@members": {}
		}
	},
	"jassijs/ui/ComponentDescriptor.ts": {
		"date": 1655556866000,
		"jassijs.ui.ComponentDescriptor": {}
	},
	"jassijs/ui/Container.ts": {
		"date": 1695590706160.0225,
		"jassijs.ui.Container": {}
	},
	"jassijs/ui/ContextMenu.ts": {
		"date": 1684403126000,
		"jassijs.ui.ContextMenu": {
			"$UIComponent": [
				{
					"fullPath": "common/ContextMenu",
					"icon": "mdi mdi-dots-vertical",
					"editableChildComponents": [
						"menu"
					]
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/converters/DateTimeConverter.ts": {
		"date": 1681559014000,
		"jassijs.ui.converters.DateTimeConverterProperies": {
			"@members": {}
		},
		"jassijs.ui.converters.DateTimeConverter": {
			"$Converter": [
				{
					"name": "datetime"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassijs.ui.converters.DateTimeConverterProperties"
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/converters/DefaultConverter.ts": {
		"date": 1657922212000,
		"jassijs.ui.converters.DefaultConverterProperties": {
			"@members": {}
		},
		"jassijs.ui.converters.DefaultConverter": {
			"$Converter": [
				{
					"name": "custom"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassijs.ui.converters.DefaultConverterProperties"
				}
			]
		}
	},
	"jassijs/ui/converters/NumberConverter.ts": {
		"date": 1658334942000,
		"jassijs.ui.converters.NumberConverterProperies": {
			"@members": {}
		},
		"jassijs.ui.converters.NumberConverter": {
			"$Converter": [
				{
					"name": "number"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassijs.ui.converters.NumberConverterProperies"
				}
			]
		}
	},
	"jassijs/ui/converters/StringConverter.ts": {
		"date": 1657129814000,
		"jassijs.ui.converters.StringConverterProperies": {
			"@members": {}
		},
		"jassijs.ui.converters.StringConverter": {
			"$Converter": [
				{
					"name": "string"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassijs.ui.converters.StringConverterProperies"
				}
			]
		}
	},
	"jassijs/ui/CSSProperties.ts": {
		"date": 1656016872000,
		"jassijs.ui.CSSProperties": {
			"@members": {}
		}
	},
	"jassijs/ui/Databinder.ts": {
		"date": 1681560838000,
		"jassijs.ui.Databinder": {
			"$UIComponent": [
				{
					"fullPath": "common/Databinder",
					"icon": "mdi mdi-connection"
				}
			]
		}
	},
	"jassijs/ui/DataComponent.ts": {
		"date": 1695242062430.286,
		"jassijs.ui.DataComponent": {
			"@members": {}
		}
	},
	"jassijs/ui/DBObjectDialog.ts": {
		"date": 1681562926000,
		"jassijs.ui.DBObjectDialog": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"createActions": {
					"$Actions": []
				}
			}
		}
	},
	"jassijs/ui/DBObjectExplorer.ts": {
		"date": 1655556796000,
		"jassijs.ui.DBObjectNode": {},
		"jassijs.ui.DBFileActions": {
			"$ActionProvider": [
				"jassijs.remote.FileNode"
			],
			"@members": {
				"ViewData": {
					"$Action": [
						{
							"name": "View Data",
							"isEnabled": "function"
						}
					]
				}
			}
		},
		"jassijs.ui.DBObjectActions": {
			"$ActionProvider": [
				"jassijs.ui.DBObjectNode"
			],
			"@members": {
				"ViewData": {
					"$Action": [
						{
							"name": "View Data"
						}
					]
				},
				"OpenCode": {
					"$Action": [
						{
							"name": "Open Code"
						}
					]
				}
			}
		},
		"jassijs.ui.DBObjectExplorer": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"dummy": {
					"$Action": [
						{
							"name": "Windows",
							"icon": "mdi mdi-iframe-array-outline"
						}
					]
				},
				"dummy2": {
					"$Action": [
						{
							"name": "Windows/Development",
							"icon": "mdi mdi-dev-to"
						}
					]
				},
				"show": {
					"$Action": [
						{
							"name": "Windows/Development/DBObjects",
							"icon": "mdi mdi-database-search"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/DBObjectView.ts": {
		"date": 1681559040000,
		"jassijs/ui/DBObjectView": {
			"$UIComponent": [
				{
					"editableChildComponents": [
						"this",
						"me.main",
						"me.toolbar",
						"me.save",
						"me.remove",
						"me.refresh",
						"me.databinder"
					]
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/DesignDummy.ts": {
		"date": 1655755336000,
		"jassijs.ui.DesignDummy": {}
	},
	"jassijs/ui/DockingContainer.ts": {
		"date": 1681513934000,
		"jassijs.ui.DockingContainer": {}
	},
	"jassijs/ui/HTMLEditorPanel.ts": {
		"date": 1655641682000,
		"jassijs.ui.HTMLEditorPanel": {}
	},
	"jassijs/ui/HTMLPanel.ts": {
		"date": 1657572162000,
		"jassijs.ui.HTMLPanel": {
			"$UIComponent": [
				{
					"fullPath": "common/HTMLPanel",
					"icon": "mdi mdi-cloud-tags"
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/Image.ts": {
		"date": 1655672424000,
		"jassijs.ui.Image": {
			"$UIComponent": [
				{
					"fullPath": "default/Image",
					"icon": "mdi mdi-file-image"
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/InvisibleComponent.ts": {
		"date": 1655843346000,
		"jassijs.ui.InvisibleComponent": {
			"$Property": [
				{
					"hideBaseClassProperties": true
				}
			]
		}
	},
	"jassijs/ui/Menu.ts": {
		"date": 1655753280000,
		"jassijs.ui.Menu": {
			"$UIComponent": [
				{
					"fullPath": "common/Menu",
					"icon": "mdi mdi-menu",
					"initialize": {
						"text": "menu"
					}
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/MenuItem.ts": {
		"date": 1656016938000,
		"jassijs.ui.MenuItem": {
			"$UIComponent": [
				{
					"fullPath": "common/MenuItem",
					"icon": "mdi mdi-menu-open",
					"initialize": {
						"text": "menu"
					},
					"editableChildComponents": [
						"items"
					]
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/Notify.ts": {
		"date": 1655585212000
	},
	"jassijs/ui/ObjectChooser.ts": {
		"date": 1681553938000,
		"jassijs.ui.ObjectChooser": {
			"$UIComponent": [
				{
					"fullPath": "common/ObjectChooser",
					"icon": "mdi mdi-glasses"
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/OptionDialog.ts": {
		"date": 1656067784000,
		"jassijs.ui.OptionDialog": {
			"@members": {}
		},
		"jassijs.ui.OptionDialogTestProp": {
			"@members": {}
		}
	},
	"jassijs/ui/Panel.ts": {
		"date": 1683645540000,
		"jassijs.ui.PanelCreateProperties": {
			"@members": {}
		},
		"jassijs.ui.Panel": {
			"$UIComponent": [
				{
					"fullPath": "common/Panel",
					"icon": "mdi mdi-checkbox-blank-outline",
					"editableChildComponents": [
						"this"
					]
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassijs.ui.PanelCreateProperties"
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/Property.ts": {
		"date": 1658347724000,
		"jassijs.ui.Property": {}
	},
	"jassijs/ui/PropertyEditor.ts": {
		"date": 1695319969067.791,
		"jassijs.ui.PropertyEditor": {},
		"jassijs.ui.PropertyEditorTestSubProperties": {
			"@members": {}
		},
		"jassijs.ui.PropertyEditorTestProperties": {
			"@members": {}
		}
	},
	"jassijs/ui/PropertyEditors/BooleanEditor.ts": {
		"date": 1655556866000,
		"jassijs.ui.PropertyEditors.BooleanEditor": {
			"$PropertyEditor": [
				[
					"boolean"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/ClassSelectorEditor.ts": {
		"date": 1657571442000,
		"jassijs.ui.PropertyEditors.ClassSelectorEditor": {
			"$PropertyEditor": [
				[
					"classselector"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/ColorEditor.ts": {
		"date": 1656017118000,
		"jassijs.ui.PropertyEditors.ColorEditor": {
			"$PropertyEditor": [
				[
					"color"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/ComponentSelectorEditor.ts": {
		"date": 1655556796000,
		"jassijs.ui.PropertyEditors.ComponentSelectorEditor": {
			"$PropertyEditor": [
				[
					"componentselector"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/DatabinderEditor.ts": {
		"date": 1656506936000,
		"jassijs.ui.PropertyEditors.DatabinderEditor": {
			"$PropertyEditor": [
				[
					"databinder"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/DBObjectEditor.ts": {
		"date": 1655556866000,
		"jassijs.ui.PropertyEditors.DBObjectEditor": {
			"$PropertyEditor": [
				[
					"dbobject"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/DefaultEditor.ts": {
		"date": 1655556796000,
		"jassijs.ui.PropertyEditors.DefaultEditor": {
			"$PropertyEditor": [
				[
					"string",
					"number",
					"number[]",
					"boolean[]"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/Editor.ts": {
		"date": 1655556796000,
		"jassijs.ui.PropertyEditors.Editor": {}
	},
	"jassijs/ui/PropertyEditors/FontEditor.ts": {
		"date": 1655556866000,
		"jassijs.ui.PropertyEditors.FontEditor": {
			"$PropertyEditor": [
				[
					"font"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/FunctionEditor.ts": {
		"date": 1655556866000,
		"jassijs.ui.PropertyEditors.FunctionEditor": {
			"$PropertyEditor": [
				[
					"function"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/HTMLEditor.ts": {
		"date": 1655556866000,
		"jassijs.ui.PropertyEditors.HTMLEditor": {
			"$PropertyEditor": [
				[
					"html"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/ImageEditor.ts": {
		"date": 1656189492000,
		"jassijs.ui.PropertyEditors.ImageEditor": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"$PropertyEditor": [
				[
					"image"
				]
			],
			"@members": {
				"dummy": {
					"$Action": [
						{
							"name": "Tools",
							"icon": "mdi mdi-tools"
						}
					]
				},
				"show": {
					"$Action": [
						{
							"name": "Tools/Icons",
							"icon": "mdi mdi-image-area"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/PropertyEditors/JsonArrayEditor.ts": {
		"date": 1656960820000,
		"jassijs.ui.PropertyEditors.JsonArrayEditor": {
			"$PropertyEditor": [
				[
					"jsonarray"
				]
			]
		},
		"jassijs.ui.JsonArrayEditor.TestProperties": {
			"@members": {}
		},
		"jassijs.ui.JsonArrayEditor.TestProperties2": {
			"@members": {}
		}
	},
	"jassijs/ui/PropertyEditors/JsonEditor.ts": {
		"date": 1658349512000,
		"jassijs.ui.PropertyEditors.JsonEditor": {
			"$PropertyEditor": [
				[
					"json"
				]
			]
		},
		"jassijs.ui.PropertyEditorTestProperties2": {
			"@members": {}
		},
		"jassijs.ui.PropertyEditorTestProperties": {
			"@members": {}
		}
	},
	"jassijs/ui/PropertyEditors/NameEditor.ts": {
		"date": 1655556796000,
		"jassijs.ui.PropertyEditors.NameEditor": {
			"$PropertyEditor": [
				[
					"*name*"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/TableColumnImport.ts": {
		"date": 1657049000000,
		"jassijs/ui/PropertyEditors/TableColumnImport": {}
	},
	"jassijs/ui/Repeater.ts": {
		"date": 1681564940000,
		"jassijs.ui.RepeaterDesignPanel": {
			"$UIComponent": [
				{
					"editableChildComponents": [
						"databinder"
					]
				}
			]
		},
		"jassijs.ui.Repeater": {
			"$UIComponent": [
				{
					"fullPath": "common/Repeater",
					"icon": "mdi mdi-locker-multiple",
					"editableChildComponents": [
						"this",
						"design"
					]
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/Select.ts": {
		"date": 1655847540000,
		"jassijs.ui.SelectCreateProperties": {
			"@members": {}
		},
		"jassijs.ui.Select": {
			"$UIComponent": [
				{
					"fullPath": "common/Select",
					"icon": "mdi mdi-form-dropdown"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassijs.ui.SelectCreateProperties"
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/SettingsDialog.ts": {
		"date": 1681570600000,
		"jassijs.ui.SettingsObject": {},
		"jassijs.ui.SettingsDialog": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"show": {
					"$Action": [
						{
							"name": "Settings",
							"icon": "mdi mdi-settings-helper"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/Style.ts": {
		"date": 1655847592000,
		"jassijs.ui.Style": {
			"$UIComponent": [
				{
					"fullPath": "common/Style",
					"icon": "mdi mdi-virus"
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/Table.ts": {
		"date": 1695241273271.6812,
		"jassijs.ui.TableEditorProperties": {
			"@members": {}
		},
		"jassijs.ui.Table": {
			"$UIComponent": [
				{
					"fullPath": "common/Table",
					"icon": "mdi mdi-grid"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassijs.ui.TableEditorProperties"
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/Textarea.ts": {
		"date": 1655757394000,
		"jassijs.ui.Textarea": {
			"$UIComponent": [
				{
					"fullPath": "common/Textarea",
					"icon": "mdi mdi-text-box-outline"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "string"
				}
			]
		}
	},
	"jassijs/ui/Textbox.ts": {
		"date": 1695237619068.785,
		"jassijs.ui.Textbox": {
			"$UIComponent": [
				{
					"fullPath": "common/Textbox",
					"icon": "mdi mdi-form-textbox"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "string"
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/Tree.ts": {
		"date": 1656079002000,
		"jassijs.ui.TreeEditorPropertiesMulti": {
			"@members": {}
		},
		"jassijs.ui.TreeEditorProperties": {
			"@members": {}
		},
		"jassijs.ui.Tree": {
			"$UIComponent": [
				{
					"fullPath": "common/Tree",
					"icon": "mdi mdi-file-tree"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassijs.ui.TreeEditorProperties"
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/Upload.ts": {
		"date": 1655847946000,
		"jassijs.ui.Upload": {
			"$UIComponent": [
				{
					"fullPath": "common/Upload",
					"icon": "mdi mdi-cloud-upload-outline"
				}
			],
			"@members": {}
		}
	},
	"jassijs/ui/VariablePanel.ts": {
		"date": 1656066842000,
		"jassijs.ui.VariablePanel": {}
	},
	"jassijs/util/Cookies.ts": {
		"date": 1682364420000
	},
	"jassijs/util/CSVImport.ts": {
		"date": 1681562976000,
		"jassijs.util.CSVImport": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"showDialog": {
					"$Action": [
						{
							"name": "Administration/Database CSV-Import",
							"icon": "mdi mdi-database-import"
						}
					]
				}
			}
		}
	},
	"jassijs/util/DatabaseSchema.ts": {
		"date": 1622984214000
	},
	"jassijs/util/Numberformatter.ts": {
		"date": 1657046808000,
		"jassijs.util.Numberformatter": {}
	},
	"jassijs/util/Reloader.ts": {
		"date": 1684441726000,
		"jassijs.util.Reloader": {}
	},
	"jassijs/util/Runlater.ts": {
		"date": 1655556796000,
		"jassi.util.Runlater": {}
	},
	"jassijs/util/Tools.ts": {
		"date": 1657655420000,
		"jassijs.util.Tools": {}
	},
	"jassijs/server/Reloader.ts": {
		"date": 1686927696000,
		"jassijs.server.Reloader": {}
	}
}
 }
});