//this file is autogenerated dont modify
define("a/registry", ["require"], function (require) {
    return {
        default: {
            "a/Dialog.ts": {
                "date": 1611520651246,
                "$/Dialog": {}
            },
            "a/modul.ts": {
                "date": 1612818323489
            },
            "a/monaco.ts": {
                "date": 1611772398569
            },
            "a/rep.ts": {
                "date": 1611936363489
            },
            "a/testreport.ts": {
                "date": 1611936363489
            }
        }
    };
});
//# sourceMappingURL=registry.js.map