//this file is autogenerated don't modify
define("a/registry", ["require"], function (require) {
    return {
        default: {
            "a/Dialog.ts": {
                "date": 1622220020019,
                "$/Dialog": {}
            },
            "a/modul.ts": {
                "date": 1612818323489
            },
            "a/monaco.ts": {
                "date": 1613148104582
            },
            "a/rep.ts": {
                "date": 1613330812614
            },
            "a/testreport.ts": {
                "date": 1613330812614
            }
        }
    };
});
//# sourceMappingURL=registry.js.map