//this file is autogenerated don't modify
define("tests/registry", ["require"], function (require) {
    return {
        default: {
            "tests/DBTests.ts": {
                "date": 1624296652000
            },
            "tests/FileActionsTests.ts": {
                "date": 1624296374000
            },
            "tests/remote/T.ts": {
                "date": 1655556792356,
                "tests.remote.T": {}
            },
            "tests/remote/TestCustomer.ts": {
                "date": 1656073034029,
                "tests.TestCustomer": {
                    "$ParentRights": [
                        [
                            {
                                "name": "TestCustomers",
                                "sqlToCheck": "me.id>=:i1 and me.id<=:i2",
                                "description": {
                                    "text": "TestCustomer",
                                    "i1": "from",
                                    "i2": "to"
                                }
                            }
                        ]
                    ],
                    "$DBObject": [],
                    "@members": {
                        "id": {
                            "PrimaryColumn": []
                        },
                        "name": {
                            "Column": [
                                {
                                    "nullable": true
                                }
                            ]
                        },
                        "orders": {
                            "OneToMany": [
                                "function",
                                "function"
                            ]
                        }
                    }
                }
            },
            "tests/remote/TestOrder.ts": {
                "date": 1656073023813,
                "tests.TestOrder": {
                    "$DBObject": [],
                    "@members": {
                        "id": {
                            "PrimaryColumn": []
                        },
                        "customer": {
                            "$CheckParentRight": [],
                            "ManyToOne": [
                                "function"
                            ]
                        },
                        "details": {
                            "OneToMany": [
                                "function",
                                "function"
                            ]
                        }
                    }
                }
            },
            "tests/remote/TestOrderDetails.ts": {
                "date": 1656073236783,
                "tests.TestOrderDetails": {
                    "$DBObject": [],
                    "@members": {
                        "id": {
                            "PrimaryColumn": []
                        },
                        "Order": {
                            "$CheckParentRight": [],
                            "ManyToOne": [
                                "function",
                                "function"
                            ]
                        }
                    }
                }
            },
            "tests/remote/TestServerfile.ts": {
                "date": 1624999038000
            },
            "tests/RemoteModulTests.ts": {
                "date": 1655556792356
            },
            "tests/ServerTests.ts": {
                "date": 1656077953224
            },
            "tests/TestDialog.ts": {
                "date": 1656079687883,
                "tests/TestDialog": {}
            },
            "tests/TestReport.ts": {
                "date": 1623864074000
            }
        }
    };
});
//# sourceMappingURL=registry.js.map