//this file is autogenerated dont modify
define("jassi_editor/registry",["require"], function(require) {
 return {
  default: {
	"jassi_editor/AcePanel.ts": {
		"date": 1613148379164,
		"jassi.ui.AcePanel": {}
	},
	"jassi_editor/ChromeDebugger.ts": {
		"date": 1613154792948,
		"jassi_editor.ChromeDebugger": {}
	},
	"jassi_editor/CodeEditor.ts": {
		"date": 1613154837204,
		"jassi_editor.CodeEditor": {}
	},
	"jassi_editor/CodeEditorInvisibleComponents.ts": {
		"date": 1613154664883,
		"jassi_editor.CodeEditorInvisibleComponents": {}
	},
	"jassi_editor/CodePanel.ts": {
		"date": 1613154800103,
		"jassi_editor.CodePanel": {}
	},
	"jassi_editor/ComponentDesigner.ts": {
		"date": 1613148568348,
		"jassi_editor.ComponentDesigner": {}
	},
	"jassi_editor/ComponentExplorer.ts": {
		"date": 1613165831350,
		"jassi_editor.ComponentExplorer": {}
	},
	"jassi_editor/ComponentPalette.ts": {
		"date": 1613148318012,
		"jassi_editor.ComponentPalette": {}
	},
	"jassi_editor/Debugger.ts": {
		"date": 1613154693814,
		"jassi_editor.Debugger": {}
	},
	"jassi_editor/modul.ts": {
		"date": 1613157707411
	},
	"jassi_editor/MonacoPanel.ts": {
		"date": 1613154843011,
		"jassi_editor.MonacoPanel": {}
	},
	"jassi_editor/util/DragAndDropper.ts": {
		"date": 1613148527827,
		"jassi_editor.util.DragAndDropper": {}
	},
	"jassi_editor/util/monaco.ts": {
		"date": 1613148168781
	},
	"jassi_editor/util/Parser.ts": {
		"date": 1613154740484,
		"jassi_editor.base.Parser": {}
	},
	"jassi_editor/util/Resizer.ts": {
		"date": 1613148509602,
		"jassi_editor.util.Resizer": {}
	},
	"jassi_editor/util/TSSourceMap.ts": {
		"date": 1613147374359,
		"jassi_editor.util.TSSourceMap": {}
	},
	"jassi_editor/util/Typescript.ts": {
		"date": 1613164778342,
		"jassi_editor.util.Typescript": {}
	}
}
 }
});