//this file is autogenerated don't modify
define("jassi_editor/registry",["require"], function(require) {
 return {
  default: {
	"jassi_editor/AcePanel.ts": {
		"date": 1613218566582,
		"jassi.ui.AcePanel": {}
	},
	"jassi_editor/ChromeDebugger.ts": {
		"date": 1613592968297,
		"jassi_editor.ChromeDebugger": {}
	},
	"jassi_editor/CodeEditor.ts": {
		"date": 1613572265906,
		"jassi_editor.CodeEditor": {}
	},
	"jassi_editor/CodeEditorInvisibleComponents.ts": {
		"date": 1613218566583,
		"jassi_editor.CodeEditorInvisibleComponents": {}
	},
	"jassi_editor/CodePanel.ts": {
		"date": 1613218544158,
		"jassi_editor.CodePanel": {}
	},
	"jassi_editor/ComponentDesigner.ts": {
		"date": 1613218544160,
		"jassi_editor.ComponentDesigner": {}
	},
	"jassi_editor/ComponentExplorer.ts": {
		"date": 1613218544158,
		"jassi_editor.ComponentExplorer": {}
	},
	"jassi_editor/ComponentPalette.ts": {
		"date": 1614028739796,
		"jassi_editor.ComponentPalette": {}
	},
	"jassi_editor/Debugger.ts": {
		"date": 1613218544158,
		"jassi_editor.Debugger": {}
	},
	"jassi_editor/modul.ts": {
		"date": 1614109063764
	},
	"jassi_editor/MonacoPanel.ts": {
		"date": 1613573828092,
		"jassi_editor.MonacoPanel": {}
	},
	"jassi_editor/StartEditor.ts": {
		"date": 1613341619526
	},
	"jassi_editor/util/DragAndDropper.ts": {
		"date": 1613218544158,
		"jassi_editor.util.DragAndDropper": {}
	},
	"jassi_editor/util/monaco.ts": {
		"date": 1613148168781
	},
	"jassi_editor/util/Parser.ts": {
		"date": 1613779964792,
		"jassi_editor.base.Parser": {}
	},
	"jassi_editor/util/Resizer.ts": {
		"date": 1613218544158,
		"jassi_editor.util.Resizer": {}
	},
	"jassi_editor/util/TSSourceMap.ts": {
		"date": 1613550062397,
		"jassi_editor.util.TSSourceMap": {}
	},
	"jassi_editor/util/Typescript.ts": {
		"date": 1613218610071,
		"jassi_editor.util.Typescript": {}
	}
}
 }
});