"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"tg/remote/MyRemoteObject.ts": {
		"date": 1622999304732,
		"tg/remote/MyRemoteObject": {}
	},
	"tg/remote/Person.ts": {
		"date": 1622999405219,
		"tg.Person": {
			"$DBObject": []
		}
	}
}