"use strict:";
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "tg/remote/MyRemoteObject.ts": {
        "date": 1622922501315,
        "tg/remote/MyRemoteObject": {}
    }
};
//# sourceMappingURL=registry.js.map