"use strict:";
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "jassi/base/ext/registry.ts": {
        "date": 1575151356681
    },
    "jassi/remote/Classes.ts": {
        "date": 1613248818825,
        "jassi.remote.Classes": {}
    },
    "jassi/remote/Database.ts": {
        "date": 1613248958209,
        "jassi.remote.Database": {}
    },
    "jassi/remote/DBArray.ts": {
        "date": 1613233278151,
        "jassi.remote.DBArray": {}
    },
    "jassi/remote/DBObject.ts": {
        "date": 1613219076133,
        "jassi.remote.DBObject": {}
    },
    "jassi/remote/DBObjectQuery.ts": {
        "date": 1613218566583
    },
    "jassi/remote/Extensions.ts": {
        "date": 1613218569575
    },
    "jassi/remote/FileNode.ts": {
        "date": 1613219099164,
        "jassi.remote.FileNode": {}
    },
    "jassi/remote/hallo.ts": {
        "date": 1613218515810
    },
    "jassi/remote/Jassi.ts": {
        "date": 1613219112108,
        "jassi.remote.Jassi": {}
    },
    "jassi/remote/Registry.ts": {
        "date": 1613228011197
    },
    "jassi/remote/RemoteObject.ts": {
        "date": 1613219128046,
        "jassi.remote.RemoteObject": {}
    },
    "jassi/remote/RemoteProtocol.ts": {
        "date": 1613219136623,
        "jassi.remote.RemoteProtocol": {}
    },
    "jassi/remote/security/Group.ts": {
        "date": 1613218997136,
        "jassi.remote.security.Group": {
            "$DBObject": [
                {
                    "name": "jassi_group"
                }
            ]
        }
    },
    "jassi/remote/security/ParentRight.ts": {
        "date": 1613219003253,
        "jassi.remote.security.ParentRight": {
            "$DBObject": [
                {
                    "name": "jassi_parentright"
                }
            ]
        }
    },
    "jassi/remote/security/Right.ts": {
        "date": 1613219011774,
        "jassi.remote.security.Right": {
            "$DBObject": [
                {
                    "name": "jassi_right"
                }
            ]
        }
    },
    "jassi/remote/security/Rights.ts": {
        "date": 1613219021491,
        "jassi.remote.security.Rights": {}
    },
    "jassi/remote/security/User.ts": {
        "date": 1613219027355,
        "jassi.remote.security.User": {
            "$DBObject": [
                {
                    "name": "jassi_user"
                }
            ]
        }
    },
    "jassi/remote/Server.ts": {
        "date": 1613232706751,
        "jassi.remote.Server": {}
    },
    "jassi/server/Compile.ts": {
        "date": 1613246385279
    },
    "jassi/server/DBManager.ts": {
        "date": 1613245752692
    },
    "jassi/server/DoRemoteProtocol.ts": {
        "date": 1613223789102
    },
    "jassi/server/Filessystem.ts": {
        "date": 1613249019292
    },
    "jassi/server/GetRequest.ts": {
        "date": 1589836235449
    },
    "jassi/server/Indexer.ts": {
        "date": 1613245531530
    },
    "jassi/server/PassportLoginRegister.ts": {
        "date": 1613220855230
    },
    "jassi/server/PassportSetup.ts": {
        "date": 1613220873869
    },
    "jassi/server/RawBody.ts": {
        "date": 1589573020012
    },
    "jassi/server/Zip.ts": {
        "date": 1589573353489
    },
    "jassi/UserModel.ts": {
        "date": 1613218878493
    },
    "jassi/util/DatabaseSchema.ts": {
        "date": 1611490790268
    }
};
//# sourceMappingURL=registry.js.map