"use strict:";
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "jassi/remote/Classes.ts": {
        "date": 1613925159863,
        "jassi.remote.Classes": {}
    },
    "jassi/remote/Database.ts": {
        "date": 1622574367955,
        "jassi.remote.Database": {}
    },
    "jassi/remote/DBArray.ts": {
        "date": 1615231253407,
        "jassi.remote.DBArray": {}
    },
    "jassi/remote/DBObject.ts": {
        "date": 1618670223073,
        "jassi.remote.DBObject": {}
    },
    "jassi/remote/DBObjectQuery.ts": {
        "date": 1613218566583
    },
    "jassi/remote/Extensions.ts": {
        "date": 1615231258775
    },
    "jassi/remote/FileNode.ts": {
        "date": 1614803263239,
        "jassi.remote.FileNode": {}
    },
    "jassi/remote/hallo.ts": {
        "date": 1613218515810
    },
    "jassi/remote/Jassi.ts": {
        "date": 1614285410993,
        "jassi.remote.Jassi": {}
    },
    "jassi/remote/ObjectTransaction.ts": {
        "date": 1614468824546
    },
    "jassi/remote/Registry.ts": {
        "date": 1615986605063
    },
    "jassi/remote/RemoteObject.ts": {
        "date": 1614545171594,
        "jassi.remote.RemoteObject": {}
    },
    "jassi/remote/RemoteProtocol.ts": {
        "date": 1622499412074,
        "jassi.remote.RemoteProtocol": {}
    },
    "jassi/remote/security/Group.ts": {
        "date": 1622488337363,
        "jassi.security.Group": {
            "$DBObject": [
                {
                    "name": "jassi_group"
                }
            ]
        }
    },
    "jassi/remote/security/ParentRight.ts": {
        "date": 1622488385789,
        "jassi.security.ParentRight": {
            "$DBObject": [
                {
                    "name": "jassi_parentright"
                }
            ]
        }
    },
    "jassi/remote/security/Right.ts": {
        "date": 1622488393617,
        "jassi.security.Right": {
            "$DBObject": [
                {
                    "name": "jassi_right"
                }
            ]
        }
    },
    "jassi/remote/security/Rights.ts": {
        "date": 1622488403616,
        "jassi.security.Rights": {}
    },
    "jassi/remote/security/Setting.ts": {
        "date": 1622489979623,
        "jassi.security.Setting": {
            "$DBObject": [
                {
                    "name": "jassi_setting"
                }
            ]
        }
    },
    "jassi/remote/security/User.ts": {
        "date": 1622488411714,
        "jassi.security.User": {
            "$DBObject": [
                {
                    "name": "jassi_user"
                }
            ]
        }
    },
    "jassi/remote/Server.ts": {
        "date": 1622715804154,
        "jassi.remote.Server": {}
    },
    "jassi/remote/Settings.ts": {
        "date": 1622714168789,
        "jassi.remote.Settings": {}
    },
    "jassi/remote/Transaction.ts": {
        "date": 1614545262225,
        "jassi.remote.Transaction": {}
    },
    "jassi/server/Compile.ts": {
        "date": 1618564109929
    },
    "jassi/server/DBManager.ts": {
        "date": 1622714673039,
        "jassi_localserver.DBManager": {}
    },
    "jassi/server/DoRemoteProtocol.ts": {
        "date": 1614540000853
    },
    "jassi/server/Filesystem.ts": {
        "date": 1622398495469
    },
    "jassi/server/Indexer.ts": {
        "date": 1615116180620
    },
    "jassi/server/JassiServer.ts": {
        "date": 1622398327202
    },
    "jassi/server/PassportLoginRegister.ts": {
        "date": 1622715047008
    },
    "jassi/server/PassportSetup.ts": {
        "date": 1614464139513
    },
    "jassi/server/RawBody.ts": {
        "date": 1589573020012
    },
    "jassi/server/RegistryIndexer.ts": {
        "date": 1622198903787
    },
    "jassi/server/Zip.ts": {
        "date": 1614891596646
    },
    "jassi/UserModel.ts": {
        "date": 1613218878493
    },
    "jassi/util/DatabaseSchema.ts": {
        "date": 1611490790268
    }
};
//# sourceMappingURL=registry.js.map