"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"jassi/remote/Classes.ts": {
		"date": 1613925159863,
		"jassi.remote.Classes": {}
	},
	"jassi/remote/Database.ts": {
		"date": 1613249031685,
		"jassi.remote.Database": {}
	},
	"jassi/remote/DBArray.ts": {
		"date": 1613233278151,
		"jassi.remote.DBArray": {}
	},
	"jassi/remote/DBObject.ts": {
		"date": 1614545325200,
		"jassi.remote.DBObject": {}
	},
	"jassi/remote/DBObjectQuery.ts": {
		"date": 1613218566583
	},
	"jassi/remote/Extensions.ts": {
		"date": 1613925202662
	},
	"jassi/remote/FileNode.ts": {
		"date": 1614803263239,
		"jassi.remote.FileNode": {}
	},
	"jassi/remote/hallo.ts": {
		"date": 1613218515810
	},
	"jassi/remote/Jassi.ts": {
		"date": 1614285410993,
		"jassi.remote.Jassi": {}
	},
	"jassi/remote/ObjectTransaction.ts": {
		"date": 1614468824546
	},
	"jassi/remote/Registry.ts": {
		"date": 1614285404119
	},
	"jassi/remote/RemoteObject.ts": {
		"date": 1614545171594,
		"jassi.remote.RemoteObject": {}
	},
	"jassi/remote/RemoteProtocol.ts": {
		"date": 1614463817133,
		"jassi.remote.RemoteProtocol": {}
	},
	"jassi/remote/security/Group.ts": {
		"date": 1613218997136,
		"jassi.remote.security.Group": {
			"$DBObject": [
				{
					"name": "jassi_group"
				}
			]
		}
	},
	"jassi/remote/security/ParentRight.ts": {
		"date": 1613219003253,
		"jassi.remote.security.ParentRight": {
			"$DBObject": [
				{
					"name": "jassi_parentright"
				}
			]
		}
	},
	"jassi/remote/security/Right.ts": {
		"date": 1613219011774,
		"jassi.remote.security.Right": {
			"$DBObject": [
				{
					"name": "jassi_right"
				}
			]
		}
	},
	"jassi/remote/security/Rights.ts": {
		"date": 1614469207075,
		"jassi.remote.security.Rights": {}
	},
	"jassi/remote/security/User.ts": {
		"date": 1614459180220,
		"jassi.remote.security.User": {
			"$DBObject": [
				{
					"name": "jassi_user"
				}
			]
		}
	},
	"jassi/remote/Server.ts": {
		"date": 1614891730205,
		"jassi.remote.Server": {}
	},
	"jassi/remote/Transaction.ts": {
		"date": 1614545262225,
		"jassi.remote.Transaction": {}
	},
	"jassi/server/Compile.ts": {
		"date": 1613330043874
	},
	"jassi/server/DBManager.ts": {
		"date": 1614801636948
	},
	"jassi/server/DoRemoteProtocol.ts": {
		"date": 1614540000853
	},
	"jassi/server/Filesystem.ts": {
		"date": 1614891589205
	},
	"jassi/server/Indexer.ts": {
		"date": 1614891596646
	},
	"jassi/server/JassiServer.ts": {
		"date": 1614891596646
	},
	"jassi/server/PassportLoginRegister.ts": {
		"date": 1614463987601
	},
	"jassi/server/PassportSetup.ts": {
		"date": 1614464139513
	},
	"jassi/server/RawBody.ts": {
		"date": 1589573020012
	},
	"jassi/server/RegistryIndexer.ts": {
		"date": 1614891596646
	},
	"jassi/server/Zip.ts": {
		"date": 1614891596646
	},
	"jassi/UserModel.ts": {
		"date": 1613218878493
	},
	"jassi/util/DatabaseSchema.ts": {
		"date": 1611490790268
	}
}