//this file is autogenerated don't modify
define("jassi/registry",["require"], function(require) {
 return {
  default: {
	"jassi/base/ActionNode.ts": {
		"date": 1613505970029,
		"jassi.base.ActionNode": {}
	},
	"jassi/base/Actions.ts": {
		"date": 1613555666518,
		"jassi.base.Actions": {}
	},
	"jassi/base/Database.ts": {
		"date": 1613218544160,
		"jassi.base.Database": {},
		"jassi.base.Database.TypeResolver": {},
		"jassi.base.Database.Type": {},
		"jassi.base.Database.Field": {}
	},
	"jassi/base/DatabaseSchema.ts": {
		"date": 1622487662229,
		"jassi.base.DatabaseSchema": {}
	},
	"jassi/base/Errors.ts": {
		"date": 1590693468836
	},
	"jassi/base/Extensions.ts": {
		"date": 1613921826082
	},
	"jassi/base/LoginDialog.ts": {
		"date": 1622584859609
	},
	"jassi/base/PropertyEditorService.ts": {
		"date": 1613218566584,
		"jassi.base.PropertyEditorService": {}
	},
	"jassi/base/Router.ts": {
		"date": 1615231156312,
		"jassi.base.Router": {}
	},
	"jassi/base/Tests.ts": {
		"date": 1613416627532,
		"jassi.ui.TestAction": {
			"$ActionProvider": [
				"jassi.remote.FileNode"
			]
		},
		"jassi.base.Test": {}
	},
	"jassi/base/Windows.ts": {
		"date": 1613218544160,
		"jassi.base.Windows": {}
	},
	"jassi/jassi.ts": {
		"date": 1614358430834
	},
	"jassi/modul.ts": {
		"date": 1615134737730
	},
	"jassi/remote/Classes.ts": {
		"date": 1613925159863,
		"jassi.remote.Classes": {}
	},
	"jassi/remote/Database.ts": {
		"date": 1622574367955,
		"jassi.remote.Database": {}
	},
	"jassi/remote/DBArray.ts": {
		"date": 1615231253407,
		"jassi.remote.DBArray": {}
	},
	"jassi/remote/DBObject.ts": {
		"date": 1618670223073,
		"jassi.remote.DBObject": {}
	},
	"jassi/remote/DBObjectQuery.ts": {
		"date": 1613218566583
	},
	"jassi/remote/Extensions.ts": {
		"date": 1615231258775
	},
	"jassi/remote/FileNode.ts": {
		"date": 1614803263239,
		"jassi.remote.FileNode": {}
	},
	"jassi/remote/hallo.ts": {
		"date": 1613218515810
	},
	"jassi/remote/Jassi.ts": {
		"date": 1614285410993,
		"jassi.remote.Jassi": {}
	},
	"jassi/remote/ObjectTransaction.ts": {
		"date": 1614468824546
	},
	"jassi/remote/Registry.ts": {
		"date": 1615986605063
	},
	"jassi/remote/RemoteObject.ts": {
		"date": 1614545171594,
		"jassi.remote.RemoteObject": {}
	},
	"jassi/remote/RemoteProtocol.ts": {
		"date": 1622499412074,
		"jassi.remote.RemoteProtocol": {}
	},
	"jassi/remote/security/Group.ts": {
		"date": 1622488337363,
		"jassi.security.Group": {
			"$DBObject": [
				{
					"name": "jassi_group"
				}
			]
		}
	},
	"jassi/remote/security/ParentRight.ts": {
		"date": 1622488385789,
		"jassi.security.ParentRight": {
			"$DBObject": [
				{
					"name": "jassi_parentright"
				}
			]
		}
	},
	"jassi/remote/security/Right.ts": {
		"date": 1622488393617,
		"jassi.security.Right": {
			"$DBObject": [
				{
					"name": "jassi_right"
				}
			]
		}
	},
	"jassi/remote/security/Rights.ts": {
		"date": 1622488403616,
		"jassi.security.Rights": {}
	},
	"jassi/remote/security/Setting.ts": {
		"date": 1622489979623,
		"jassi.security.Setting": {
			"$DBObject": [
				{
					"name": "jassi_setting"
				}
			]
		}
	},
	"jassi/remote/security/User.ts": {
		"date": 1622488411714,
		"jassi.security.User": {
			"$DBObject": [
				{
					"name": "jassi_user"
				}
			]
		}
	},
	"jassi/remote/Server.ts": {
		"date": 1622198971874,
		"jassi.remote.Server": {}
	},
	"jassi/remote/Settings.ts": {
		"date": 1622569749272,
		"jassi.remote.Settings": {}
	},
	"jassi/remote/Transaction.ts": {
		"date": 1614545262225,
		"jassi.remote.Transaction": {}
	},
	"jassi/security/GroupView.ts": {
		"date": 1622035450211,
		"jassi/security/GroupView": {
			"$DBObjectView": [
				{
					"classname": "{{dbfullclassname}}"
				}
			]
		}
	},
	"jassi/security/UserView.ts": {
		"date": 1613218819988,
		"jassi/UserView": {
			"$DBObjectView": [
				{
					"classname": "jassi.security.User"
				}
			]
		}
	},
	"jassi/template/TemplateDBDialog.ts": {
		"date": 1615921857812,
		"jassi.ui.TemplateDBDialogProperties": {},
		"jassi.ui.TemplateDBDialog": {
			"$ActionProvider": [
				"jassi.remote.FileNode"
			]
		}
	},
	"jassi/template/TemplateDBObject.ts": {
		"date": 1613649434998,
		"jassi.ui.TemplateDBDialogProperties": {},
		"jassi.ui.TemplateDBObject": {
			"$ActionProvider": [
				"jassi.remote.FileNode"
			]
		}
	},
	"jassi/template/TemplateEmptyDialog.ts": {
		"date": 1613504671112,
		"jassi.ui.TemplateEmptyDialog": {
			"$ActionProvider": [
				"jassi.remote.FileNode"
			]
		}
	},
	"jassi/ui/ActionNodeMenu.ts": {
		"date": 1613512475808,
		"jassi/ui/ActionNodeMenu": {}
	},
	"jassi/ui/BoxPanel.ts": {
		"date": 1616801823471,
		"jassi.ui.BoxPanel": {
			"$UIComponent": [
				{
					"fullPath": "common/BoxPanel",
					"icon": "mdi mdi-view-sequential-outline",
					"editableChildComponents": [
						"this"
					]
				}
			],
			"$Property": [
				{
					"name": "isAbsolute",
					"hide": true,
					"type": "boolean"
				}
			]
		}
	},
	"jassi/ui/Button.ts": {
		"date": 1621966337826,
		"jassi.ui.Button": {
			"$UIComponent": [
				{
					"fullPath": "common/Button",
					"icon": "mdi mdi-gesture-tap-button",
					"initialize": {
						"text": "button"
					}
				}
			]
		}
	},
	"jassi/ui/Calendar.ts": {
		"date": 1622198594778,
		"jassi.ui.Calendar": {
			"$UIComponent": [
				{
					"fullPath": "common/Calendar",
					"icon": "mdi mdi-calendar-month"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "string"
				}
			]
		}
	},
	"jassi/ui/Checkbox.ts": {
		"date": 1615988827935,
		"jassi.ui.Checkbox": {
			"$UIComponent": [
				{
					"fullPath": "common/Ceckbox",
					"icon": "mdi mdi-checkbox-marked-outline"
				}
			]
		}
	},
	"jassi/ui/Component.ts": {
		"date": 1621967768029,
		"jassi.ui.Component": {}
	},
	"jassi/ui/ComponentDescriptor.ts": {
		"date": 1622549428373,
		"jassi.ui.ComponentDescriptor": {}
	},
	"jassi/ui/ComponentSpy.ts": {
		"date": 1615231223589,
		"jassi.ui.ComponentSpy": {
			"$ActionProvider": [
				"jassi.base.ActionNode"
			]
		}
	},
	"jassi/ui/Container.ts": {
		"date": 1613218544159,
		"jassi.ui.Container": {}
	},
	"jassi/ui/ContextMenu.ts": {
		"date": 1614703451260,
		"jassi.ui.ContextMenu": {
			"$UIComponent": [
				{
					"fullPath": "common/ContextMenu",
					"icon": "mdi mdi-dots-vertical",
					"editableChildComponents": [
						"menu"
					]
				}
			]
		}
	},
	"jassi/ui/converters/DefaultConverter.ts": {
		"date": 1615231302585,
		"jassi.ui.converters.DefaultConverterProperties": {},
		"jassi.ui.converters.DefaultConverter": {
			"$Converter": [
				{
					"name": "custom"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassi.ui.converters.DefaultConverterProperties"
				}
			]
		}
	},
	"jassi/ui/converters/NumberConverter.ts": {
		"date": 1621963163546,
		"jassi.ui.converters.NumberConverter": {
			"$Converter": [
				{
					"name": "number"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json"
				}
			]
		}
	},
	"jassi/ui/converters/StringConverter.ts": {
		"date": 1615231315342,
		"jassi.ui.converters.StringConverter": {
			"$Converter": [
				{
					"name": "string"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json"
				}
			]
		}
	},
	"jassi/ui/CSSProperties.ts": {
		"date": 1613218544159,
		"jassi.ui.CSSProperties": {}
	},
	"jassi/ui/DatabaseDesigner.ts": {
		"date": 1616102745056,
		"jassi/ui/DatabaseDesigner": {
			"$ActionProvider": [
				"jassi.base.ActionNode"
			]
		}
	},
	"jassi/ui/Databinder.ts": {
		"date": 1621971369148,
		"jassi.ui.Databinder": {
			"$UIComponent": [
				{
					"fullPath": "common/Databinder",
					"icon": "mdi mdi-connection"
				}
			]
		}
	},
	"jassi/ui/DataComponent.ts": {
		"date": 1615587905350,
		"jassi.ui.DataComponent": {}
	},
	"jassi/ui/DBObjectDialog.ts": {
		"date": 1614464799579,
		"jassi.ui.DBObjectDialog": {
			"$ActionProvider": [
				"jassi.base.ActionNode"
			]
		}
	},
	"jassi/ui/DBObjectExplorer.ts": {
		"date": 1622585229596,
		"jassi.ui.DBObjectNode": {},
		"jassi.ui.DBFileActions": {
			"$ActionProvider": [
				"jassi.remote.FileNode"
			]
		},
		"jassi.ui.DBObjectActions": {
			"$ActionProvider": [
				"jassi.ui.DBObjectNode"
			]
		},
		"jassi.ui.DBObjectExplorer": {
			"$ActionProvider": [
				"jassi.base.ActionNode"
			]
		}
	},
	"jassi/ui/DBObjectView.ts": {
		"date": 1622035473442,
		"jassi/ui/DBObjectView": {
			"$UIComponent": [
				{
					"editableChildComponents": [
						"this",
						"me.main",
						"me.toolbar",
						"me.save",
						"me.remove",
						"me.refresh"
					]
				}
			]
		}
	},
	"jassi/ui/DesignDummy.ts": {
		"date": 1615231275007,
		"jassi.ui.DesignDummy": {}
	},
	"jassi/ui/DockingContainer.ts": {
		"date": 1613218544158,
		"jassi.ui.DockingContainer": {}
	},
	"jassi/ui/ErrorPanel.ts": {
		"date": 1622199248933,
		"jassi.ui.ErrorPanel": {
			"$ActionProvider": [
				"jassi.base.ActionNode"
			]
		}
	},
	"jassi/ui/FileExplorer.ts": {
		"date": 1622585294035,
		"jassi.ui.FileActions": {
			"$ActionProvider": [
				"jassi.remote.FileNode"
			]
		},
		"jassi.ui.FileExplorer": {
			"$ActionProvider": [
				"jassi.base.ActionNode"
			]
		}
	},
	"jassi/ui/HTMLEditorPanel.ts": {
		"date": 1613218566582,
		"jassi.ui.HTMLEditorPanel": {}
	},
	"jassi/ui/HTMLPanel.ts": {
		"date": 1617202756406,
		"jassi.ui.HTMLPanel": {
			"$UIComponent": [
				{
					"fullPath": "common/HTMLPanel",
					"icon": "mdi mdi-cloud-tags"
				}
			]
		}
	},
	"jassi/ui/Image.ts": {
		"date": 1614118156072,
		"jassi.ui.Image": {
			"$UIComponent": [
				{
					"fullPath": "default/Image",
					"icon": "mdi mdi-file-image"
				}
			]
		}
	},
	"jassi/ui/InvisibleComponent.ts": {
		"date": 1615231279789,
		"jassi.ui.InvisibleComponent": {
			"$Property": [
				{
					"hideBaseClassProperties": true
				}
			]
		}
	},
	"jassi/ui/Menu.ts": {
		"date": 1613218544159,
		"jassi.ui.Menu": {
			"$UIComponent": [
				{
					"fullPath": "common/Menu",
					"icon": "mdi mdi-menu",
					"initialize": {
						"text": "menu"
					}
				}
			]
		}
	},
	"jassi/ui/MenuItem.ts": {
		"date": 1613506069164,
		"jassi.ui.MenuItem": {
			"$UIComponent": [
				{
					"fullPath": "common/MenuItem",
					"icon": "mdi mdi-menu-open",
					"initialize": {
						"text": "menu"
					},
					"editableChildComponents": [
						"items"
					]
				}
			]
		}
	},
	"jassi/ui/ObjectChooser.ts": {
		"date": 1616195924588,
		"jassi.ui.ObjectChooser": {
			"$UIComponent": [
				{
					"fullPath": "common/ObjectChooser",
					"icon": "mdi mdi-glasses"
				}
			]
		}
	},
	"jassi/ui/OptionDialog.ts": {
		"date": 1613218544158,
		"jassi.ui.OptionDialog": {},
		"jassi.ui.OptionDialogTestProp": {}
	},
	"jassi/ui/Panel.ts": {
		"date": 1617031543751,
		"jassi.ui.PanelCreateProperties": {},
		"jassi.ui.Panel": {
			"$UIComponent": [
				{
					"fullPath": "common/Panel",
					"icon": "mdi mdi-checkbox-blank-outline",
					"editableChildComponents": [
						"this"
					]
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassi.ui.PanelCreateProperties"
				}
			]
		}
	},
	"jassi/ui/Property.ts": {
		"date": 1613218566584,
		"jassi.ui.Property": {}
	},
	"jassi/ui/PropertyEditor.ts": {
		"date": 1615844604424,
		"jassi.ui.PropertyEditor": {},
		"jassi.ui.PropertyEditorTestProperties": {}
	},
	"jassi/ui/PropertyEditors/BooleanEditor.ts": {
		"date": 1613218544157,
		"jassi.ui.PropertyEditors.BooleanEditor": {
			"$PropertyEditor": [
				[
					"boolean"
				]
			]
		}
	},
	"jassi/ui/PropertyEditors/ClassSelectorEditor.ts": {
		"date": 1613421412342,
		"jassi.ui.PropertyEditors.ClassSelectorEditor": {
			"$PropertyEditor": [
				[
					"classselector"
				]
			]
		}
	},
	"jassi/ui/PropertyEditors/ColorEditor.ts": {
		"date": 1613421827599,
		"jassi.ui.PropertyEditors.ColorEditor": {
			"$PropertyEditor": [
				[
					"color"
				]
			]
		}
	},
	"jassi/ui/PropertyEditors/ComponentSelectorEditor.ts": {
		"date": 1613338542938,
		"jassi.ui.PropertyEditors.ComponentSelectorEditor": {
			"$PropertyEditor": [
				[
					"componentselector"
				]
			]
		}
	},
	"jassi/ui/PropertyEditors/DatabinderEditor.ts": {
		"date": 1613421449783,
		"jassi.ui.PropertyEditors.DatabinderEditor": {
			"$PropertyEditor": [
				[
					"databinder"
				]
			]
		}
	},
	"jassi/ui/PropertyEditors/DBObjectEditor.ts": {
		"date": 1613218544160,
		"jassi.ui.PropertyEditors.DBObjectEditor": {
			"$PropertyEditor": [
				[
					"dbobject"
				]
			]
		}
	},
	"jassi/ui/PropertyEditors/DefaultEditor.ts": {
		"date": 1613421239003,
		"jassi.ui.PropertyEditors.DefaultEditor": {
			"$PropertyEditor": [
				[
					"string",
					"number",
					"number[]"
				]
			]
		}
	},
	"jassi/ui/PropertyEditors/Editor.ts": {
		"date": 1613218566582,
		"jassi.ui.PropertyEditors.Editor": {}
	},
	"jassi/ui/PropertyEditors/FontEditor.ts": {
		"date": 1613338564468,
		"jassi.ui.PropertyEditors.FontEditor": {
			"$PropertyEditor": [
				[
					"font"
				]
			]
		}
	},
	"jassi/ui/PropertyEditors/FunctionEditor.ts": {
		"date": 1613421461639,
		"jassi.ui.PropertyEditors.FunctionEditor": {
			"$PropertyEditor": [
				[
					"function"
				]
			]
		}
	},
	"jassi/ui/PropertyEditors/HTMLEditor.ts": {
		"date": 1613218544157,
		"jassi.ui.PropertyEditors.HTMLEditor": {
			"$PropertyEditor": [
				[
					"html"
				]
			]
		}
	},
	"jassi/ui/PropertyEditors/ImageEditor.ts": {
		"date": 1614118659538,
		"jassi.ui.PropertyEditors.ImageEditor": {
			"$ActionProvider": [
				"jassi.base.ActionNode"
			],
			"$PropertyEditor": [
				[
					"image"
				]
			]
		}
	},
	"jassi/ui/PropertyEditors/JsonEditor.ts": {
		"date": 1613332987727,
		"jassi.ui.PropertyEditors.JsonEditor": {
			"$PropertyEditor": [
				[
					"json"
				]
			]
		},
		"jassi.ui.PropertyEditorTestProperties": {},
		"jassi.ui.PropertyEditorTestProperties2": {}
	},
	"jassi/ui/PropertyEditors/LoadingEditor.ts": {
		"date": 1613218544158
	},
	"jassi/ui/PropertyEditors/NameEditor.ts": {
		"date": 1613421352058,
		"jassi.ui.PropertyEditors.NameEditor": {
			"$PropertyEditor": [
				[
					"*name*"
				]
			]
		}
	},
	"jassi/ui/Repeater.ts": {
		"date": 1616795708998,
		"jassi.ui.RepeaterDesignPanel": {
			"$UIComponent": [
				{
					"editableChildComponents": [
						"databinder"
					]
				}
			]
		},
		"jassi.ui.Repeater": {
			"$UIComponent": [
				{
					"fullPath": "common/Repeater",
					"icon": "mdi mdi-locker-multiple",
					"editableChildComponents": [
						"this",
						"design"
					]
				}
			]
		}
	},
	"jassi/ui/SearchExplorer.ts": {
		"date": 1622585287990,
		"jassi.ui.SearchExplorer": {
			"$ActionProvider": [
				"jassi.base.ActionNode"
			]
		}
	},
	"jassi/ui/Select.ts": {
		"date": 1613338080789,
		"jassi.ui.SelectCreateProperties": {},
		"jassi.ui.Select": {
			"$UIComponent": [
				{
					"fullPath": "common/Select",
					"icon": "mdi mdi-form-dropdown"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassi.ui.SelectCreateProperties"
				}
			]
		}
	},
	"jassi/ui/SettingsDialog.ts": {
		"date": 1622548257613,
		"jassi_editor.Testuw": {
			"$SettingsDescriptor": []
		},
		"jassi.ui.SettingsDialogCurrentSettings": {},
		"jassi.ui.SettingsDialog": {}
	},
	"jassi/ui/Style.ts": {
		"date": 1613218544157,
		"jassi.ui.Style": {
			"$UIComponent": [
				{
					"fullPath": "common/Style",
					"icon": "mdi mdi-virus"
				}
			]
		}
	},
	"jassi/ui/Table.ts": {
		"date": 1618667343544,
		"jassi.ui.TableEditorProperties": {},
		"jassi.ui.Table": {
			"$UIComponent": [
				{
					"fullPath": "common/Table",
					"icon": "mdi mdi-grid"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassi.ui.TableEditorProperties"
				}
			]
		}
	},
	"jassi/ui/Textarea.ts": {
		"date": 1614023973946,
		"jassi.ui.Textarea": {
			"$UIComponent": [
				{
					"fullPath": "common/Textarea",
					"icon": "mdi mdi-text-box-outline"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "string"
				}
			]
		}
	},
	"jassi/ui/Textbox.ts": {
		"date": 1622197522304,
		"jassi.ui.Textbox": {
			"$UIComponent": [
				{
					"fullPath": "common/Textbox",
					"icon": "mdi mdi-form-textbox"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "string"
				}
			]
		}
	},
	"jassi/ui/Tree.ts": {
		"date": 1614961346455,
		"jassi.ui.TreeEditorPropertiesMulti": {},
		"jassi.ui.TreeEditorProperties": {},
		"jassi.ui.Tree": {
			"$UIComponent": [
				{
					"fullPath": "common/Tree",
					"icon": "mdi mdi-file-tree"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassi.ui.TreeEditorProperties"
				}
			]
		}
	},
	"jassi/ui/Upload.ts": {
		"date": 1622198762488,
		"jassi.ui.Upload": {
			"$UIComponent": [
				{
					"fullPath": "common/Upload",
					"icon": "mdi mdi-cloud-upload-outline"
				}
			]
		}
	},
	"jassi/ui/VariablePanel.ts": {
		"date": 1616796607091,
		"jassi.ui.VariablePanel": {}
	},
	"jassi/util/Cookies.ts": {
		"date": 1611783871704
	},
	"jassi/util/CSVImport.ts": {
		"date": 1618558365447,
		"jassi.util.CSVImport": {
			"$ActionProvider": [
				"jassi.base.ActionNode"
			]
		}
	},
	"jassi/util/DatabaseSchema.ts": {
		"date": 1622574331537
	},
	"jassi/util/Numberformatter.ts": {
		"date": 1622031313274,
		"jassi.util.Numberformatter": {}
	},
	"jassi/util/Reloader.ts": {
		"date": 1615324259508,
		"jassi.util.Reloader": {}
	},
	"jassi/util/Tools.ts": {
		"date": 1613218544160,
		"jassi.util.Tools": {}
	}
}
 }
});