//this file is autogenerated don't modify
define("de/registry",["require"], function(require) {
 return {
  default: {
	"de/d2de.ts": {
		"date": 1587933243841
	},
	"de/del.ts": {
		"date": 1622984213677
	},
	"de/Dialog.ts": {
		"date": 1622984213677,
		"de/Dialog": {}
	},
	"de/DialogKunde.ts": {
		"date": 1622985638961,
		"de.DialogKunde": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			]
		}
	},
	"de/modul.ts": {
		"date": 1612818328924
	},
	"de/oo/dd.ts": {
		"date": 1588091991590
	},
	"de/pp/aa/a.ts": {
		"date": 1588092762645
	},
	"de/q.ts": {
		"date": 1588091498058
	},
	"de/remote/AR.ts": {
		"date": 1622985477990,
		"de.AR": {
			"$Rights": [
				[
					{
						"name": "Auftragswesen/Ausgangsrechnung/festschreiben"
					},
					{
						"name": "Auftragswesen/Ausgangsrechnung/löschen"
					}
				]
			],
			"$DBObject": []
		}
	},
	"de/remote/ARZeile.ts": {
		"date": 1622985479813,
		"de.ARZeile": {
			"$DBObject": []
		}
	},
	"de/remote/Kunde.ext.ts": {
		"date": 1622985482440
	},
	"de/remote/Kunde.ts": {
		"date": 1622985484542,
		"de.Kunde": {
			"$ParentRights": [
				[
					{
						"name": "Kundennummern",
						"sqlToCheck": "me.id>=:i1 and me.id<=:i2",
						"description": {
							"text": "Kundennummern",
							"i1": "von",
							"i2": "bis"
						}
					}
				]
			],
			"$DBObject": []
		}
	},
	"de/remote/KundeExt.ts": {
		"date": 1622985486232,
		"de.KundeExt": {
			"$Extension": [
				"de.Kunde"
			]
		}
	},
	"de/remote/KundeExt2.ts": {
		"date": 1622985488536
	},
	"de/remote/Lieferant.ts": {
		"date": 1622985489873,
		"de.Lieferant": {
			"$DBObject": []
		}
	},
	"de/remote/MyUser.ts": {
		"date": 1622985491688,
		"de.MyUser": {
			"$DBObject": [],
			"Entity": []
		}
	}
}
 }
});