//this file is autogenerated don't modify
define("de/registry",["require"], function(require) {
 return {
  default: {
	"de/Dialog2.ts": {
		"date": 1697206950609.826,
		"de/Dialog2": {}
	},
	"de/DialogKunde.ts": {
		"date": 1740069816811.559,
		"de.DialogKunde": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"render": {
					"$Action": [
						{
							"name": "Demo",
							"icon": "mdi mdi-television-play"
						}
					]
				},
				"showDialog": {
					"$Action": [
						{
							"name": "Demo/Kunden",
							"icon": "mdi mdi-account"
						}
					]
				}
			}
		}
	},
	"de/KundeView.ts": {
		"date": 1740069816812.5593,
		"de.KundeView": {
			"$DBObjectView": [
				{
					"classname": "de.Kunde"
				}
			]
		}
	},
	"de/modul.ts": {
		"date": 1655740312000
	},
	"de/remote/AR.ts": {
		"date": 1750088588608.2544,
		"de.AR": {
			"$Rights": [
				[
					{
						"name": "Auftragswesen/Ausgangsrechnung/festschreiben"
					},
					{
						"name": "Auftragswesen/Ausgangsrechnung/löschen"
					}
				]
			],
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"strasse": {
					"Column": []
				},
				"nummer": {
					"Column": []
				},
				"ort": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"kunde": {
					"ManyToOne": [
						"function",
						"function"
					]
				},
				"zeilen": {
					"OneToMany": [
						"function",
						"function"
					]
				},
				"myfind": {
					"UseServer": []
				}
			}
		}
	},
	"de/remote/ARZeile.ts": {
		"date": 1749963543806.5596,
		"de.ARZeile": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryGeneratedColumn": []
				},
				"text": {
					"Column": []
				},
				"position": {
					"Column": []
				},
				"preis": {
					"Column": [
						{
							"nullable": true,
							"type": "decimal"
						}
					]
				},
				"ar": {
					"ManyToOne": [
						"function",
						"function"
					]
				},
				"find": {
					"UseServer": []
				}
			}
		}
	},
	"de/remote/Kunde.ext.ts": {
		"date": 1622985484000
	},
	"de/remote/Kunde.ts": {
		"date": 1749964322573.4482,
		"de.Kunde": {
			"$ParentRights": [
				[
					{
						"name": "Kundennummern",
						"sqlToCheck": "me.id>=:i1 and me.id<=:i2",
						"description": {
							"text": "Kundennummern",
							"i1": "von",
							"i2": "bis"
						}
					}
				]
			],
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"vorname": {
					"Column": []
				},
				"nachname": {
					"Column": []
				},
				"strasse": {
					"Column": []
				},
				"PLZ": {
					"Column": []
				},
				"ort": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"hausnummer": {
					"Column": []
				},
				"rechnungen": {
					"OneToMany": [
						"function",
						"function"
					]
				},
				"alleKundenNachNachname": {
					"$DBObjectQuery": [
						{
							"name": "Alle nach Namen",
							"description": "Kundenliste nach Namen"
						}
					]
				},
				"alleKundenNachNummer": {
					"$DBObjectQuery": [
						{
							"name": "Alle nach Nummer",
							"description": "Kundenliste nach Nummer"
						}
					]
				},
				"find": {
					"UseServer": []
				},
				"land": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"test": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"de/remote/KundeExt.ts": {
		"date": 1655556796000,
		"de.KundeExt": {
			"$Extension": [
				"de.Kunde"
			]
		}
	},
	"de/remote/KundeExt2.ts": {
		"date": 1655556796000,
		"de.KundeExt2": {
			"$Extension": [
				"de.Kunde"
			]
		}
	},
	"de/remote/Lieferant.ts": {
		"date": 1656072674000,
		"de.Lieferant": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"name": {
					"Column": [
						{
							"nullable": false
						}
					]
				}
			}
		}
	},
	"de/remote/MyRemoteObject.ts": {
		"date": 1750546788159.0122,
		"de.remote.MyRemoteObject": {
			"@members": {
				"sayHello": {
					"ValidateFunctionParameter": []
				},
				"sayHello2": {
					"ValidateFunctionParameter": []
				}
			}
		}
	},
	"de/remote/MyUser.ts": {
		"date": 1656072680000,
		"de.MyUser": {
			"$DBObject": [],
			"Entity": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"firstName": {
					"Column": []
				},
				"lastName": {
					"Column": []
				},
				"age": {
					"Column": []
				}
			}
		}
	},
	"de/Report1.ts": {
		"date": 1656019764000
	},
	"de/ReportKunde.ts": {
		"date": 1655556796000,
		"de.ReportKunde": {
			"@members": {}
		}
	},
	"de/ReportKunden.ts": {
		"date": 1655556796000,
		"de.ReportKunde": {
			"@members": {}
		}
	},
	"de/test.ts": {
		"date": 1681301006000
	},
	"de/TestEmployees.ts": {
		"date": 1697199351525.1855
	},
	"de/TestExtension.ts": {
		"date": 1656077196000
	},
	"de/TH.ts": {
		"date": 1682186442000
	},
	"de/TTDialog.ts": {
		"date": 1655556796000,
		"de/TTDialog": {}
	},
	"de/ab.ts": {
		"date": 1749962018973.366
	},
	"de/remote/DelRemoteObject.ts": {
		"date": 1750088961591.24,
		"de.remote.DelRemoteObject": {}
	},
	"de/zz.ts": {
		"date": 1750427245317.2957
	},
	"de/remote/MyRemoteObject2.ts": {
		"date": 1750547089612.7952,
		"de.remote.MyRemoteObject2": {},
		"de.remote.MyRemoteObject": {
			"@members": {
				"sayHello": {
					"ValidateFunctionParameter": []
				},
				"sayHello2": {
					"ValidateFunctionParameter": []
				}
			}
		}
	},
	"de/remote/ll.ts": {
		"date": 1750547610214.476,
		"de.remote.ll": {
			"@members": {
				"sayHello": {
					"ValidateFunctionParameter": []
				},
				"info": {
					"UseServer": []
				}
			}
		}
	},
	"de/remote/Loch.ts": {
		"date": 1750547500344.0847,
		"de.remote.Loch": {},
		"de.remote.MyRemoteObject": {
			"@members": {
				"sayHello": {
					"ValidateFunctionParameter": []
				},
				"sayHello2": {
					"ValidateFunctionParameter": []
				}
			}
		}
	},
	"de/aa.ts": {
		"date": 1682369482000
	}
}
 }
});