//this file is autogenerated don't modify
define("jassijs_report/registry",["require"], function(require) {
 return {
  default: {
	"jassijs_report/designer/ReportDesigner.ts": {
		"date": 1684440710650.4395,
		"jassijs_report.designer.ReportDesigner": {}
	},
	"jassijs_report/designer/SimpleReportDesigner.ts": {
		"date": 1655556794000,
		"jassijs_report.designer.SimpleReportDesigner": {}
	},
	"jassijs_report/ext/pdfjs.ts": {
		"date": 1657714200000
	},
	"jassijs_report/ext/pdfmake.ts": {
		"date": 1657714352000
	},
	"jassijs_report/modul.ts": {
		"date": 1655329710000
	},
	"jassijs_report/pdfMake-interface.ts": {
		"date": 1681513961981.488
	},
	"jassijs_report/PDFReport.ts": {
		"date": 1655556866000,
		"jassijs_report.PDFReport": {}
	},
	"jassijs_report/PDFViewer.ts": {
		"date": 1681513899602.687,
		"jassijs_report.PDFViewer": {}
	},
	"jassijs_report/RColumns.ts": {
		"date": 1655929934000,
		"jassijs_report.RColumns": {
			"$ReportComponent": [
				{
					"fullPath": "report/Columns",
					"icon": "mdi mdi-view-parallel-outline",
					"editableChildComponents": [
						"this"
					]
				}
			]
		}
	},
	"jassijs_report/RComponent.ts": {
		"date": 1655930740000,
		"jassijs_report.ReportComponent": {
			"$Property": [
				{
					"hideBaseClassProperties": true
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/RDatatable.ts": {
		"date": 1655930956000,
		"jassijs_report.RDatatable": {
			"$ReportComponent": [
				{
					"fullPath": "report/Datatable",
					"icon": "mdi mdi-table-cog",
					"editableChildComponents": [
						"this",
						"this.headerPanel",
						"this.bodyPanel",
						"this.footerPanel"
					]
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/remote/pdfmakejassi.ts": {
		"date": 1634336644000
	},
	"jassijs_report/remote/RComponent.ts": {
		"date": 1656016830000,
		"jassijs_report.ReportComponent": {
			"$Property": [
				{
					"hideBaseClassProperties": true
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/remote/ServerReport.ts": {
		"date": 1684441132383.0664,
		"jassijs_report.remote.ServerReport": {
			"@members": {
				"getDesign": {
					"ValidateFunctionParameter": []
				},
				"getBase64": {
					"ValidateFunctionParameter": []
				}
			}
		}
	},
	"jassijs_report/Report.ts": {
		"date": 1656501702000,
		"jassijs_report.remote.Report": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"createActions": {
					"$Actions": []
				}
			}
		}
	},
	"jassijs_report/ReportDesign.ts": {
		"date": 1656015000000,
		"jassijs_report.InfoProperties": {
			"@members": {}
		},
		"jassijs_report.PermissionProperties": {
			"@members": {}
		},
		"jassijs_report.StyleContainer": {
			"$Property": [
				{
					"hideBaseClassProperties": true
				}
			]
		},
		"jassijs_report.ReportDesign": {
			"$ReportComponent": [
				{
					"fullPath": "undefined",
					"icon": "undefined",
					"editableChildComponents": [
						"this",
						"this.backgroundPanel",
						"this.headerPanel",
						"this.contentPanel",
						"this.footerPanel"
					]
				}
			],
			"$Property": [
				{
					"hideBaseClassProperties": true
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/ReportDesignGlobal.ts": {
		"date": 1655397714000
	},
	"jassijs_report/Reports.ts": {
		"date": 1657978946000,
		"jassijs_report/Reports": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"show": {
					"$Action": [
						{
							"name": "Tools/Reports",
							"icon": "mdi mdi-chart-box-outline"
						}
					]
				}
			}
		}
	},
	"jassijs_report/ReportViewer.ts": {
		"date": 1681571041226.5884,
		"jassijs_report/ReportViewer": {}
	},
	"jassijs_report/RGroupTablerow.ts": {
		"date": 1656073104000,
		"jassijs_report.RTablerow": {
			"$ReportComponent": [
				{
					"editableChildComponents": [
						"this"
					]
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/RImage.ts": {
		"date": 1656184928000,
		"jassijs_report.RImage": {
			"$ReportComponent": [
				{
					"fullPath": "report/Image",
					"icon": "mdi mdi-image-frame"
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/RImageEditor.ts": {
		"date": 1656017314000,
		"jassi_report/RImagePropertyEditor": {
			"$PropertyEditor": [
				[
					"rimage"
				]
			]
		}
	},
	"jassijs_report/ROList.ts": {
		"date": 1656019462000,
		"jassijs_report.ROList": {
			"$ReportComponent": [
				{
					"fullPath": "report/Ordered List",
					"icon": "mdi mdi-format-list-numbered",
					"editableChildComponents": [
						"this"
					]
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/RStack.ts": {
		"date": 1656015322000,
		"jassijs_report.RStack": {
			"$ReportComponent": [
				{
					"fullPath": "report/Stack",
					"icon": "mdi mdi-view-sequential-outline",
					"editableChildComponents": [
						"this"
					]
				}
			]
		}
	},
	"jassijs_report/RStyle.ts": {
		"date": 1656015340000,
		"jassijs_report.RStyle": {
			"$ReportComponent": [
				{
					"fullPath": "report/Style",
					"icon": "mdi mdi-virus-outline",
					"editableChildComponents": [
						"this"
					]
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/RTable.ts": {
		"date": 1681571019401.4517,
		"jassijs_report.RTable": {
			"$ReportComponent": [
				{
					"fullPath": "report/Table",
					"icon": "mdi mdi-table-large",
					"editableChildComponents": [
						"this",
						"this.headerPanel",
						"this.bodyPanel",
						"this.footerPanel"
					]
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/RTableLayouts.ts": {
		"date": 1633113320000
	},
	"jassijs_report/RTablerow.ts": {
		"date": 1656019424000,
		"jassijs_report.RTablerow": {
			"$ReportComponent": [
				{
					"editableChildComponents": [
						"this"
					]
				}
			]
		}
	},
	"jassijs_report/RText.ts": {
		"date": 1656335832000,
		"jassijs_report.RText": {
			"$ReportComponent": [
				{
					"fullPath": "report/Text",
					"icon": "mdi mdi-format-color-text"
				}
			],
			"$Property": [
				{
					"name": "value",
					"type": "string",
					"description": "text"
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/RTextGroup.ts": {
		"date": 1656016376000,
		"jassijs_report.RTextGroup": {
			"$ReportComponent": [
				{
					"fullPath": "report/TextGroup",
					"icon": "mdi mdi-text-box-multiple-outline",
					"editableChildComponents": [
						"this"
					]
				}
			]
		}
	},
	"jassijs_report/RUList.ts": {
		"date": 1656016418000,
		"jassijs_report.RUList": {
			"$ReportComponent": [
				{
					"fullPath": "report/Unordered List",
					"icon": "mdi mdi-format-list-bulleted",
					"editableChildComponents": [
						"this"
					]
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/RUnknown.ts": {
		"date": 1656016430000,
		"jassijs_report.RUnknown": {}
	},
	"jassijs_report/server/DoServerreport.ts": {
		"date": 1684441369461.1033
	},
	"jassijs_report/server/TestServerreport.ts": {
		"date": 1684501451913.4646
	},
	"jassijs_report/SimpleReportEditor.ts": {
		"date": 1655637342000,
		"jassi_report.SimpleReportEditor": {}
	},
	"jassijs_report/StartReporteditor.ts": {
		"date": 1681570913030.2517
	},
	"jassijs_report/TemplateReport.ts": {
		"date": 1681570098047.462,
		"jassijs_report.TemplateReport": {
			"$ActionProvider": [
				"jassijs.remote.FileNode"
			],
			"@members": {
				"newFile": {
					"$Action": [
						{
							"name": "New/Report",
							"isEnabled": "function"
						}
					]
				}
			}
		}
	},
	"jassijs_report/test/ClientReport.ts": {
		"date": 1656501728000,
		"jassijs_report.test.ClientReport": {
			"$Report": [
				{
					"name": "test/Sample Clientreport"
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/test/ServerReport.ts": {
		"date": 1684401086547.6228,
		"jassijs_report.test.ServerReport": {
			"$Report": [
				{
					"name": "test/Sample Serverreport",
					"serverReportPath": "jassijs_report/server/TestServerreport"
				}
			],
			"@members": {}
		}
	}
}
 }
});