//this file is autogenerated don't modify
define("jassijs_report/registry",["require"], function(require) {
 return {
  default: {
	"jassijs_report/designer/ReportDesigner.ts": {
		"date": 1656337133845,
		"jassijs_report.designer.ReportDesigner": {}
	},
	"jassijs_report/designer/SimpleReportDesigner.ts": {
		"date": 1655556793964,
		"jassijs_report.designer.SimpleReportDesigner": {}
	},
	"jassijs_report/modul.ts": {
		"date": 1655329708587
	},
	"jassijs_report/pdfMake-interface.ts": {
		"date": 1656184595147
	},
	"jassijs_report/PDFReport.ts": {
		"date": 1655556864381,
		"jassijs_report.PDFReport": {}
	},
	"jassijs_report/PDFViewer.ts": {
		"date": 1656015023161,
		"jassijs_report.PDFViewer": {}
	},
	"jassijs_report/RColumns.ts": {
		"date": 1655929932578,
		"jassijs_report.RColumns": {
			"$ReportComponent": [
				{
					"fullPath": "report/Columns",
					"icon": "mdi mdi-view-parallel-outline",
					"editableChildComponents": [
						"this"
					]
				}
			]
		}
	},
	"jassijs_report/RComponent.ts": {
		"date": 1655930739791,
		"jassijs_report.ReportComponent": {
			"$Property": [
				{
					"hideBaseClassProperties": true
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/RDatatable.ts": {
		"date": 1655930954595,
		"jassijs_report.RDatatable": {
			"$ReportComponent": [
				{
					"fullPath": "report/Datatable",
					"icon": "mdi mdi-table-cog",
					"editableChildComponents": [
						"this",
						"this.headerPanel",
						"this.bodyPanel",
						"this.footerPanel"
					]
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/remote/pdfmakejassi.ts": {
		"date": 1634336644000
	},
	"jassijs_report/ReportDesign.ts": {
		"date": 1656014998740,
		"jassijs_report.InfoProperties": {
			"@members": {}
		},
		"jassijs_report.PermissionProperties": {
			"@members": {}
		},
		"jassijs_report.StyleContainer": {
			"$Property": [
				{
					"hideBaseClassProperties": true
				}
			]
		},
		"jassijs_report.ReportDesign": {
			"$ReportComponent": [
				{
					"fullPath": "undefined",
					"icon": "undefined",
					"editableChildComponents": [
						"this",
						"this.backgroundPanel",
						"this.headerPanel",
						"this.contentPanel",
						"this.footerPanel"
					]
				}
			],
			"$Property": [
				{
					"hideBaseClassProperties": true
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/ReportDesignGlobal.ts": {
		"date": 1655397712425
	},
	"jassijs_report/RGroupTablerow.ts": {
		"date": 1656073103788,
		"jassijs_report.RTablerow": {
			"$ReportComponent": [
				{
					"editableChildComponents": [
						"this"
					]
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/RImage.ts": {
		"date": 1656184927090,
		"jassijs_report.RImage": {
			"$ReportComponent": [
				{
					"fullPath": "report/Image",
					"icon": "mdi mdi-image-frame"
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/RImageEditor.ts": {
		"date": 1656017313344,
		"jassi_report/RImagePropertyEditor": {
			"$PropertyEditor": [
				[
					"rimage"
				]
			]
		}
	},
	"jassijs_report/ROList.ts": {
		"date": 1656019460389,
		"jassijs_report.ROList": {
			"$ReportComponent": [
				{
					"fullPath": "report/Ordered List",
					"icon": "mdi mdi-format-list-numbered",
					"editableChildComponents": [
						"this"
					]
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/RStack.ts": {
		"date": 1656015321904,
		"jassijs_report.RStack": {
			"$ReportComponent": [
				{
					"fullPath": "report/Stack",
					"icon": "mdi mdi-view-sequential-outline",
					"editableChildComponents": [
						"this"
					]
				}
			]
		}
	},
	"jassijs_report/RStyle.ts": {
		"date": 1656015338312,
		"jassijs_report.RStyle": {
			"$ReportComponent": [
				{
					"fullPath": "report/Style",
					"icon": "mdi mdi-virus-outline",
					"editableChildComponents": [
						"this"
					]
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/RTable.ts": {
		"date": 1656019451264,
		"jassijs_report.RTable": {
			"$ReportComponent": [
				{
					"fullPath": "report/Table",
					"icon": "mdi mdi-table-large",
					"editableChildComponents": [
						"this",
						"this.headerPanel",
						"this.bodyPanel",
						"this.footerPanel"
					]
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/RTableLayouts.ts": {
		"date": 1633113320000
	},
	"jassijs_report/RTablerow.ts": {
		"date": 1656019423044,
		"jassijs_report.RTablerow": {
			"$ReportComponent": [
				{
					"editableChildComponents": [
						"this"
					]
				}
			]
		}
	},
	"jassijs_report/RText.ts": {
		"date": 1656335831495,
		"jassijs_report.RText": {
			"$ReportComponent": [
				{
					"fullPath": "report/Text",
					"icon": "mdi mdi-format-color-text"
				}
			],
			"$Property": [
				{
					"name": "value",
					"type": "string",
					"description": "text"
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/RTextGroup.ts": {
		"date": 1656016375966,
		"jassijs_report.RTextGroup": {
			"$ReportComponent": [
				{
					"fullPath": "report/TextGroup",
					"icon": "mdi mdi-text-box-multiple-outline",
					"editableChildComponents": [
						"this"
					]
				}
			]
		}
	},
	"jassijs_report/RUList.ts": {
		"date": 1656016417389,
		"jassijs_report.RUList": {
			"$ReportComponent": [
				{
					"fullPath": "report/Unordered List",
					"icon": "mdi mdi-format-list-bulleted",
					"editableChildComponents": [
						"this"
					]
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/RUnknown.ts": {
		"date": 1656016429630,
		"jassijs_report.RUnknown": {}
	},
	"jassijs_report/SimpleReportEditor.ts": {
		"date": 1655637340626,
		"jassi_report.SimpleReportEditor": {}
	},
	"jassijs_report/StartReporteditor.ts": {
		"date": 1655760762456
	},
	"jassijs_report/TemplateReport.ts": {
		"date": 1656019402317,
		"jassijs_report.TemplateReport": {
			"$ActionProvider": [
				"jassijs.remote.FileNode"
			],
			"@members": {
				"newFile": {
					"$Action": [
						{
							"name": "New/Report",
							"isEnabled": "function"
						}
					]
				}
			}
		}
	},
	"jassijs_report/test/ClientReport.ts": {
		"date": 1656501727996,
		"jassijs_report.test.ClientReport": {
			"$Report": [
				{
					"name": "test/Sample Clientreport"
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/test/ServerReport.ts": {
		"date": 1656501737136,
		"jassijs_report.test.ServerReport": {
			"$Report": [
				{
					"name": "test/Sample Serverreport",
					"serverReportPath": "jassijs_report/TestServerreport"
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/Report.ts": {
		"date": 1656501701030,
		"jassijs_report.remote.Report": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"createActions": {
					"$Actions": []
				}
			}
		}
	},
	"jassijs_report/remote/ServerReport.ts": {
		"date": 1656331483222,
		"jassijs_report.remote.ServerReport": {}
	},
	"jassijs_report/Reports.ts": {
		"date": 1656501787077,
		"jassijs_report/Reports": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"show": {
					"$Action": [
						{
							"name": "Tools/Reports",
							"icon": "mdi mdi-chart-box-outline"
						}
					]
				}
			}
		}
	},
	"jassijs_report/ReportViewer.ts": {
		"date": 1656456334039,
		"jassijs_report/ReportViewer": {}
	}
}
 }
});