define("jassijs_reportdefinition/modul", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.default = {
        "require": {
            paths: {},
            shim: {}
        }
    };
});
//source from https://cdn.jsdelivr.net/npm/@types/pdfmake/interfaces.d.ts
// Type definitions for pdfmake 0.1
// Project: http://pdfmake.org
// Definitions by: Milen Stefanov <https://github.com/m1llen1um>
//                 Rajab Shakirov <https://github.com/radziksh>
//                 Enzo Volkmann <https://github.com/evolkmann>
//                 Andi Pätzold <https://github.com/andipaetzold>
//                 Neal Mummau <https://github.com/nmummau>
//                 Jean-Raphaël Matte <https://github.com/jeralm>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 3.0
//  changes by jassijs are tagged with /*changed by jassijs*/
/// <reference types="node" />
/// <reference types="pdfkit" />
define("jassijs_reportdefinition/pdfMake-interface", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
});
//this file is autogenerated don't modify
define("jassijs_reportdefinition/registry", ["require"], function (require) {
    return {
        default: {
            "jassijs_reportdefinition/modul.ts": {
                "date": 1655637506035
            },
            "jassijs_reportdefinition/pdfMake-interface.ts": {
                "date": 1655637557493
            },
            "jassijs_reportdefinition/ReportDesignGlobal.ts": {
                "date": 1655397712425
            }
        }
    };
});
//# sourceMappingURL=jassijs_reportdefinition.js.map