"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"jassijs/index.d.ts": {
		"date": 1681918736000
	},
	"jassijs/remote/Classes.ts": {
		"date": 1686759604000,
		"jassijs.remote.JassiError": {},
		"jassijs.remote.Classes": {}
	},
	"jassijs/remote/ClientError.ts": {
		"date": 1655556930000,
		"jassijs.remote.ClientError": {}
	},
	"jassijs/remote/Config.ts": {
		"date": 1719331708682.118
	},
	"jassijs/remote/Database.ts": {
		"date": 1655556796000,
		"jassijs.remote.Database": {}
	},
	"jassijs/remote/DatabaseTools.ts": {
		"date": 1681309882000,
		"jassijs.remote.DatabaseTools": {
			"@members": {
				"runSQL": {
					"ValidateFunctionParameter": []
				}
			}
		}
	},
	"jassijs/remote/DBArray.ts": {
		"date": 1655556796000,
		"jassijs.remote.DBArray": {}
	},
	"jassijs/remote/DBObject.ts": {
		"date": 1697209147073.5745,
		"jassijs.remote.DBObject": {}
	},
	"jassijs/remote/DBObjectQuery.ts": {
		"date": 1623876714000
	},
	"jassijs/remote/Extensions.ts": {
		"date": 1626209336000
	},
	"jassijs/remote/FileNode.ts": {
		"date": 1655556796000,
		"jassijs.remote.FileNode": {}
	},
	"jassijs/remote/hallo.ts": {
		"date": 1622985410000
	},
	"jassijs/remote/Jassi.ts": {
		"date": 1697209123749.7214
	},
	"jassijs/remote/JassijsGlobal.ts": {
		"date": 1655549782000
	},
	"jassijs/remote/Modules.ts": {
		"date": 1682799476000
	},
	"jassijs/remote/ObjectTransaction.ts": {
		"date": 1622985414000
	},
	"jassijs/remote/Registry.ts": {
		"date": 1697206758182.0095
	},
	"jassijs/remote/RemoteObject.ts": {
		"date": 1655556866000,
		"jassijs.remote.RemoteObject": {}
	},
	"jassijs/remote/RemoteProtocol.ts": {
		"date": 1655556796000,
		"jassijs.remote.RemoteProtocol": {}
	},
	"jassijs/remote/security/Group.ts": {
		"date": 1682888736000,
		"jassijs.security.Group": {
			"$DBObject": [
				{
					"name": "jassijs_group"
				}
			],
			"@members": {
				"id": {
					"ValidateIsInt": [
						{
							"optional": true
						}
					],
					"PrimaryColumn": []
				},
				"name": {
					"ValidateIsString": [],
					"Column": []
				},
				"parentRights": {
					"ValidateIsArray": [
						{
							"optional": true,
							"type": "function"
						}
					],
					"JoinTable": [],
					"ManyToMany": [
						"function",
						"function"
					]
				},
				"rights": {
					"ValidateIsArray": [
						{
							"optional": true,
							"type": "function"
						}
					],
					"JoinTable": [],
					"ManyToMany": [
						"function",
						"function"
					]
				},
				"users": {
					"ValidateIsArray": [
						{
							"optional": true,
							"type": "function"
						}
					],
					"ManyToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"jassijs/remote/security/ParentRight.ts": {
		"date": 1681581398000,
		"jassijs.security.ParentRight": {
			"$DBObject": [
				{
					"name": "jassijs_parentright"
				}
			],
			"@members": {
				"id": {
					"ValidateIsInt": [
						{
							"optional": true
						}
					],
					"PrimaryGeneratedColumn": []
				},
				"name": {
					"ValidateIsString": [],
					"Column": []
				},
				"classname": {
					"ValidateIsString": [],
					"Column": []
				},
				"i1": {
					"ValidateIsNumber": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"i2": {
					"ValidateIsNumber": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"s1": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"s2": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"groups": {
					"ValidateIsArray": [
						{
							"optional": true,
							"type": "function"
						}
					],
					"ManyToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"jassijs/remote/security/Right.ts": {
		"date": 1681322768000,
		"jassijs.security.Right": {
			"$DBObject": [
				{
					"name": "jassijs_right"
				}
			],
			"@members": {
				"id": {
					"ValidateIsInt": [
						{
							"optional": true
						}
					],
					"PrimaryColumn": []
				},
				"name": {
					"ValidateIsString": [],
					"Column": []
				},
				"groups": {
					"ValidateIsArray": [
						{
							"optional": true,
							"type": "function"
						}
					],
					"ManyToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"jassijs/remote/security/Rights.ts": {
		"date": 1655556796000,
		"jassijs.security.Rights": {}
	},
	"jassijs/remote/security/Setting.ts": {
		"date": 1681316436000,
		"jassijs.security.Setting": {
			"$DBObject": [
				{
					"name": "jassijs_setting"
				}
			],
			"@members": {
				"id": {
					"ValidateIsInt": [
						{
							"optional": true
						}
					],
					"PrimaryColumn": []
				},
				"data": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"jassijs/remote/security/User.ts": {
		"date": 1681329604000,
		"jassijs.security.User": {
			"$DBObject": [
				{
					"name": "jassijs_user"
				}
			],
			"@members": {
				"id": {
					"ValidateIsNumber": [
						{
							"optional": true
						}
					],
					"PrimaryGeneratedColumn": []
				},
				"email": {
					"ValidateIsString": [],
					"Column": []
				},
				"password": {
					"ValidateIsString": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"select": false
						}
					]
				},
				"groups": {
					"ValidateIsArray": [
						{
							"optional": true,
							"type": "function"
						}
					],
					"JoinTable": [],
					"ManyToMany": [
						"function",
						"function"
					]
				},
				"isAdmin": {
					"ValidateIsBoolean": [
						{
							"optional": true
						}
					],
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"jassijs/remote/Server.ts": {
		"date": 1695399507170.7808,
		"jassijs.remote.Server": {
			"@members": {
				"dir": {
					"ValidateFunctionParameter": []
				},
				"zip": {
					"ValidateFunctionParameter": []
				},
				"loadFiles": {
					"ValidateFunctionParameter": []
				},
				"loadFile": {
					"ValidateFunctionParameter": []
				},
				"saveFiles": {
					"ValidateFunctionParameter": []
				},
				"saveFile": {
					"ValidateFunctionParameter": []
				},
				"testServersideFile": {
					"ValidateFunctionParameter": []
				},
				"removeServerModul": {
					"ValidateFunctionParameter": []
				},
				"delete": {
					"ValidateFunctionParameter": []
				},
				"rename": {
					"ValidateFunctionParameter": []
				},
				"createFile": {
					"ValidateFunctionParameter": []
				},
				"createFolder": {
					"ValidateFunctionParameter": []
				},
				"createModule": {
					"ValidateFunctionParameter": []
				}
			}
		}
	},
	"jassijs/remote/Serverservice.ts": {
		"date": 1695999826188.6174
	},
	"jassijs/remote/Settings.ts": {
		"date": 1681315776000,
		"jassijs.remote.Settings": {
			"@members": {
				"remove": {
					"ValidateFunctionParameter": []
				},
				"save": {
					"ValidateFunctionParameter": []
				},
				"saveAll": {
					"ValidateFunctionParameter": []
				}
			}
		}
	},
	"jassijs/remote/Test.ts": {
		"date": 1655556930000,
		"jassijs.remote.Test": {}
	},
	"jassijs/remote/Transaction.ts": {
		"date": 1655556866000,
		"jassijs.remote.Transaction": {}
	},
	"jassijs/remote/Validator.ts": {
		"date": 1681322648000
	},
	"jassijs/server/Compile.ts": {
		"date": 1697213849686.3022
	},
	"jassijs/server/Cookies.ts": {
		"date": 1682364420000
	},
	"jassijs/server/CreatePackage.ts": {
		"date": 1682971612000
	},
	"jassijs/server/DatabaseSchema.ts": {
		"date": 1682241710000
	},
	"jassijs/server/DBManager.ts": {
		"date": 1697213352571.0527,
		"jassijs/server/DBManager": {
			"$Serverservice": [
				{
					"name": "db",
					"getInstance": "function"
				}
			]
		}
	},
	"jassijs/server/DBManagerExt.ts": {
		"date": 1682717756000
	},
	"jassijs/server/DoRemoteProtocol.ts": {
		"date": 1682362434000
	},
	"jassijs/server/ext/EmpyDeclaration.ts": {
		"date": 1682275348000
	},
	"jassijs/server/ext/jszip.ts": {
		"date": 1657714030000
	},
	"jassijs/server/Filesystem.ts": {
		"date": 1719332352671.4578,
		"jassijs.server.Filesystem": {
			"$Serverservice": [
				{
					"name": "filesystem",
					"getInstance": "function"
				}
			]
		}
	},
	"jassijs/server/FileTools.ts": {
		"date": 1697209029986.565
	},
	"jassijs/server/Indexer.ts": {
		"date": 1684515212000
	},
	"jassijs/server/JassiServer.ts": {
		"date": 1697208017035.5112
	},
	"jassijs/server/LocalProtocol.ts": {
		"date": 1697207752396.3682
	},
	"jassijs/server/NativeAdapter.ts": {
		"date": 1684173750000
	},
	"jassijs/server/PassportLoginRegister.ts": {
		"date": 1680946668000
	},
	"jassijs/server/PassportSetup.ts": {
		"date": 1680946688000
	},
	"jassijs/server/RawBody.ts": {
		"date": 1654195782000
	},
	"jassijs/server/RegistryIndexer.ts": {
		"date": 1682799792000
	},
	"jassijs/server/Reloader.ts": {
		"date": 1684435442000
	},
	"jassijs/server/Testuser.ts": {
		"date": 1655556794000,
		"Testuser": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"firstname": {
					"Column": []
				},
				"lastname": {
					"Column": []
				}
			}
		}
	},
	"jassijs/server/TypeORMListener.ts": {
		"date": 1697207709231.553,
		"jassijs.server.TypeORMListener": {
			"EventSubscriber": []
		}
	},
	"jassijs/server/UpdatePackage.ts": {
		"date": 1682701332000
	},
	"jassijs/server/Zip.ts": {
		"date": 1622984046000
	},
	"jassijs/UserModel.ts": {
		"date": 1622984046000
	},
	"jassijs/util/DatabaseSchema.ts": {
		"date": 1611490792000
	}
}