"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"jassijs/remote/Classes.ts": {
		"date": 1655556498000,
		"jassijs.remote.JassiError": {},
		"jassijs.remote.Classes": {}
	},
	"jassijs/remote/ClientError.ts": {
		"date": 1655556930000,
		"jassijs.remote.ClientError": {}
	},
	"jassijs/remote/Database.ts": {
		"date": 1655556796000,
		"jassijs.remote.Database": {}
	},
	"jassijs/remote/DatabaseTools.ts": {
		"date": 1680946799456,
		"jassijs.remote.DatabaseTools": {}
	},
	"jassijs/remote/DBArray.ts": {
		"date": 1655556796000,
		"jassijs.remote.DBArray": {}
	},
	"jassijs/remote/DBObject.ts": {
		"date": 1680809099251,
		"jassijs.remote.DBObject": {}
	},
	"jassijs/remote/DBObjectQuery.ts": {
		"date": 1623876714000
	},
	"jassijs/remote/Extensions.ts": {
		"date": 1626209336000
	},
	"jassijs/remote/FileNode.ts": {
		"date": 1655556796000,
		"jassijs.remote.FileNode": {}
	},
	"jassijs/remote/hallo.ts": {
		"date": 1622985410000
	},
	"jassijs/remote/Jassi.ts": {
		"date": 1655761748000
	},
	"jassijs/remote/JassijsGlobal.ts": {
		"date": 1655549782000
	},
	"jassijs/remote/ObjectTransaction.ts": {
		"date": 1622985414000
	},
	"jassijs/remote/Registry.ts": {
		"date": 1680975011688
	},
	"jassijs/remote/RemoteObject.ts": {
		"date": 1655556866000,
		"jassijs.remote.RemoteObject": {}
	},
	"jassijs/remote/RemoteProtocol.ts": {
		"date": 1655556796000,
		"jassijs.remote.RemoteProtocol": {}
	},
	"jassijs/remote/security/Group.ts": {
		"date": 1656072578000,
		"jassijs.security.Group": {
			"$DBObject": [
				{
					"name": "jassijs_group"
				}
			],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"name": {
					"Column": []
				},
				"parentRights": {
					"JoinTable": [],
					"ManyToMany": [
						"function",
						"function"
					]
				},
				"rights": {
					"JoinTable": [],
					"ManyToMany": [
						"function",
						"function"
					]
				},
				"users": {
					"ManyToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"jassijs/remote/security/ParentRight.ts": {
		"date": 1656072588000,
		"jassijs.security.ParentRight": {
			"$DBObject": [
				{
					"name": "jassijs_parentright"
				}
			],
			"@members": {
				"id": {
					"PrimaryGeneratedColumn": []
				},
				"name": {
					"Column": []
				},
				"classname": {
					"Column": []
				},
				"i1": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"i2": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"s1": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"s2": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"groups": {
					"ManyToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"jassijs/remote/security/Right.ts": {
		"date": 1656072608000,
		"jassijs.security.Right": {
			"$DBObject": [
				{
					"name": "jassijs_right"
				}
			],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"name": {
					"Column": []
				},
				"groups": {
					"ManyToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"jassijs/remote/security/Rights.ts": {
		"date": 1655556796000,
		"jassijs.security.Rights": {}
	},
	"jassijs/remote/security/Setting.ts": {
		"date": 1656072620000,
		"jassijs.security.Setting": {
			"$DBObject": [
				{
					"name": "jassijs_setting"
				}
			],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"data": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"jassijs/remote/security/User.ts": {
		"date": 1656072626000,
		"jassijs.security.User": {
			"$DBObject": [
				{
					"name": "jassijs_user"
				}
			],
			"@members": {
				"id": {
					"PrimaryGeneratedColumn": []
				},
				"email": {
					"Column": []
				},
				"password": {
					"Column": [
						{
							"select": false
						}
					]
				},
				"groups": {
					"JoinTable": [],
					"ManyToMany": [
						"function",
						"function"
					]
				},
				"isAdmin": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"jassijs/remote/Settings.ts": {
		"date": 1680946807085,
		"jassijs.remote.Settings": {}
	},
	"jassijs/remote/Test.ts": {
		"date": 1655556930000,
		"jassijs.remote.Test": {}
	},
	"jassijs/remote/Transaction.ts": {
		"date": 1655556866000,
		"jassijs.remote.Transaction": {}
	},
	"jassijs/server/Compile.ts": {
		"date": 1680803766537
	},
	"jassijs/server/DBManager.ts": {
		"date": 1680982331732,
		"jassijs/server/DBManager": {
			"$Serverservice": [
				{
					"name": "db",
					"getInstance": "function"
				}
			]
		}
	},
	"jassijs/server/DoRemoteProtocol.ts": {
		"date": 1680946638753
	},
	"jassijs/server/Filesystem.ts": {
		"date": 1680946644898,
		"jassijs.server.Filesystem": {
			"$Serverservice": [
				{
					"name": "filesystem",
					"getInstance": "function"
				}
			]
		}
	},
	"jassijs/server/Indexer.ts": {
		"date": 1680806099946
	},
	"jassijs/server/JassiServer.ts": {
		"date": 1680722219857
	},
	"jassijs/server/PassportLoginRegister.ts": {
		"date": 1680946666516
	},
	"jassijs/server/PassportSetup.ts": {
		"date": 1680946687665
	},
	"jassijs/server/RawBody.ts": {
		"date": 1654195782000
	},
	"jassijs/server/RegistryIndexer.ts": {
		"date": 1680805467362
	},
	"jassijs/server/Zip.ts": {
		"date": 1622984046000
	},
	"jassijs/UserModel.ts": {
		"date": 1622984046000
	},
	"jassijs/util/DatabaseSchema.ts": {
		"date": 1611490792000
	},
	"jassijs/remote/Validator.ts": {
		"date": 1680723591109
	},
	"jassijs/remote/Server.ts": {
		"date": 1680948998750,
		"jassijs.remote.Server": {}
	},
	"jassijs/remote/Serverservice.ts": {
		"date": 1680954695071
	}
}