"use strict:";
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "jassijs/remote/Classes.ts": {
        "date": 1655556498000,
        "jassijs.remote.JassiError": {},
        "jassijs.remote.Classes": {}
    },
    "jassijs/remote/ClientError.ts": {
        "date": 1655556930000,
        "jassijs.remote.ClientError": {}
    },
    "jassijs/remote/Database.ts": {
        "date": 1655556796000,
        "jassijs.remote.Database": {}
    },
    "jassijs/remote/DatabaseTools.ts": {
        "date": 1681309880654,
        "jassijs.remote.DatabaseTools": {
            "@members": {
                "runSQL": {
                    "ValidateFunctionParameter": []
                }
            }
        }
    },
    "jassijs/remote/DBArray.ts": {
        "date": 1655556796000,
        "jassijs.remote.DBArray": {}
    },
    "jassijs/remote/DBObject.ts": {
        "date": 1681317354018,
        "jassijs.remote.DBObject": {}
    },
    "jassijs/remote/DBObjectQuery.ts": {
        "date": 1623876714000
    },
    "jassijs/remote/Extensions.ts": {
        "date": 1626209336000
    },
    "jassijs/remote/FileNode.ts": {
        "date": 1655556796000,
        "jassijs.remote.FileNode": {}
    },
    "jassijs/remote/hallo.ts": {
        "date": 1622985410000
    },
    "jassijs/remote/Jassi.ts": {
        "date": 1681571354352
    },
    "jassijs/remote/JassijsGlobal.ts": {
        "date": 1655549782000
    },
    "jassijs/remote/ObjectTransaction.ts": {
        "date": 1622985414000
    },
    "jassijs/remote/Registry.ts": {
        "date": 1682363039551
    },
    "jassijs/remote/RemoteObject.ts": {
        "date": 1655556866000,
        "jassijs.remote.RemoteObject": {}
    },
    "jassijs/remote/RemoteProtocol.ts": {
        "date": 1655556796000,
        "jassijs.remote.RemoteProtocol": {}
    },
    "jassijs/remote/security/Group.ts": {
        "date": 1681322755237,
        "jassijs.security.Group": {
            "$DBObject": [
                {
                    "name": "jassijs_group"
                }
            ],
            "@members": {
                "id": {
                    "ValidateIsInt": [
                        {
                            "optional": true
                        }
                    ],
                    "PrimaryColumn": []
                },
                "name": {
                    "ValidateIsString": [],
                    "Column": []
                },
                "parentRights": {
                    "ValidateIsArray": [
                        {
                            "optional": true,
                            "type": "function"
                        }
                    ],
                    "JoinTable": [],
                    "ManyToMany": [
                        "function",
                        "function"
                    ]
                },
                "rights": {
                    "ValidateIsArray": [
                        {
                            "optional": true,
                            "type": "function"
                        }
                    ],
                    "JoinTable": [],
                    "ManyToMany": [
                        "function",
                        "function"
                    ]
                },
                "users": {
                    "ValidateIsArray": [
                        {
                            "optional": true,
                            "type": "function"
                        }
                    ],
                    "ManyToMany": [
                        "function",
                        "function"
                    ]
                }
            }
        }
    },
    "jassijs/remote/security/ParentRight.ts": {
        "date": 1681581396308,
        "jassijs.security.ParentRight": {
            "$DBObject": [
                {
                    "name": "jassijs_parentright"
                }
            ],
            "@members": {
                "id": {
                    "ValidateIsInt": [
                        {
                            "optional": true
                        }
                    ],
                    "PrimaryGeneratedColumn": []
                },
                "name": {
                    "ValidateIsString": [],
                    "Column": []
                },
                "classname": {
                    "ValidateIsString": [],
                    "Column": []
                },
                "i1": {
                    "ValidateIsNumber": [
                        {
                            "optional": true
                        }
                    ],
                    "Column": [
                        {
                            "nullable": true
                        }
                    ]
                },
                "i2": {
                    "ValidateIsNumber": [
                        {
                            "optional": true
                        }
                    ],
                    "Column": [
                        {
                            "nullable": true
                        }
                    ]
                },
                "s1": {
                    "ValidateIsString": [
                        {
                            "optional": true
                        }
                    ],
                    "Column": [
                        {
                            "nullable": true
                        }
                    ]
                },
                "s2": {
                    "ValidateIsString": [
                        {
                            "optional": true
                        }
                    ],
                    "Column": [
                        {
                            "nullable": true
                        }
                    ]
                },
                "groups": {
                    "ValidateIsArray": [
                        {
                            "optional": true,
                            "type": "function"
                        }
                    ],
                    "ManyToMany": [
                        "function",
                        "function"
                    ]
                }
            }
        }
    },
    "jassijs/remote/security/Right.ts": {
        "date": 1681322767135,
        "jassijs.security.Right": {
            "$DBObject": [
                {
                    "name": "jassijs_right"
                }
            ],
            "@members": {
                "id": {
                    "ValidateIsInt": [
                        {
                            "optional": true
                        }
                    ],
                    "PrimaryColumn": []
                },
                "name": {
                    "ValidateIsString": [],
                    "Column": []
                },
                "groups": {
                    "ValidateIsArray": [
                        {
                            "optional": true,
                            "type": "function"
                        }
                    ],
                    "ManyToMany": [
                        "function",
                        "function"
                    ]
                }
            }
        }
    },
    "jassijs/remote/security/Rights.ts": {
        "date": 1655556796000,
        "jassijs.security.Rights": {}
    },
    "jassijs/remote/security/Setting.ts": {
        "date": 1681316435162,
        "jassijs.security.Setting": {
            "$DBObject": [
                {
                    "name": "jassijs_setting"
                }
            ],
            "@members": {
                "id": {
                    "ValidateIsInt": [
                        {
                            "optional": true
                        }
                    ],
                    "PrimaryColumn": []
                },
                "data": {
                    "ValidateIsString": [
                        {
                            "optional": true
                        }
                    ],
                    "Column": [
                        {
                            "nullable": true
                        }
                    ]
                }
            }
        }
    },
    "jassijs/remote/security/User.ts": {
        "date": 1681329602964,
        "jassijs.security.User": {
            "$DBObject": [
                {
                    "name": "jassijs_user"
                }
            ],
            "@members": {
                "id": {
                    "ValidateIsNumber": [
                        {
                            "optional": true
                        }
                    ],
                    "PrimaryGeneratedColumn": []
                },
                "email": {
                    "ValidateIsString": [],
                    "Column": []
                },
                "password": {
                    "ValidateIsString": [
                        {
                            "optional": true
                        }
                    ],
                    "Column": [
                        {
                            "select": false
                        }
                    ]
                },
                "groups": {
                    "ValidateIsArray": [
                        {
                            "optional": true,
                            "type": "function"
                        }
                    ],
                    "JoinTable": [],
                    "ManyToMany": [
                        "function",
                        "function"
                    ]
                },
                "isAdmin": {
                    "ValidateIsBoolean": [
                        {
                            "optional": true
                        }
                    ],
                    "Column": [
                        {
                            "nullable": true
                        }
                    ]
                }
            }
        }
    },
    "jassijs/remote/Settings.ts": {
        "date": 1681315774171,
        "jassijs.remote.Settings": {
            "@members": {
                "remove": {
                    "ValidateFunctionParameter": []
                },
                "save": {
                    "ValidateFunctionParameter": []
                },
                "saveAll": {
                    "ValidateFunctionParameter": []
                }
            }
        }
    },
    "jassijs/remote/Test.ts": {
        "date": 1655556930000,
        "jassijs.remote.Test": {}
    },
    "jassijs/remote/Transaction.ts": {
        "date": 1655556866000,
        "jassijs.remote.Transaction": {}
    },
    "jassijs/server/Compile.ts": {
        "date": 1682283699017
    },
    "jassijs/server/DBManager.ts": {
        "date": 1682591475311,
        "jassijs/server/DBManager": {
            "$Serverservice": [
                {
                    "name": "db",
                    "getInstance": "function"
                }
            ]
        }
    },
    "jassijs/server/DoRemoteProtocol.ts": {
        "date": 1682362433280
    },
    "jassijs/server/Filesystem.ts": {
        "date": 1682591314622,
        "jassijs.server.Filesystem": {
            "$Serverservice": [
                {
                    "name": "filesystem",
                    "getInstance": "function"
                }
            ]
        }
    },
    "jassijs/server/Indexer.ts": {
        "date": 1680806099946
    },
    "jassijs/server/JassiServer.ts": {
        "date": 1682449512016
    },
    "jassijs/server/PassportLoginRegister.ts": {
        "date": 1680946666516
    },
    "jassijs/server/PassportSetup.ts": {
        "date": 1680946687665
    },
    "jassijs/server/RawBody.ts": {
        "date": 1654195782000
    },
    "jassijs/server/RegistryIndexer.ts": {
        "date": 1681930917452
    },
    "jassijs/server/Zip.ts": {
        "date": 1622984046000
    },
    "jassijs/UserModel.ts": {
        "date": 1622984046000
    },
    "jassijs/util/DatabaseSchema.ts": {
        "date": 1611490792000
    },
    "jassijs/remote/Validator.ts": {
        "date": 1681322647268
    },
    "jassijs/remote/Server.ts": {
        "date": 1682513195150,
        "jassijs.remote.Server": {
            "@members": {
                "dir": {
                    "ValidateFunctionParameter": []
                },
                "zip": {
                    "ValidateFunctionParameter": []
                },
                "loadFiles": {
                    "ValidateFunctionParameter": []
                },
                "loadFile": {
                    "ValidateFunctionParameter": []
                },
                "saveFiles": {
                    "ValidateFunctionParameter": []
                },
                "saveFile": {
                    "ValidateFunctionParameter": []
                },
                "testServersideFile": {
                    "ValidateFunctionParameter": []
                },
                "removeServerModul": {
                    "ValidateFunctionParameter": []
                },
                "delete": {
                    "ValidateFunctionParameter": []
                },
                "rename": {
                    "ValidateFunctionParameter": []
                },
                "createFile": {
                    "ValidateFunctionParameter": []
                },
                "createFolder": {
                    "ValidateFunctionParameter": []
                },
                "createModule": {
                    "ValidateFunctionParameter": []
                }
            }
        }
    },
    "jassijs/remote/Serverservice.ts": {
        "date": 1682277848397
    },
    "jassijs/index.d.ts": {
        "date": 1681918735845
    },
    "jassijs/server/UpdatePackage.ts": {
        "date": 1682167521365
    },
    "jassijs/remote/Config.ts": {
        "date": 1682361522060
    },
    "jassijs/server/NativeAdapter.ts": {
        "date": 1682517569027
    },
    "jassijs/server/FileTools.ts": {
        "date": 1682591534994
    }
};
//# sourceMappingURL=registry.js.map