import { $Class } from "jassijs/remote/Registry";
import { $Property } from "jassijs/ui/Property";
import { $ActionProvider, $Action } from "jassijs/base/Actions";
import { DBObject } from "jassijs/remote/DBObject";
import { FileNode } from "jassijs/remote/FileNode";
import { OptionDialog } from "jassijs/ui/OptionDialog";
import { classes } from "jassijs/remote/Classes";
import registry from "jassijs/remote/Registry";
import { FileActions } from "jassijs/ui/FileExplorer";
import { TemplateDBDialog } from "jassijs/template/TemplateDBDialog";

var code=`import {DBObject, $DBObject } from "jassijs/remote/DBObject";
import { $Class } from "jassijs/remote/Registry";
import { Entity, PrimaryColumn, Column, OneToOne, ManyToMany, ManyToOne, OneToMany,JoinColumn,JoinTable } from "jassijs/util/DatabaseSchema";
import { $DBObjectQuery } from "jassijs/remote/DBObjectQuery";


@$DBObject()
@$Class("{{fullclassname}}")

export class {{classname}} extends DBObject {

    {{PrimaryAnnotator}}
    declare id: number;
  
    constructor() {
        super();
    }
}


export async function test() {
};`;

@$Class("jassijs.template.TemplateDBObjectProperties")
export class TemplateDBObjectProperties {
	@$Property({decription:"name of the db class"})
	name:string;
	@$Property({default:"true",description:"the primary column alue will be automatically generated with an auto-increment value"})
    autogeneratedid:string;
}
@$ActionProvider("jassijs.remote.FileNode")
@$Class("jassijs.template.TemplateDBObject")
export class TemplateDBObject {
	static code:string=code;
    @$Action({
        name: "New/DBObject",
        isEnabled: function(all: FileNode[]): boolean {
            return all[0].isDirectory()&&all[0].fullpath.indexOf("/remote/")!==-1;
        }
    })
    static async newFile(all: FileNode[]) {
		var props=new TemplateDBObjectProperties();
        var res = await OptionDialog.askProperties("Create Database Class:",props, ["ok", "cancel"],undefined,false);
        if (res.button === "ok" ) {
	    	var scode=TemplateDBObject.code.replaceAll("{{fullclassname}}",all[0].fullpath+"/"+props.name);
	    	scode=scode.replaceAll("{{classname}}",props.name);
	    	var anno="@PrimaryColumn()";
	    	if(props.autogeneratedid)
	    		 anno="@PrimaryGeneratedColumn()";
	    	scode=scode.replaceAll("{{PrimaryAnnotator}}",anno);

	    	FileActions .newFile(all,props.name+".ts",scode,true);
        }
    }
}


