//this file is autogenerated don't modify
define("tg/registry", ["require"], function (require) {
    return {
        default: {
            "tg/remote/MyRemoteObject.ts": {
                "date": 1622999304732,
                "tg/remote/MyRemoteObject": {}
            },
            "tg/remote/Person.ts": {
                "date": 1622999405219,
                "tg.Person": {
                    "$DBObject": []
                }
            }
        }
    };
});
//# sourceMappingURL=registry.js.map