//this file is autogenerated don't modify
define("tg/registry",["require"], function(require) {
 return {
  default: {
	"tg/remote/MyRemoteObject.ts": {
		"date": 1622922501315,
		"tg/remote/MyRemoteObject": {}
	}
}
 }
});