"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"jassijs_report/remote/pdfmakejassi.ts": {
		"date": 1634336644000
	},
	"jassijs_report/remote/RComponent.ts": {
		"date": 1656016830000,
		"jassijs_report.ReportComponent": {
			"$Property": [
				{
					"hideBaseClassProperties": true
				}
			],
			"@members": {}
		}
	},
	"jassijs_report/TestServerreport.ts": {
		"date": 1656367820000
	},
	"jassijs_report/remote/ServerReport.ts": {
		"date": 1656331484000,
		"jassijs_report.remote.ServerReport": {}
	},
	"jassijs_report/DoServerreport.ts": {
		"date": 1656365932000
	}
}