//this file is autogenerated don't modify
define("testrmodul/registry",["require"], function(require) {
 return {
  default: {
	"testrmodul/remote/TestRModul.ts": {
		"date": 1681323085306,
		"testrmodul.remote.TestRModul": {}
	},
	"testrmodul/remote/TestRCustomer.ts": {
		"date": 1681323092645,
		"testrmodul.TestRCustomer": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"name": {
					"Column": []
				}
			}
		}
	}
}
 }
});