//this file is autogenerated don't modify
define("testrmodul/registry", ["require"], function (require) {
    return {
        default: {
            "testrmodul/remote/TestRModul.ts": {
                "date": 1655459935291,
                "testrmodul.remote.TestRModul": {}
            }
        }
    };
});
//# sourceMappingURL=registry.js.map