//this file is autogenerated don't modify
define("jassi_localserver/registry", ["require"], function (require) {
    return {
        default: {
            "jassi_localserver/DatabaseSchema.ts": {
                "date": 1614290342083
            },
            "jassi_localserver/DBManager.ts": {
                "date": 1614469272935
            },
            "jassi_localserver/Filesystem.ts": {
                "date": 1614962437159,
                "jassi_localserver.Filessystem": {}
            },
            "jassi_localserver/Indexer.ts": {
                "date": 1614893991197
            },
            "jassi_localserver/LocalProtocol.ts": {
                "date": 1614963126042
            },
            "jassi_localserver/modul.ts": {
                "date": 1614785819884
            },
            "jassi_localserver/RegistyIndexer.ts": {
                "date": 1614891745582,
                "jassi_localserver.RegistryIndexer": {}
            },
            "jassi_localserver/Testserver.ts": {
                "date": 1614365026599,
                "jassi_localserver.Testserver": {}
            },
            "jassi_localserver/Testuser.ts": {
                "date": 1614289287180,
                "Testuser": {
                    "$DBObject": []
                }
            },
            "jassi_localserver/TypeORMListener.ts": {
                "date": 1614891650187,
                "jassi_localserver/TypeORMListener": {
                    "EventSubscriber": []
                }
            }
        }
    };
});
//# sourceMappingURL=registry.js.map