//this file is autogenerated don't modify
define("jassi_localserver/registry", ["require"], function (require) {
    return {
        default: {
            "jassi_localserver/DatabaseSchema.ts": {
                "date": 1618335240687
            },
            "jassi_localserver/DBManager.ts": {
                "date": 1618330522544,
                "jassi_localserver.DBManager": {}
            },
            "jassi_localserver/Filesystem.ts": {
                "date": 1615320036255,
                "jassi_localserver.Filessystem": {}
            },
            "jassi_localserver/Indexer.ts": {
                "date": 1614893991197
            },
            "jassi_localserver/LocalProtocol.ts": {
                "date": 1615324690490
            },
            "jassi_localserver/modul.ts": {
                "date": 1615410135735
            },
            "jassi_localserver/RegistryIndexer.ts": {
                "date": 1615986957521,
                "jassi_localserver.RegistryIndexer": {}
            },
            "jassi_localserver/Testserver.ts": {
                "date": 1614365026599,
                "jassi_localserver.Testserver": {}
            },
            "jassi_localserver/Testuser.ts": {
                "date": 1614289287180,
                "Testuser": {
                    "$DBObject": []
                }
            },
            "jassi_localserver/TypeORMListener.ts": {
                "date": 1615320659610,
                "jassi_localserver.TypeORMListener": {
                    "EventSubscriber": []
                }
            }
        }
    };
});
//# sourceMappingURL=registry.js.map