//this file is autogenerated don't modify
define("jassijs_localserver/registry",["require"], function(require) {
 return {
  default: {
	"jassijs_localserver/DatabaseSchema.ts": {
		"date": 1622984213677
	},
	"jassijs_localserver/DBManager.ts": {
		"date": 1624103920275,
		"jassi_localserver.DBManager": {}
	},
	"jassijs_localserver/Filesystem.ts": {
		"date": 1624107072713,
		"jassijs_localserver.Filessystem": {}
	},
	"jassijs_localserver/Indexer.ts": {
		"date": 1624131940284
	},
	"jassijs_localserver/LocalProtocol.ts": {
		"date": 1624105941572
	},
	"jassijs_localserver/modul.ts": {
		"date": 1622998474045
	},
	"jassijs_localserver/RegistryIndexer.ts": {
		"date": 1624131740939,
		"jassijs_localserver.RegistryIndexer": {}
	},
	"jassijs_localserver/Testuser.ts": {
		"date": 1622984213666,
		"Testuser": {
			"$DBObject": []
		}
	},
	"jassijs_localserver/TypeORMListener.ts": {
		"date": 1622998616949,
		"jassijs_localserver.TypeORMListener": {
			"EventSubscriber": []
		}
	}
}
 }
});