//this file is autogenerated don't modify
define("jassijs_report/registry", ["require"], function (require) {
    return {
        default: {
            "jassijs_report/designer/ReportDesigner.ts": {
                "date": 1699287545054.5315,
                "jassijs_report.designer.ReportDesigner": {}
            },
            "jassijs_report/designer/SimpleReportDesigner.ts": {
                "date": 1655556794000,
                "jassijs_report.designer.SimpleReportDesigner": {}
            },
            "jassijs_report/ext/pdfjs.ts": {
                "date": 1657714200000
            },
            "jassijs_report/ext/pdfmake.ts": {
                "date": 1657714352000
            },
            "jassijs_report/modul.ts": {
                "date": 1655329710000
            },
            "jassijs_report/pdfMake-interface.ts": {
                "date": 1681513962000
            },
            "jassijs_report/PDFReport.ts": {
                "date": 1655556866000,
                "jassijs_report.PDFReport": {}
            },
            "jassijs_report/PDFViewer.ts": {
                "date": 1719589039108.462,
                "jassijs_report.PDFViewer": {}
            },
            "jassijs_report/RColumns.ts": {
                "date": 1721763160019.909,
                "jassijs_report.RColumns": {
                    "$ReportComponent": [
                        {
                            "fullPath": "report/Columns",
                            "icon": "mdi mdi-view-parallel-outline",
                            "editableChildComponents": [
                                "this"
                            ]
                        }
                    ]
                }
            },
            "jassijs_report/RComponent.ts": {
                "date": 1699203219964.0005,
                "jassijs_report.RComponent": {
                    "$Property": [
                        {
                            "hideBaseClassProperties": true
                        }
                    ],
                    "@members": {}
                }
            },
            "jassijs_report/RDatatable.ts": {
                "date": 1655930956000,
                "jassijs_report.RDatatable": {
                    "$ReportComponent": [
                        {
                            "fullPath": "report/Datatable",
                            "icon": "mdi mdi-table-cog",
                            "editableChildComponents": [
                                "this",
                                "this.headerPanel",
                                "this.bodyPanel",
                                "this.footerPanel"
                            ]
                        }
                    ],
                    "@members": {}
                }
            },
            "jassijs_report/remote/pdfmakejassi.ts": {
                "date": 1634336644000
            },
            "jassijs_report/remote/ServerReport.ts": {
                "date": 1684441134000,
                "jassijs_report.remote.ServerReport": {
                    "@members": {
                        "getDesign": {
                            "ValidateFunctionParameter": []
                        },
                        "getBase64": {
                            "ValidateFunctionParameter": []
                        }
                    }
                }
            },
            "jassijs_report/Report.ts": {
                "date": 1656501702000,
                "jassijs_report.remote.Report": {
                    "$ActionProvider": [
                        "jassijs.base.ActionNode"
                    ],
                    "@members": {
                        "createActions": {
                            "$Actions": []
                        }
                    }
                }
            },
            "jassijs_report/ReportDesign.ts": {
                "date": 1721763173671.8528,
                "jassijs_report.InfoProperties": {
                    "@members": {}
                },
                "jassijs_report.PermissionProperties": {
                    "@members": {}
                },
                "jassijs_report.StyleContainer": {
                    "$Property": [
                        {
                            "hideBaseClassProperties": true
                        }
                    ]
                },
                "jassijs_report.ReportDesign": {
                    "$ReportComponent": [
                        {
                            "fullPath": "undefined",
                            "icon": "undefined",
                            "editableChildComponents": [
                                "this",
                                "this.backgroundPanel",
                                "this.headerPanel",
                                "this.contentPanel",
                                "this.footerPanel"
                            ]
                        }
                    ],
                    "$Property": [
                        {
                            "hideBaseClassProperties": true
                        }
                    ],
                    "@members": {}
                }
            },
            "jassijs_report/ReportDesignGlobal.ts": {
                "date": 1655397714000
            },
            "jassijs_report/Reports.ts": {
                "date": 1657978946000,
                "jassijs_report/Reports": {
                    "$ActionProvider": [
                        "jassijs.base.ActionNode"
                    ],
                    "@members": {
                        "show": {
                            "$Action": [
                                {
                                    "name": "Tools/Reports",
                                    "icon": "mdi mdi-chart-box-outline"
                                }
                            ]
                        }
                    }
                }
            },
            "jassijs_report/ReportViewer.ts": {
                "date": 1681571042000,
                "jassijs_report/ReportViewer": {}
            },
            "jassijs_report/RGroupTablerow.ts": {
                "date": 1699111120748.0674,
                "jassijs_report.RTablerow": {
                    "@members": {}
                }
            },
            "jassijs_report/RImage.ts": {
                "date": 1719588998709.0293,
                "jassijs_report.RImage": {
                    "$ReportComponent": [
                        {
                            "fullPath": "report/Image",
                            "icon": "mdi mdi-image-frame"
                        }
                    ],
                    "@members": {}
                }
            },
            "jassijs_report/RImageEditor.ts": {
                "date": 1656017314000,
                "jassi_report/RImagePropertyEditor": {
                    "$PropertyEditor": [
                        [
                            "rimage"
                        ]
                    ]
                }
            },
            "jassijs_report/ROList.ts": {
                "date": 1721763181480.2773,
                "jassijs_report.ROList": {
                    "$ReportComponent": [
                        {
                            "fullPath": "report/Ordered List",
                            "icon": "mdi mdi-format-list-numbered",
                            "editable