"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"testrmodul/remote/TestRModul.ts": {
		"date": 1655459935291,
		"testrmodul.remote.TestRModul": {}
	}
}