"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"testrmodul/remote/TestRModul.ts": {
		"date": 1627586549322,
		"testrmodul.remote.TestRModul": {}
	},
	"testrmodul/remote/TestRCustomer.ts": {
		"date": 1627586551813,
		"testrmodul.TestRCustomer": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"name": {
					"Column": []
				}
			}
		}
	}
}