//this file is autogenerated dont modify
define("jassi_report/registry", ["require"], function (require) {
    return {
        default: {
            "jassi_report/designer/Report.ts": {
                "date": 1611936363493,
                "jassi_report.Report": {}
            },
            "jassi_report/designer/ReportDesigner.ts": {
                "date": 1613165872074,
                "jassi_report.designer.ReportDesigner": {}
            },
            "jassi_report/modul.ts": {
                "date": 1613156079114
            },
            "jassi_report/PDFReport.ts": {
                "date": 1613165819524,
                "jassi_report.PDFReport": {}
            },
            "jassi_report/PDFViewer.ts": {
                "date": 1613148644258,
                "jassi_report.PDFViewer": {}
            },
            "jassi_report/RColumns.ts": {
                "date": 1612389719738,
                "jassi_report.RColumns": {
                    "$ReportComponent": [
                        {
                            "fullPath": "report/Columns",
                            "icon": "mdi mdi-view-parallel-outline",
                            "editableChildComponents": [
                                "this"
                            ]
                        }
                    ],
                    "$Property": [
                        {
                            "hideBaseClassProperties": true
                        }
                    ]
                }
            },
            "jassi_report/RComponent.ts": {
                "date": 1611935803813
            },
            "jassi_report/RDatatable.ts": {
                "date": 1613165810874,
                "jassi_report.RDatatable": {
                    "$ReportComponent": [
                        {
                            "fullPath": "report/Datatable",
                            "icon": "mdi mdi-file-table-box-multiple-outline",
                            "editableChildComponents": [
                                "this",
                                "this.headerPanel",
                                "this.bodyPanel",
                                "this.footerPanel"
                            ]
                        }
                    ]
                }
            },
            "jassi_report/ReportComponent.ts": {
                "date": 1612890169107,
                "jassi_report.ReportComponent": {
                    "$Property": [
                        {
                            "hideBaseClassProperties": true
                        }
                    ]
                }
            },
            "jassi_report/ReportComponentProperties.ts.ts": {
                "date": 1611935804327
            },
            "jassi_report/ReportDesign.ts": {
                "date": 1613165094773,
                "jassi_report.InfoProperties": {},
                "jassi_report.PermissionProperties": {},
                "jassi_report.ReportDesign": {
                    "$ReportComponent": [
                        {
                            "fullPath": "undefined",
                            "icon": "undefined",
                            "editableChildComponents": [
                                "this",
                                "this.backgroundPanel",
                                "this.headerPanel",
                                "this.contentPanel",
                                "this.footerPanel"
                            ]
                        }
                    ]
                }
            },
            "jassi_report/ReportEditor.ts": {
                "date": 1613165800855,
                "jassi_report.ReportEditor": {}
            },
            "jassi_report/RStack.ts": {
                "date": 1612389843337,
                "jassi_report.RStack": {
                    "$ReportComponent": [
                        {
                            "fullPath": "report/Stack",
                            "icon": "mdi mdi-view-sequential-outline",
                            "editableChildComponents": [
                                "this"
                            ]
                        }
                    ]
                }
            },
            "jassi_report/RTablerow.ts": {
                "date": 1611936363493,
                "jassi_report.RTablerow": {
                    "$ReportComponent": [
                        {
                            "editableChildComponents": [
                                "this"
                            ]
                        }
                    ]
                }
            },
            "jassi_report/RText.ts": {
                "date": 1613165109709,
                "jassi_report.RText": {
                    "$ReportComponent": [
                        {
                            "fullPath": "report/Text",
                            "icon": "mdi mdi-format-color-text"
                        }
                    ],
                    "$Property": [
                        {
                            "name": "value",
                            "type": "string",
                            "description": "text"
                        }
                    ]
                }
            },
            "jassi_report/RUnknown.ts": {
                "date": 1612890208427,
                "jassi_report.RUnknown": {}
            }
        }
    };
});
//# sourceMappingURL=registry.js.map