//this file is autogenerated don't modify
define("jassijs/registry",["require"], function(require) {
 return {
  default: {
	"jassijs/base/ActionNode.ts": {
		"date": 1627916874000,
		"jassijs.base.ActionNode": {}
	},
	"jassijs/base/Actions.ts": {
		"date": 1633978962000,
		"jassijs.base.Actions": {}
	},
	"jassijs/base/DatabaseSchema.ts": {
		"date": 1630961318000,
		"jassijs.base.DatabaseSchema": {}
	},
	"jassijs/base/Errors.ts": {
		"date": 1623094944000
	},
	"jassijs/base/Extensions.ts": {
		"date": 1622985782000
	},
	"jassijs/base/LoginDialog.ts": {
		"date": 1623093222000
	},
	"jassijs/base/PropertyEditorService.ts": {
		"date": 1633125786000,
		"jassijs.base.PropertyEditorService": {}
	},
	"jassijs/base/Router.ts": {
		"date": 1622985640000,
		"jassijs.base.Router": {}
	},
	"jassijs/base/Tests.ts": {
		"date": 1654466268524,
		"jassijs.ui.TestAction": {
			"$ActionProvider": [
				"jassijs.remote.FileNode"
			],
			"@members": {
				"testNode": {
					"$Action": [
						{
							"name": "Run Tests"
						}
					]
				}
			}
		}
	},
	"jassijs/base/Windows.ts": {
		"date": 1622985640000,
		"jassijs.base.Windows": {}
	},
	"jassijs/jassi.ts": {
		"date": 1622985802000
	},
	"jassijs/modul.ts": {
		"date": 1654017492691
	},
	"jassijs/remote/Classes.ts": {
		"date": 1624296520000,
		"jassijs.remote.JassiError": {},
		"jassijs.remote.Classes": {}
	},
	"jassijs/remote/ClientError.ts": {
		"date": 1624295334000,
		"jassijs.remote.ClientError": {}
	},
	"jassijs/remote/Database.ts": {
		"date": 1622985396000,
		"jassijs.remote.Database": {}
	},
	"jassijs/remote/DatabaseTools.ts": {
		"date": 1624296508000,
		"jassijs.remote.DatabaseTools": {}
	},
	"jassijs/remote/DBArray.ts": {
		"date": 1624295776000,
		"jassijs.remote.DBArray": {}
	},
	"jassijs/remote/DBObject.ts": {
		"date": 1624295826000,
		"jassijs.remote.DBObject": {}
	},
	"jassijs/remote/DBObjectQuery.ts": {
		"date": 1623876714000
	},
	"jassijs/remote/Extensions.ts": {
		"date": 1626209336000
	},
	"jassijs/remote/FileNode.ts": {
		"date": 1623779782000,
		"jassijs.remote.FileNode": {}
	},
	"jassijs/remote/hallo.ts": {
		"date": 1622985410000
	},
	"jassijs/remote/Jassi.ts": {
		"date": 1634389646000,
		"jassijs.remote.Jassi": {}
	},
	"jassijs/remote/ObjectTransaction.ts": {
		"date": 1622985414000
	},
	"jassijs/remote/Registry.ts": {
		"date": 1634384712000
	},
	"jassijs/remote/RemoteObject.ts": {
		"date": 1627600804000,
		"jassijs.remote.RemoteObject": {}
	},
	"jassijs/remote/RemoteProtocol.ts": {
		"date": 1624295910000,
		"jassijs.remote.RemoteProtocol": {}
	},
	"jassijs/remote/security/Group.ts": {
		"date": 1622999224000,
		"jassijs.security.Group": {
			"$DBObject": [
				{
					"name": "jassijs_group"
				}
			],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"name": {
					"Column": []
				},
				"parentRights": {
					"JoinTable": [],
					"ManyToMany": [
						"function",
						"function"
					]
				},
				"rights": {
					"JoinTable": [],
					"ManyToMany": [
						"function",
						"function"
					]
				},
				"users": {
					"ManyToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"jassijs/remote/security/ParentRight.ts": {
		"date": 1622999218000,
		"jassijs.security.ParentRight": {
			"$DBObject": [
				{
					"name": "jassijs_parentright"
				}
			],
			"@members": {
				"id": {
					"PrimaryGeneratedColumn": []
				},
				"name": {
					"Column": []
				},
				"classname": {
					"Column": []
				},
				"i1": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"i2": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"s1": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"s2": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"groups": {
					"ManyToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"jassijs/remote/security/Right.ts": {
		"date": 1622998618000,
		"jassijs.security.Right": {
			"$DBObject": [
				{
					"name": "jassijs_right"
				}
			],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"name": {
					"Column": []
				},
				"groups": {
					"ManyToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"jassijs/remote/security/Rights.ts": {
		"date": 1622985524000,
		"jassijs.security.Rights": {}
	},
	"jassijs/remote/security/Setting.ts": {
		"date": 1624296036000,
		"jassijs.security.Setting": {
			"$DBObject": [
				{
					"name": "jassijs_setting"
				}
			],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"data": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"jassijs/remote/security/User.ts": {
		"date": 1623528370000,
		"jassijs.security.User": {
			"$DBObject": [
				{
					"name": "jassijs_user"
				}
			],
			"@members": {
				"id": {
					"PrimaryGeneratedColumn": []
				},
				"email": {
					"Column": []
				},
				"password": {
					"Column": [
						{
							"select": false
						}
					]
				},
				"groups": {
					"JoinTable": [],
					"ManyToMany": [
						"function",
						"function"
					]
				},
				"isAdmin": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"jassijs/remote/Server.ts": {
		"date": 1633979244000,
		"jassijs.remote.Server": {}
	},
	"jassijs/remote/Settings.ts": {
		"date": 1631479362000,
		"jassijs.remote.Settings": {}
	},
	"jassijs/remote/Test.ts": {
		"date": 1630957818000,
		"jassijs.remote.Test": {}
	},
	"jassijs/remote/Transaction.ts": {
		"date": 1622985432000,
		"jassijs.remote.Transaction": {}
	},
	"jassijs/security/GroupView.ts": {
		"date": 1622984494000,
		"jassijs/security/GroupView": {
			"$DBObjectView": [
				{
					"classname": "{{dbfullclassname}}"
				}
			],
			"@members": {
				"value": {
					"$Property": [
						{
							"isUrlTag": true,
							"id": true,
							"editor": "jassijs.ui.PropertyEditors.DBObjectEditor"
						}
					]
				}
			}
		}
	},
	"jassijs/security/UserView.ts": {
		"date": 1654704034248,
		"jassijs/UserView": {
			"$DBObjectView": [
				{
					"classname": "jassijs.security.User"
				}
			],
			"@members": {
				"value": {
					"$Property": [
						{
							"isUrlTag": true,
							"id": true,
							"editor": "jassijs.ui.PropertyEditors.DBObjectEditor"
						}
					]
				}
			}
		}
	},
	"jassijs/template/TemplateDBDialog.ts": {
		"date": 1633815998000,
		"jassijs.ui.TemplateDBDialog": {
			"$ActionProvider": [
				"jassijs.remote.FileNode"
			],
			"@members": {
				"newFile": {
					"$Action": [
						{
							"name": "New/Report",
							"isEnabled": "function"
						}
					]
				}
			}
		}
	},
	"jassijs/template/TemplateDBObject.ts": {
		"date": 1622985640000,
		"jassijs.template.TemplateDBDialogProperties": {
			"@members": {
				"name": {
					"$Property": [
						{
							"decription": "name of the db class"
						}
					]
				},
				"autogeneratedid": {
					"$Property": [
						{
							"default": "true",
							"description": "the primary column alue will be automatically generated with an auto-increment value"
						}
					]
				}
			}
		},
		"jassijs.ui.TemplateDBObject": {
			"$ActionProvider": [
				"jassijs.remote.FileNode"
			],
			"@members": {
				"newFile": {
					"$Action": [
						{
							"name": "New/DBObject",
							"isEnabled": "function"
						}
					]
				}
			}
		}
	},
	"jassijs/template/TemplateEmptyDialog.ts": {
		"date": 1654630454354,
		"jassijs.template.TemplateEmptyDialog": {
			"$ActionProvider": [
				"jassijs.remote.FileNode"
			],
			"@members": {
				"newFile": {
					"$Action": [
						{
							"name": "New/Dialog",
							"isEnabled": "function"
						}
					]
				}
			}
		}
	},
	"jassijs/template/TemplateRemoteObject.ts": {
		"date": 1624056722000,
		"jassijs.template.TemplateRemoteObject": {
			"$ActionProvider": [
				"jassijs.remote.FileNode"
			],
			"@members": {
				"newFile": {
					"$Action": [
						{
							"name": "New/RemoteObject",
							"isEnabled": "function"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/ActionNodeMenu.ts": {
		"date": 1654696176754,
		"jassijs/ui/ActionNodeMenu": {}
	},
	"jassijs/ui/BoxPanel.ts": {
		"date": 1654984297312,
		"jassijs.ui.BoxPanel": {
			"$UIComponent": [
				{
					"fullPath": "common/BoxPanel",
					"icon": "mdi mdi-view-sequential-outline",
					"editableChildComponents": [
						"this"
					]
				}
			],
			"$Property": [
				{
					"name": "isAbsolute",
					"hide": true,
					"type": "boolean"
				}
			],
			"@members": {
				"horizontal": {
					"$Property": [
						{
							"default": true
						}
					]
				},
				"spliter": {
					"$Property": [
						{
							"type": "number[]",
							"description": "set the size of splitter e.g. [40,60] the firstcomponent size is 40%"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/Button.ts": {
		"date": 1654695976908,
		"jassijs.ui.Button": {
			"$UIComponent": [
				{
					"fullPath": "common/Button",
					"icon": "mdi mdi-gesture-tap-button",
					"initialize": {
						"text": "button"
					}
				}
			],
			"@members": {
				"onclick": {
					"$Property": [
						{
							"default": "function(event){\n\t\n}"
						}
					]
				},
				"icon": {
					"$Property": [
						{
							"type": "image"
						}
					]
				},
				"text": {
					"$Property": []
				}
			}
		}
	},
	"jassijs/ui/Calendar.ts": {
		"date": 1654705194788,
		"jassijs.ui.Calendar": {
			"$UIComponent": [
				{
					"fullPath": "common/Calendar",
					"icon": "mdi mdi-calendar-month"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "string"
				}
			]
		}
	},
	"jassijs/ui/Checkbox.ts": {
		"date": 1654700986669,
		"jassijs.ui.Checkbox": {
			"$UIComponent": [
				{
					"fullPath": "common/Ceckbox",
					"icon": "mdi mdi-checkbox-marked-outline"
				}
			],
			"@members": {
				"onclick": {
					"$Property": [
						{
							"default": "function(event){\n\t\n}"
						}
					]
				},
				"value": {
					"$Property": [
						{
							"type": "boolean"
						}
					]
				},
				"text": {
					"$Property": []
				}
			}
		}
	},
	"jassijs/ui/Component.ts": {
		"date": 1654631923861,
		"jassijs.ui.Component": {
			"@members": {
				"onfocus": {
					"$Property": [
						{
							"default": "function(event){\n\t\n}"
						}
					]
				},
				"onblur": {
					"$Property": [
						{
							"default": "function(event){\n\t\n}"
						}
					]
				},
				"label": {
					"$Property": [
						{
							"description": "adds a label above the component"
						}
					]
				},
				"tooltip": {
					"$Property": [
						{
							"description": "tooltip are displayed on mouse over"
						}
					]
				},
				"x": {
					"$Property": [
						{}
					]
				},
				"y": {
					"$Property": []
				},
				"hidden": {
					"$Property": []
				},
				"width": {
					"$Property": [
						{
							"type": "string"
						}
					]
				},
				"height": {
					"$Property": [
						{
							"type": "string"
						}
					]
				},
				"css": {
					"$Property": [
						{
							"type": "json",
							"componentType": "jassijs.ui.CSSProperties"
						}
					]
				},
				"styles": {
					"$Property": [
						{
							"type": "componentselector",
							"componentType": "[jassijs.ui.Style]"
						}
					]
				},
				"contextMenu": {
					"$Property": [
						{
							"type": "componentselector",
							"componentType": "jassijs.ui.ContextMenu"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/ComponentDescriptor.ts": {
		"date": 1655029061275,
		"jassijs.ui.ComponentDescriptor": {}
	},
	"jassijs/ui/ComponentSpy.ts": {
		"date": 1654466293098,
		"jassijs.ui.ComponentSpy": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"dummy": {
					"$Action": [
						{
							"name": "Administration",
							"icon": "mdi mdi-account-cog-outline"
						}
					]
				},
				"showDialog": {
					"$Action": [
						{
							"name": "Administration/Spy Components",
							"icon": "mdi mdi-police-badge"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/Container.ts": {
		"date": 1654695913660,
		"jassijs.ui.Container": {}
	},
	"jassijs/ui/ContextMenu.ts": {
		"date": 1654701972513,
		"jassijs.ui.ContextMenu": {
			"$UIComponent": [
				{
					"fullPath": "common/ContextMenu",
					"icon": "mdi mdi-dots-vertical",
					"editableChildComponents": [
						"menu"
					]
				}
			],
			"@members": {
				"includeClassActions": {
					"$Property": []
				},
				"onbeforeshow": {
					"$Property": [
						{
							"default": "function(event){\n\t\n}"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/converters/DefaultConverter.ts": {
		"date": 1622985640000,
		"jassijs.ui.converters.DefaultConverterProperties": {
			"@members": {
				"stringToObject": {
					"$Property": [
						{
							"default": "function(ob){}"
						}
					]
				}
			}
		},
		"jassijs.ui.converters.DefaultConverter": {
			"$Converter": [
				{
					"name": "custom"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassijs.ui.converters.DefaultConverterProperties"
				}
			]
		}
	},
	"jassijs/ui/converters/NumberConverter.ts": {
		"date": 1622985640000,
		"jassijs.ui.converters.NumberConverter": {
			"$Converter": [
				{
					"name": "number"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json"
				}
			]
		}
	},
	"jassijs/ui/converters/StringConverter.ts": {
		"date": 1622985640000,
		"jassijs.ui.converters.StringConverter": {
			"$Converter": [
				{
					"name": "string"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json"
				}
			]
		}
	},
	"jassijs/ui/CSSProperties.ts": {
		"date": 1622985640000,
		"jassijs.ui.CSSProperties": {
			"@members": {
				"background_color": {
					"$Property": [
						{
							"type": "color"
						}
					]
				},
				"background_image": {
					"$Property": []
				},
				"border_color": {
					"$Property": [
						{
							"type": "color"
						}
					]
				},
				"border_style": {
					"$Property": [
						{
							"chooseFrom": [
								"none",
								"hidden",
								"dotted",
								"dashed",
								"solid",
								"double",
								"groove",
								"ridge",
								"inset",
								"outset",
								"inherit",
								"initial",
								"unset"
							]
						}
					]
				},
				"border_width": {
					"$Property": [
						{
							"chooseFrom": [
								"thin",
								"medium",
								"thick",
								"2px",
								"inherit",
								"initial",
								"unset"
							]
						}
					]
				},
				"color": {
					"$Property": [
						{
							"type": "color"
						}
					]
				},
				"cursor": {
					"$Property": [
						{
							"chooseFrom": [
								"auto",
								"default",
								"none",
								"context-menu",
								"help",
								"pointer",
								"progress",
								"wait",
								"cell",
								"crosshair",
								"text",
								"vertical-text",
								"alias",
								"copy",
								"move",
								"no-drop",
								"not-allowed",
								"grab",
								"grabbing",
								"all-scroll",
								"col-resize",
								"row-resize",
								"n-resize",
								"e-resize",
								"s-resize",
								"w-resize",
								"ne-resize",
								"nw-resize",
								"se-resize",
								"sw-resize",
								"ew-resize",
								"ns-resize",
								"nesw-resize",
								"nwse-resize",
								"zoom-in",
								"zoom-out",
								"inherit",
								"initial",
								"unset"
							]
						}
					]
				},
				"filter": {
					"$Property": [
						{
							"chooseFrom": [
								"blur(5px)",
								"brightness(0.4)",
								"contrast(200%)",
								"drop-shadow(16px 16px 20px blue)",
								"grayscale(50%)",
								"hue-rotate(90deg)",
								"invert(75%)",
								"opacity(25%)",
								"saturate(30%)",
								"sepia(60%)",
								"inherit",
								"initial",
								"unset"
							]
						}
					]
				},
				"float": {
					"$Property": [
						{
							"chooseFrom": [
								"left",
								"right",
								"none",
								"inline-start",
								"inline-end",
								"inherit",
								"initial",
								"unset"
							]
						}
					]
				},
				"font_family": {
					"$Property": [
						{
							"type": "font"
						}
					]
				},
				"font_size": {
					"$Property": [
						{
							"chooseFrom": [
								"12px",
								"xx-small",
								"x-small",
								"small",
								"medium",
								"large",
								"x-large",
								"xx-large",
								"xxx-large",
								"larger",
								"smaller",
								"inherit",
								"initial",
								"unset"
							]
						}
					]
				},
				"font_variant": {
					"$Property": [
						{
							"chooseFrom": [
								"normal",
								"small-caps",
								"small-caps slashed-zero",
								"common-ligatures tabular-nums",
								"no-common-ligatures proportional-nums",
								"inherit",
								"initial",
								"unset"
							]
						}
					]
				},
				"font_weight": {
					"$Property": [
						{
							"chooseFrom": [
								"normal",
								"bold",
								"lighter",
								"bolder",
								"100",
								"900",
								"inherit",
								"initial",
								"unset"
							]
						}
					]
				},
				"letter_spacing": {
					"$Property": [
						{
							"chooseFrom": [
								"normal",
								"1px"
							]
						}
					]
				},
				"line_height": {
					"$Property": [
						{
							"chooseFrom": [
								"normal",
								"32px"
							]
						}
					]
				},
				"margin_bottom": {
					"$Property": [
						{
							"chooseFrom": [
								"3px"
							]
						}
					]
				},
				"margin_left": {
					"$Property": [
						{
							"chooseFrom": [
								"3px"
							]
						}
					]
				},
				"margin_right": {
					"$Property": [
						{
							"chooseFrom": [
								"3px"
							]
						}
					]
				},
				"margin_top": {
					"$Property": [
						{
							"chooseFrom": [
								"3px"
							]
						}
					]
				},
				"overflow": {
					"$Property": [
						{
							"chooseFrom": [
								"visible",
								"hidden",
								"clip",
								"scroll",
								"auto",
								"inherit",
								"initial",
								"unset"
							]
						}
					]
				},
				"padding_bottom": {
					"$Property": [
						{
							"chooseFrom": [
								"3px"
							]
						}
					]
				},
				"padding_left": {
					"$Property": [
						{
							"chooseFrom": [
								"3px"
							]
						}
					]
				},
				"padding_right": {
					"$Property": [
						{
							"chooseFrom": [
								"3px"
							]
						}
					]
				},
				"padding_top": {
					"$Property": [
						{
							"chooseFrom": [
								"3px"
							]
						}
					]
				},
				"position": {
					"$Property": [
						{
							"chooseFrom": [
								"static",
								"relative",
								"absolute",
								"sticky",
								"fixed",
								"inherit",
								"initial",
								"unset"
							]
						}
					]
				},
				"text_align": {
					"$Property": [
						{
							"chooseFrom": [
								"start",
								"end",
								"left",
								"right",
								"center",
								"justify",
								"match-parent",
								"inherit",
								"initial",
								"unset"
							]
						}
					]
				},
				"text_decoration_color": {
					"$Property": [
						{
							"type": "color"
						}
					]
				},
				"text_decoration_line": {
					"$Property": [
						{
							"chooseFrom": [
								"none",
								"underline",
								"overline",
								"line-through",
								"blink",
								"spelling-error",
								"grammar-error",
								"inherit",
								"initial",
								"unset"
							]
						}
					]
				},
				"text_decoration_style": {
					"$Property": [
						{
							"chooseFrom": [
								"solid",
								"double",
								"dotted",
								"dashed",
								"wavy",
								"inherit",
								"initial",
								"unset"
							]
						}
					]
				},
				"text_decoration_thickness": {
					"$Property": [
						{
							"chooseFrom": [
								"3px"
							]
						}
					]
				},
				"text_transform": {
					"$Property": [
						{
							"chooseFrom": [
								"none",
								"capitalize",
								"uppercase",
								"lowercase",
								"full-width",
								"full-size-kana",
								"inherit",
								"initial",
								"unset"
							]
						}
					]
				},
				"vertical_align": {
					"$Property": [
						{
							"chooseFrom": [
								"baseline",
								"sub",
								"super",
								"text-top",
								"text-bottom",
								"middle",
								"top",
								"bottom",
								"3px",
								"inherit",
								"initial",
								"unset"
							]
						}
					]
				},
				"z_index": {
					"$Property": [
						{
							"chooseFrom": [
								"1",
								"2",
								"auto"
							]
						}
					]
				}
			}
		}
	},
	"jassijs/ui/DatabaseDesigner.ts": {
		"date": 1654466327290,
		"jassijs/ui/DatabaseDesigner": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"showDialog": {
					"$Action": [
						{
							"name": "Administration/Database Designer",
							"icon": "mdi mdi-database-edit"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/Databinder.ts": {
		"date": 1633770208000,
		"jassijs.ui.Databinder": {
			"$UIComponent": [
				{
					"fullPath": "common/Databinder",
					"icon": "mdi mdi-connection"
				}
			]
		}
	},
	"jassijs/ui/DataComponent.ts": {
		"date": 1655060463951,
		"jassijs.ui.DataComponent": {
			"@members": {
				"autocommit": {
					"$Property": []
				},
				"bind": {
					"$Property": [
						{
							"type": "databinder"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/DBObjectDialog.ts": {
		"date": 1627590896000,
		"jassijs.ui.DBObjectDialog": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"createActions": {
					"$Actions": []
				}
			}
		}
	},
	"jassijs/ui/DBObjectExplorer.ts": {
		"date": 1626119078000,
		"jassijs.ui.DBObjectNode": {},
		"jassijs.ui.DBFileActions": {
			"$ActionProvider": [
				"jassijs.remote.FileNode"
			],
			"@members": {
				"ViewData": {
					"$Action": [
						{
							"name": "View Data",
							"isEnabled": "function"
						}
					]
				}
			}
		},
		"jassijs.ui.DBObjectActions": {
			"$ActionProvider": [
				"jassijs.ui.DBObjectNode"
			],
			"@members": {
				"ViewData": {
					"$Action": [
						{
							"name": "View Data"
						}
					]
				},
				"OpenCode": {
					"$Action": [
						{
							"name": "Open Code"
						}
					]
				}
			}
		},
		"jassijs.ui.DBObjectExplorer": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"dummy": {
					"$Action": [
						{
							"name": "Windows",
							"icon": "mdi mdi-iframe-array-outline"
						}
					]
				},
				"dummy2": {
					"$Action": [
						{
							"name": "Windows/Development",
							"icon": "mdi mdi-dev-to"
						}
					]
				},
				"show": {
					"$Action": [
						{
							"name": "Windows/Development/DBObjects",
							"icon": "mdi mdi-database-search"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/DBObjectView.ts": {
		"date": 1655058328961,
		"jassijs/ui/DBObjectView": {
			"$UIComponent": [
				{
					"editableChildComponents": [
						"this",
						"me.main",
						"me.toolbar",
						"me.save",
						"me.remove",
						"me.refresh"
					]
				}
			],
			"@members": {
				"oncreated": {
					"$Property": [
						{
							"default": "function(obj?/*: DBObject*/){\n\t\n}"
						}
					]
				},
				"onsaved": {
					"$Property": [
						{
							"default": "function(obj?/*: DBObject*/){\n\t\n}"
						}
					]
				},
				"onrefreshed": {
					"$Property": [
						{
							"default": "function(obj?/*: DBObject*/){\n\t\n}"
						}
					]
				},
				"ondeleted": {
					"$Property": [
						{
							"default": "function(obj?/*: DBObject*/){\n\t\n}"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/DesignDummy.ts": {
		"date": 1632323326000,
		"jassijs.ui.DesignDummy": {}
	},
	"jassijs/ui/DockingContainer.ts": {
		"date": 1634384980000,
		"jassijs.ui.DockingContainer": {}
	},
	"jassijs/ui/ErrorPanel.ts": {
		"date": 1627925312000,
		"jassijs.ui.ErrorPanel": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"showDialog": {
					"$Action": [
						{
							"name": "Administration/Errors",
							"icon": "mdi mdi-emoticon-confused-outline"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/FileExplorer.ts": {
		"date": 1634384746000,
		"jassijs.ui.FileActions": {
			"$ActionProvider": [
				"jassijs.remote.FileNode"
			],
			"@members": {
				"newFile": {
					"$Action": [
						{
							"name": "New/File",
							"icon": "mdi mdi-file",
							"isEnabled": "function"
						}
					]
				},
				"download": {
					"$Action": [
						{
							"name": "Download",
							"isEnabled": "function"
						}
					]
				},
				"newFolder": {
					"$Action": [
						{
							"name": "New/Folder",
							"isEnabled": "function"
						}
					]
				},
				"newModule": {
					"$Action": [
						{
							"name": "New/Module",
							"isEnabled": "function"
						}
					]
				},
				"dodelete": {
					"$Action": [
						{
							"name": "Delete"
						}
					]
				},
				"rename": {
					"$Action": [
						{
							"name": "Rename"
						}
					]
				},
				"refresh": {
					"$Action": [
						{
							"name": "Refresh"
						}
					]
				},
				"open": {
					"$Action": [
						{
							"name": "Open",
							"isEnabled": "function"
						}
					]
				}
			}
		},
		"jassijs.ui.FileExplorer": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"show": {
					"$Action": [
						{
							"name": "Windows/Development/Files",
							"icon": "mdi mdi-file-tree"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/HTMLEditorPanel.ts": {
		"date": 1654701807236,
		"jassijs.ui.HTMLEditorPanel": {}
	},
	"jassijs/ui/HTMLPanel.ts": {
		"date": 1654984567578,
		"jassijs.ui.HTMLPanel": {
			"$UIComponent": [
				{
					"fullPath": "common/HTMLPanel",
					"icon": "mdi mdi-cloud-tags"
				}
			],
			"@members": {
				"newlineafter": {
					"$Property": [
						{
							"description": "line break after element",
							"default": false
						}
					]
				},
				"template": {
					"$Property": [
						{
							"decription": "e.g. component.value=new Person();component.template:\"{{name}}\""
						}
					]
				},
				"value": {
					"$Property": []
				}
			}
		}
	},
	"jassijs/ui/Image.ts": {
		"date": 1654704834003,
		"jassijs.ui.Image": {
			"$UIComponent": [
				{
					"fullPath": "default/Image",
					"icon": "mdi mdi-file-image"
				}
			],
			"@members": {
				"onclick": {
					"$Property": [
						{
							"default": "function(event){\n\t\n}"
						}
					]
				},
				"value": {
					"$Property": [
						{
							"type": "string"
						}
					]
				},
				"src": {
					"$Property": [
						{
							"type": "image"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/InvisibleComponent.ts": {
		"date": 1632424878000,
		"jassijs.ui.InvisibleComponent": {
			"$Property": [
				{
					"hideBaseClassProperties": true
				}
			]
		}
	},
	"jassijs/ui/Menu.ts": {
		"date": 1654702715316,
		"jassijs.ui.Menu": {
			"$UIComponent": [
				{
					"fullPath": "common/Menu",
					"icon": "mdi mdi-menu",
					"initialize": {
						"text": "menu"
					}
				}
			],
			"@members": {
				"onclick": {
					"$Property": [
						{
							"name": "onclick",
							"type": "function",
							"default": "function(event){\n\t\n}"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/MenuItem.ts": {
		"date": 1654702869980,
		"jassijs.ui.MenuItem": {
			"$UIComponent": [
				{
					"fullPath": "common/MenuItem",
					"icon": "mdi mdi-menu-open",
					"initialize": {
						"text": "menu"
					},
					"editableChildComponents": [
						"items"
					]
				}
			],
			"@members": {
				"onclick": {
					"$Property": [
						{
							"default": "function(event){\n\t\n}"
						}
					]
				},
				"icon": {
					"$Property": []
				},
				"text": {
					"$Property": []
				}
			}
		}
	},
	"jassijs/ui/ObjectChooser.ts": {
		"date": 1655060562375,
		"jassijs.ui.ObjectChooser": {
			"$UIComponent": [
				{
					"fullPath": "common/ObjectChooser",
					"icon": "mdi mdi-glasses"
				}
			],
			"@members": {
				"dialogHeight": {
					"$Property": [
						{
							"default": 450
						}
					]
				},
				"dialogWidth": {
					"$Property": [
						{
							"default": 300
						}
					]
				},
				"items": {
					"$Property": [
						{
							"type": "string",
							"description": "the classname for to choose"
						}
					]
				},
				"onchange": {
					"$Property": [
						{
							"default": "function(event){\n\t\n}"
						}
					]
				},
				"autocommit": {
					"$Property": []
				},
				"bind": {
					"$Property": [
						{
							"type": "databinder"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/OptionDialog.ts": {
		"date": 1627926138000,
		"jassijs.ui.OptionDialog": {
			"@members": {
				"text": {
					"$Property": []
				}
			}
		},
		"jassijs.ui.OptionDialogTestProp": {
			"@members": {
				"visible": {
					"$Property": []
				},
				"text": {
					"$Property": []
				}
			}
		}
	},
	"jassijs/ui/Panel.ts": {
		"date": 1654899711644,
		"jassijs.ui.PanelCreateProperties": {
			"@members": {
				"useSpan": {
					"$Property": [
						{
							"default": false
						}
					]
				}
			}
		},
		"jassijs.ui.Panel": {
			"$UIComponent": [
				{
					"fullPath": "common/Panel",
					"icon": "mdi mdi-checkbox-blank-outline",
					"editableChildComponents": [
						"this"
					]
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassijs.ui.PanelCreateProperties"
				}
			],
			"@members": {
				"isAbsolute": {
					"$Property": []
				}
			}
		}
	},
	"jassijs/ui/Property.ts": {
		"date": 1622985640000,
		"jassijs.ui.Property": {}
	},
	"jassijs/ui/PropertyEditor.ts": {
		"date": 1654983438096,
		"jassijs.ui.PropertyEditor": {},
		"jassijs.ui.PropertyEditorTestSubProperties": {
			"@members": {
				"num": {
					"$Property": []
				},
				"text": {
					"$Property": []
				}
			}
		},
		"jassijs.ui.PropertyEditorTestProperties": {
			"@members": {
				"dialogname": {
					"$Property": [
						{
							"decription": "name of the dialog"
						}
					]
				},
				"checked": {
					"$Property": []
				},
				"color": {
					"$Property": [
						{
							"type": "color"
						}
					]
				},
				"component": {
					"$Property": [
						{
							"type": "componentselector",
							"componentType": "jassi.ui.Component"
						}
					]
				},
				"databinder": {
					"$Property": [
						{
							"type": "databinder"
						}
					]
				},
				"dbobject": {
					"$Property": [
						{
							"type": "dbobject",
							"componentType": "de.Kunde"
						}
					]
				},
				"num": {
					"$Property": [
						{
							"default": 80
						}
					]
				},
				"font": {
					"$Property": [
						{
							"type": "font"
						}
					]
				},
				"func": {
					"$Property": [
						{
							"type": "function"
						}
					]
				},
				"html": {
					"$Property": [
						{
							"type": "html"
						}
					]
				},
				"image": {
					"$Property": [
						{
							"type": "image"
						}
					]
				},
				"json": {
					"$Property": [
						{
							"type": "json",
							"componentType": "jassijs.ui.PropertyEditorTestSubProperties"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/PropertyEditors/BooleanEditor.ts": {
		"date": 1622985640000,
		"jassijs.ui.PropertyEditors.BooleanEditor": {
			"$PropertyEditor": [
				[
					"boolean"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/ClassSelectorEditor.ts": {
		"date": 1622985640000,
		"jassijs.ui.PropertyEditors.ClassSelectorEditor": {
			"$PropertyEditor": [
				[
					"classselector"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/ColorEditor.ts": {
		"date": 1633539862000,
		"jassijs.ui.PropertyEditors.ColorEditor": {
			"$PropertyEditor": [
				[
					"color"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/ComponentSelectorEditor.ts": {
		"date": 1622984380000,
		"jassijs.ui.PropertyEditors.ComponentSelectorEditor": {
			"$PropertyEditor": [
				[
					"componentselector"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/DatabinderEditor.ts": {
		"date": 1654950343134,
		"jassijs.ui.PropertyEditors.DatabinderEditor": {
			"$PropertyEditor": [
				[
					"databinder"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/DBObjectEditor.ts": {
		"date": 1622985640000,
		"jassijs.ui.PropertyEditors.DBObjectEditor": {
			"$PropertyEditor": [
				[
					"dbobject"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/DefaultEditor.ts": {
		"date": 1633126372000,
		"jassijs.ui.PropertyEditors.DefaultEditor": {
			"$PropertyEditor": [
				[
					"string",
					"number",
					"number[]",
					"boolean[]"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/Editor.ts": {
		"date": 1622985640000,
		"jassijs.ui.PropertyEditors.Editor": {}
	},
	"jassijs/ui/PropertyEditors/FontEditor.ts": {
		"date": 1632505076000,
		"jassijs.ui.PropertyEditors.FontEditor": {
			"$PropertyEditor": [
				[
					"font"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/FunctionEditor.ts": {
		"date": 1654630143534,
		"jassijs.ui.PropertyEditors.FunctionEditor": {
			"$PropertyEditor": [
				[
					"function"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/HTMLEditor.ts": {
		"date": 1622985640000,
		"jassijs.ui.PropertyEditors.HTMLEditor": {
			"$PropertyEditor": [
				[
					"html"
				]
			]
		}
	},
	"jassijs/ui/PropertyEditors/ImageEditor.ts": {
		"date": 1634384832000,
		"jassijs.ui.PropertyEditors.ImageEditor": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"$PropertyEditor": [
				[
					"image"
				]
			],
			"@members": {
				"dummy": {
					"$Action": [
						{
							"name": "Tools",
							"icon": "mdi mdi-tools"
						}
					]
				},
				"show": {
					"$Action": [
						{
							"name": "Tools/Icons",
							"icon": "mdi mdi-image-area"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/PropertyEditors/JsonEditor.ts": {
		"date": 1627596236000,
		"jassijs.ui.PropertyEditors.JsonEditor": {
			"$PropertyEditor": [
				[
					"json"
				]
			]
		},
		"jassijs.ui.PropertyEditorTestProperties": {
			"@members": {
				"dialogname": {
					"$Property": [
						{
							"decription": "name of the dialog"
						}
					]
				},
				"jo": {
					"$Property": [
						{
							"name": "jo/selectMode",
							"type": "number",
							"default": 3,
							"chooseFrom": [
								1,
								2,
								3
							],
							"description": "1=single 2=multi 3=multi_hier"
						},
						{
							"name": "jo",
							"type": "json",
							"componentType": "jassijs.ui.PropertyEditorTestProperties2"
						}
					]
				}
			}
		},
		"jassijs.ui.PropertyEditorTestProperties2": {
			"@members": {
				"name1": {
					"$Property": [
						{
							"decription": "name of the dialog"
						}
					]
				},
				"name2": {
					"$Property": [
						{
							"decription": "name of the dialog"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/PropertyEditors/LoadingEditor.ts": {
		"date": 1622985640000
	},
	"jassijs/ui/PropertyEditors/NameEditor.ts": {
		"date": 1622985640000,
		"jassijs.ui.PropertyEditors.NameEditor": {
			"$PropertyEditor": [
				[
					"*name*"
				]
			]
		}
	},
	"jassijs/ui/Repeater.ts": {
		"date": 1655144356595,
		"jassijs.ui.RepeaterDesignPanel": {
			"$UIComponent": [
				{
					"editableChildComponents": [
						"databinder"
					]
				}
			]
		},
		"jassijs.ui.Repeater": {
			"$UIComponent": [
				{
					"fullPath": "common/Repeater",
					"icon": "mdi mdi-locker-multiple",
					"editableChildComponents": [
						"this",
						"design"
					]
				}
			],
			"@members": {
				"bind": {
					"$Property": [
						{
							"type": "databinder"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/SearchExplorer.ts": {
		"date": 1627596576000,
		"jassijs.ui.SearchExplorer": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"show": {
					"$Action": [
						{
							"name": "Windows/Development/Search",
							"icon": "mdi mdi-folder-search-outline"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/Select.ts": {
		"date": 1654899968875,
		"jassijs.ui.SelectCreateProperties": {
			"@members": {
				"multiple": {
					"$Property": [
						{
							"default": false
						}
					]
				},
				"allowDeselect": {
					"$Property": [
						{
							"default": false
						}
					]
				},
				"placeholder": {
					"$Property": [
						{
							"default": ""
						}
					]
				}
			}
		},
		"jassijs.ui.Select": {
			"$UIComponent": [
				{
					"fullPath": "common/Select",
					"icon": "mdi mdi-form-dropdown"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassijs.ui.SelectCreateProperties"
				}
			],
			"@members": {
				"onchange": {
					"$Property": [
						{
							"default": "function(event){\n\t\n}"
						}
					]
				},
				"display": {
					"$Property": [
						{
							"type": "string"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/SettingsDialog.ts": {
		"date": 1654466335052,
		"jassijs.ui.SettingsObject": {},
		"jassijs.ui.SettingsDialog": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"show": {
					"$Action": [
						{
							"name": "Settings",
							"icon": "mdi mdi-settings-helper"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/Style.ts": {
		"date": 1654900107227,
		"jassijs.ui.Style": {
			"$UIComponent": [
				{
					"fullPath": "common/Style",
					"icon": "mdi mdi-virus"
				}
			],
			"@members": {
				"css": {
					"$Property": [
						{
							"type": "json",
							"componentType": "jassijs.ui.CSSProperties"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/Table.ts": {
		"date": 1654900765802,
		"jassijs.ui.TableEditorProperties": {
			"@members": {
				"paginationSize": {
					"$Property": [
						{
							"default": "undefined"
						}
					]
				},
				"headerSort": {
					"$Property": [
						{
							"default": true
						}
					]
				},
				"layout": {
					"$Property": [
						{
							"default": "fitDataStretch",
							"chooseFrom": [
								"fitData",
								"fitColumns",
								"fitDataFill",
								"fitDataStretch"
							]
						}
					]
				},
				"dataTreeChildFunction": {
					"$Property": [
						{
							"default": "undefined"
						}
					]
				},
				"movableColumns": {
					"$Property": [
						{
							"default": false
						}
					]
				},
				"cellDblClick": {
					"$Property": [
						{
							"default": "function(event:any,group:any){\n\t\n}"
						}
					]
				}
			}
		},
		"jassijs.ui.Table": {
			"$UIComponent": [
				{
					"fullPath": "common/Table",
					"icon": "mdi mdi-grid"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassijs.ui.TableEditorProperties"
				}
			],
			"@members": {
				"options": {
					"$Property": [
						{
							"type": "json",
							"componentType": "jassijs.ui.TableEditorProperties"
						}
					]
				},
				"onchange": {
					"$Property": [
						{
							"default": "function(event?: JQueryEventObject, data?:Tabulator.RowComponent){\n\t\n}"
						}
					]
				},
				"showSearchbox": {
					"$Property": []
				},
				"height": {
					"$Property": [
						{
							"type": "string"
						}
					]
				},
				"bindItems": {
					"$Property": [
						{
							"type": "databinder"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/Textarea.ts": {
		"date": 1622984380000,
		"jassijs.ui.Textarea": {
			"$UIComponent": [
				{
					"fullPath": "common/Textarea",
					"icon": "mdi mdi-text-box-outline"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "string"
				}
			]
		}
	},
	"jassijs/ui/Textbox.ts": {
		"date": 1655060542267,
		"jassijs.ui.Textbox": {
			"$UIComponent": [
				{
					"fullPath": "common/Textbox",
					"icon": "mdi mdi-form-textbox"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "string"
				}
			],
			"@members": {
				"converter": {
					"$Property": [
						{
							"type": "classselector",
							"service": "$Converter"
						}
					]
				},
				"format": {
					"$Property": [
						{
							"type": "string",
							"chooseFrom": "allFormats"
						}
					]
				},
				"value": {
					"$Property": [
						{
							"type": "string"
						}
					]
				},
				"onclick": {
					"$Property": [
						{
							"default": "function(event){\n\t\n}"
						}
					]
				},
				"onchange": {
					"$Property": [
						{
							"default": "function(event){\n\t\n}"
						}
					]
				},
				"onkeydown": {
					"$Property": [
						{
							"default": "function(event){\n\t\n}"
						}
					]
				},
				"oninput": {
					"$Property": [
						{
							"default": "function(event){\n\t\n}"
						}
					]
				},
				"placeholder": {
					"$Property": []
				}
			}
		}
	},
	"jassijs/ui/Tree.ts": {
		"date": 1655140880763,
		"jassijs.ui.TreeEditorPropertiesMulti": {
			"@members": {
				"mode": {
					"$Property": [
						{
							"default": "",
							"chooseFrom": [
								"",
								"sameParent",
								"sameLevel"
							],
							"description": "multi selection mode"
						}
					]
				}
			}
		},
		"jassijs.ui.TreeEditorProperties": {
			"@members": {
				"selectMode": {
					"$Property": [
						{
							"default": 3,
							"chooseFrom": [
								1,
								2,
								3
							],
							"description": "1=single 2=multi 3=multi_hier"
						}
					]
				},
				"checkbox": {
					"$Property": [
						{
							"default": false,
							"description": "display a checkbox before the node"
						}
					]
				},
				"multi": {
					"$Property": [
						{
							"type": "json",
							"componentType": "jassijs.ui.TreeEditorPropertiesMulti"
						}
					]
				}
			}
		},
		"jassijs.ui.Tree": {
			"$UIComponent": [
				{
					"fullPath": "common/Tree",
					"icon": "mdi mdi-file-tree"
				}
			],
			"$Property": [
				{
					"name": "new",
					"type": "json",
					"componentType": "jassijs.ui.TreeEditorProperties"
				}
			],
			"@members": {
				"options": {
					"$Property": [
						{
							"type": "json",
							"componentType": "jassijs.ui.TableEditorProperties"
						}
					]
				},
				"propStyle": {
					"$Property": [
						{
							"type": "string",
							"description": "the property called to get the style of the item"
						}
					]
				},
				"propDisplay": {
					"$Property": [
						{
							"type": "string",
							"description": "the property called to get the name of the item"
						}
					]
				},
				"onclick": {
					"$Property": [
						{
							"default": "function(event?: JQueryEventObject/*, data?:Fancytree.EventData*/){\n\t\n}"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/Upload.ts": {
		"date": 1633773138000,
		"jassijs.ui.Upload": {
			"$UIComponent": [
				{
					"fullPath": "common/Upload",
					"icon": "mdi mdi-cloud-upload-outline"
				}
			],
			"@members": {
				"readAs": {
					"$Property": [
						{
							"chooseFromStrict": true,
							"chooseFrom": [
								"Text",
								"DataUrl",
								"ArrayBuffer",
								"BinaryString"
							]
						}
					]
				},
				"accept": {
					"$Property": []
				},
				"multiple": {
					"$Property": []
				},
				"onuploaded": {
					"$Property": [
						{
							"default": "function(data:{[file:string]:string}){\n\t\n}"
						}
					]
				}
			}
		}
	},
	"jassijs/ui/VariablePanel.ts": {
		"date": 1655133146213,
		"jassijs.ui.VariablePanel": {}
	},
	"jassijs/util/Cookies.ts": {
		"date": 1622984214000
	},
	"jassijs/util/CSVImport.ts": {
		"date": 1635958614000,
		"jassijs.util.CSVImport": {
			"$ActionProvider": [
				"jassijs.base.ActionNode"
			],
			"@members": {
				"showDialog": {
					"$Action": [
						{
							"name": "Administration/Database CSV-Import",
							"icon": "mdi mdi-database-import"
						}
					]
				}
			}
		}
	},
	"jassijs/util/DatabaseSchema.ts": {
		"date": 1622984214000
	},
	"jassijs/util/Numberformatter.ts": {
		"date": 1624054582000,
		"jassijs.util.Numberformatter": {}
	},
	"jassijs/util/Reloader.ts": {
		"date": 1622985640000,
		"jassijs.util.Reloader": {}
	},
	"jassijs/util/Tools.ts": {
		"date": 1634384136000,
		"jassijs.util.Tools": {}
	},
	"jassijs/util/Runlater.ts": {
		"date": 1631479654000,
		"jassi.util.Runlater": {}
	}
}
 }
});