//this file is autogenerated don't modify
define("jassi_localserver/registry",["require"], function(require) {
 return {
  default: {
	"jassi_localserver/DatabaseSchema.ts": {
		"date": 1614290342083
	},
	"jassi_localserver/DBManager.ts": {
		"date": 1614469272935
	},
	"jassi_localserver/Filessystem.ts": {
		"date": 1614710621004
	},
	"jassi_localserver/LocalProtocol.ts": {
		"date": 1614707860432
	},
	"jassi_localserver/modul.ts": {
		"date": 1614634283885
	},
	"jassi_localserver/Testserver.ts": {
		"date": 1614365026599,
		"jassi_localserver.Testserver": {}
	},
	"jassi_localserver/Testuser.ts": {
		"date": 1614289287180,
		"Testuser": {
			"$DBObject": []
		}
	},
	"jassi_localserver/TypeORMListener.ts": {
		"date": 1614543915598,
		"jassi_localserver/TypeORMListener": {
			"EventSubscriber": []
		}
	}
}
 }
});