//this file is autogenerated don't modify
define("demo/registry",["require"], function(require) {
 return {
  default: {
	"demo/Dialog.ts": {
		"date": 1655556795284,
		"demo/Dialog": {}
	},
	"demo/EmptyDialog.ts": {
		"date": 1655556795283,
		"demo.EmptyDialog": {}
	},
	"demo/MemoryTest.ts": {
		"date": 1624296680000
	},
	"demo/modul.ts": {
		"date": 1612818334000
	},
	"demo/ReportInvoice.ts": {
		"date": 1655556795176,
		"demo.ReportInvoice": {}
	},
	"demo/StyleDialog.ts": {
		"date": 1655556793964,
		"demo/StyleDialog": {}
	},
	"demo/TableContextmenu.ts": {
		"date": 1622984380000
	},
	"demo/TestComponent.ts": {
		"date": 1655556793964,
		"demo.TestComponent": {
			"$UIComponent": [
				{
					"fullPath": "common/TestComponent",
					"editableChildComponents": [
						"this",
						"me.button4"
					]
				}
			]
		}
	},
	"demo/Testcontextmenu.ts": {
		"date": 1655556793964,
		"demo.Testcontextmenu": {}
	},
	"demo/Testmenu.ts": {
		"date": 1655556795177,
		"demo.Testmenu": {}
	},
	"demo/TestTree.ts": {
		"date": 1655556795176,
		"demo.TestTree": {}
	},
	"demo/TestUpload.ts": {
		"date": 1655556795176,
		"demo/TestUpload": {}
	},
	"demo/TreeContextmenu.ts": {
		"date": 1634384688000
	},
	"demo/TreeTable.ts": {
		"date": 1655556795176,
		"demo.TreeTable": {}
	},
	"demo/ReportKunden.ts": {
		"date": 1655556795176,
		"de.ReportKunde": {
			"@members": {
				"value": {
					"$Property": [
						{
							"isUrlTag": true,
							"id": true,
							"editor": "jassijs.ui.PropertyEditors.DBObjectEditor"
						}
					]
				}
			}
		}
	},
	"demo/ReportInvoice2.ts": {
		"date": 1655556795176,
		"demo.ReportInvoice": {}
	},
	"demo/Testdatatable.ts": {
		"date": 1655556793965
	},
	"demo/Testdatatable2.ts": {
		"date": 1655556795176
	},
	"demo/Testdatatable3.ts": {
		"date": 1655556795176
	},
	"demo/ReportStyle.ts": {
		"date": 1655556795175
	},
	"demo/Testtable.ts": {
		"date": 1655556795176
	},
	"demo/TestList.ts": {
		"date": 1635803026000
	},
	"demo/TestImage.ts": {
		"date": 1633792454000
	},
	"demo/Testdatatable1.ts": {
		"date": 1655556795175
	},
	"demo/LargeReport.ts": {
		"date": 1634240084000
	},
	"demo/DelTest.ts": {
		"date": 1635896382000
	},
	"demo/Dialog2.ts": {
		"date": 1655556795284,
		"demo/Dialog2": {}
	}
}
 }
});