"use strict:";
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "tests/remote/T.ts": {
        "date": 1655556792356,
        "tests.remote.T": {}
    },
    "tests/remote/TestCustomer.ts": {
        "date": 1656073034029,
        "tests.TestCustomer": {
            "$ParentRights": [
                [
                    {
                        "name": "TestCustomers",
                        "sqlToCheck": "me.id>=:i1 and me.id<=:i2",
                        "description": {
                            "text": "TestCustomer",
                            "i1": "from",
                            "i2": "to"
                        }
                    }
                ]
            ],
            "$DBObject": [],
            "@members": {
                "id": {
                    "PrimaryColumn": []
                },
                "name": {
                    "Column": [
                        {
                            "nullable": true
                        }
                    ]
                },
                "orders": {
                    "OneToMany": [
                        "function",
                        "function"
                    ]
                }
            }
        }
    },
    "tests/remote/TestOrder.ts": {
        "date": 1656073023813,
        "tests.TestOrder": {
            "$DBObject": [],
            "@members": {
                "id": {
                    "PrimaryColumn": []
                },
                "customer": {
                    "$CheckParentRight": [],
                    "ManyToOne": [
                        "function"
                    ]
                },
                "details": {
                    "OneToMany": [
                        "function",
                        "function"
                    ]
                }
            }
        }
    },
    "tests/remote/TestOrderDetails.ts": {
        "date": 1656073236783,
        "tests.TestOrderDetails": {
            "$DBObject": [],
            "@members": {
                "id": {
                    "PrimaryColumn": []
                },
                "Order": {
                    "$CheckParentRight": [],
                    "ManyToOne": [
                        "function",
                        "function"
                    ]
                }
            }
        }
    },
    "tests/remote/TestServerfile.ts": {
        "date": 1624999038000
    },
    "tests/remote/TestBigData.ts": {
        "date": 1656620693167,
        "tests.TestBigData": {
            "$DBObject": [],
            "@members": {
                "id": {
                    "PrimaryGeneratedColumn": []
                },
                "name": {
                    "Column": [
                        {
                            "nullable": true
                        }
                    ]
                },
                "name2": {
                    "Column": [
                        {
                            "nullable": true
                        }
                    ]
                },
                "number1": {
                    "Column": [
                        {
                            "nullable": true
                        }
                    ]
                },
                "number2": {
                    "Column": [
                        {
                            "nullable": true
                        }
                    ]
                }
            }
        }
    }
};
//# sourceMappingURL=registry.js.map