"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"tests/remote/T.ts": {
		"date": 1681570949861.1401,
		"tests.remote.T": {}
	},
	"tests/remote/TestCustomer.ts": {
		"date": 1656073036000,
		"tests.TestCustomer": {
			"$ParentRights": [
				[
					{
						"name": "TestCustomers",
						"sqlToCheck": "me.id>=:i1 and me.id<=:i2",
						"description": {
							"text": "TestCustomer",
							"i1": "from",
							"i2": "to"
						}
					}
				]
			],
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"name": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"orders": {
					"OneToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"tests/remote/TestOrder.ts": {
		"date": 1656073024000,
		"tests.TestOrder": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"customer": {
					"$CheckParentRight": [],
					"ManyToOne": [
						"function"
					]
				},
				"details": {
					"OneToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"tests/remote/TestOrderDetails.ts": {
		"date": 1656073238000,
		"tests.TestOrderDetails": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"Order": {
					"$CheckParentRight": [],
					"ManyToOne": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"tests/remote/TestServerfile.ts": {
		"date": 1624999038000
	},
	"tests/remote/TestBigData.ts": {
		"date": 1656620694000,
		"tests.TestBigData": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryGeneratedColumn": []
				},
				"name": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"name2": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"number1": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"number2": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	}
}