"use strict:";
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "testrmodul/remote/TestRCustomer.ts": {
        "date": 1624208322053,
        "testrmodul.TestRCustomer": {
            "$DBObject": []
        }
    },
    "testrmodul/remote/TestRModul.ts": {
        "date": 1624208315499,
        "testrmodul.remote.TestRModul": {}
    }
};
//# sourceMappingURL=registry.js.map