"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"testrmodul/remote/TestRCustomer.ts": {
		"date": 1624297114344,
		"testrmodul.TestRCustomer": {
			"$DBObject": []
		}
	},
	"testrmodul/remote/TestRModul.ts": {
		"date": 1624297108836,
		"testrmodul.remote.TestRModul": {}
	}
}