"use strict:";
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "local/remote/Book.ts": {
        "date": 1656073088000,
        "local.Book": {
            "$DBObject": [],
            "@members": {
                "id": {
                    "PrimaryColumn": []
                },
                "tt": {
                    "Column": [
                        {
                            "nullable": true
                        }
                    ]
                },
                "t2": {
                    "Column": []
                }
            }
        }
    }
};
//# sourceMappingURL=registry.js.map