"use strict:";
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "nothwind/remote/Products.ts": {
        "date": 1615841937632,
        "nothwind.Products": {
            "$DBObject": []
        }
    }
};
//# sourceMappingURL=registry.js.map