"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"northwind/remote/Categories.ts": {
		"date": 1655556792358,
		"northwind.Categories": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"CategoryName": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Description": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Picture": {
					"Column": []
				},
				"Products": {
					"OneToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"northwind/remote/Customer.ts": {
		"date": 1655556862854,
		"northwind.Customer": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"CompanyName": {
					"Column": []
				},
				"ContactName": {
					"Column": []
				},
				"ContactTitle": {
					"Column": []
				},
				"Address": {
					"Column": []
				},
				"City": {
					"Column": []
				},
				"Region": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"PostalCode": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Country": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Phone": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Fax": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"northwind/remote/Employees.ts": {
		"date": 1655556792357,
		"northwind.Employees": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"LastName": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"FirstName": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Title": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"TitleOfCourtesy": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Address": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"City": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Region": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"PostalCode": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Country": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"HomePhone": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Extension": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Photo": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Notes": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"PhotoPath": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ReportsTo": {
					"JoinColumn": [],
					"ManyToOne": [
						"function"
					]
				},
				"BirthDate": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"HireDate": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"northwind/remote/OrderDetails.ts": {
		"date": 1655556862851,
		"northwind.OrderDetails": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryGeneratedColumn": []
				},
				"Order": {
					"ManyToOne": [
						"function",
						"function"
					]
				},
				"Product": {
					"ManyToOne": [
						"function"
					]
				},
				"UnitPrice": {
					"Column": [
						{
							"nullable": false,
							"type": "decimal"
						}
					]
				},
				"Quantity": {
					"Column": []
				},
				"Discount": {
					"Column": [
						{
							"nullable": true,
							"type": "decimal"
						}
					]
				}
			}
		}
	},
	"northwind/remote/Orders.ts": {
		"date": 1655556792357,
		"northwind.Orders": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"Customer": {
					"ManyToOne": [
						"function"
					]
				},
				"Employee": {
					"ManyToOne": [
						"function"
					]
				},
				"OrderDate": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"RequiredDate": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShippedDate": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipVia": {
					"ManyToOne": [
						"function"
					]
				},
				"Freight": {
					"Column": [
						{
							"nullable": true,
							"type": "decimal"
						}
					]
				},
				"ShipName": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipAddress": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipCity": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipRegion": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipPostalCode": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ShipCountry": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Details": {
					"OneToMany": [
						"function",
						"function"
					]
				}
			}
		}
	},
	"northwind/remote/Products.ts": {
		"date": 1655556862851,
		"northwind.Products": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"ProductName": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Supplier": {
					"ManyToOne": [
						"function"
					]
				},
				"Category": {
					"ManyToOne": [
						"function",
						"function"
					]
				},
				"QuantityPerUnit": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"UnitPrice": {
					"Column": [
						{
							"nullable": true,
							"type": "decimal"
						}
					]
				},
				"UnitsInStock": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"UnitsOnOrder": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ReorderLevel": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Discontinued": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"northwind/remote/Shippers.ts": {
		"date": 1655556792356,
		"northwind.Shippers": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"CompanyName": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Phone": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"northwind/remote/Suppliers.ts": {
		"date": 1655556792357,
		"northwind.Suppliers": {
			"$DBObject": [],
			"@members": {
				"id": {
					"PrimaryColumn": []
				},
				"CompanyName": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ContactName": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"ContactTitle": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Address": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"City": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Region": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"PostalCode": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Country": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Phone": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"Fax": {
					"Column": [
						{
							"nullable": true
						}
					]
				},
				"HomePage": {
					"Column": [
						{
							"nullable": true
						}
					]
				}
			}
		}
	},
	"northwind/SampleServerReport.ts": {
		"date": 1624805092000
	}
}