"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"tests/remote/TestCustomer.ts": {
		"date": 1623440377887,
		"tests.TestCustomer": {
			"$DBObject": []
		}
	},
	"tests/remote/TestOrder.ts": {
		"date": 1623442886394,
		"tests.TestOrder": {
			"$DBObject": []
		}
	},
	"tests/remote/TestOrderDetails.ts": {
		"date": 1623443590163,
		"tests.TestOrderDetails": {
			"$DBObject": []
		}
	}
}