"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"jassijs/remote/Classes.ts": {
		"date": 1624296519695,
		"jassijs.remote.JassiError": {},
		"jassijs.remote.Classes": {}
	},
	"jassijs/remote/ClientError.ts": {
		"date": 1624295333733,
		"jassijs.remote.ClientError": {}
	},
	"jassijs/remote/Database.ts": {
		"date": 1622985395292,
		"jassijs.remote.Database": {}
	},
	"jassijs/remote/DatabaseTools.ts": {
		"date": 1624296507755,
		"jassijs.remote.DatabaseTools": {}
	},
	"jassijs/remote/DBArray.ts": {
		"date": 1624295775441,
		"jassijs.remote.DBArray": {}
	},
	"jassijs/remote/DBObject.ts": {
		"date": 1624295824039,
		"jassijs.remote.DBObject": {}
	},
	"jassijs/remote/DBObjectQuery.ts": {
		"date": 1623876712108
	},
	"jassijs/remote/Extensions.ts": {
		"date": 1622985402466
	},
	"jassijs/remote/FileNode.ts": {
		"date": 1623779781658,
		"jassijs.remote.FileNode": {}
	},
	"jassijs/remote/hallo.ts": {
		"date": 1622985408207
	},
	"jassijs/remote/Jassi.ts": {
		"date": 1624295844684,
		"jassijs.remote.Jassi": {}
	},
	"jassijs/remote/ObjectTransaction.ts": {
		"date": 1622985412199
	},
	"jassijs/remote/Registry.ts": {
		"date": 1624295873451
	},
	"jassijs/remote/RemoteObject.ts": {
		"date": 1624295890257,
		"jassijs.remote.RemoteObject": {}
	},
	"jassijs/remote/RemoteProtocol.ts": {
		"date": 1624295908903,
		"jassijs.remote.RemoteProtocol": {}
	},
	"jassijs/remote/security/Group.ts": {
		"date": 1622999222021,
		"jassijs.security.Group": {
			"$DBObject": [
				{
					"name": "jassijs_group"
				}
			]
		}
	},
	"jassijs/remote/security/ParentRight.ts": {
		"date": 1622999217852,
		"jassijs.security.ParentRight": {
			"$DBObject": [
				{
					"name": "jassijs_parentright"
				}
			]
		}
	},
	"jassijs/remote/security/Right.ts": {
		"date": 1622998616949,
		"jassijs.security.Right": {
			"$DBObject": [
				{
					"name": "jassijs_right"
				}
			]
		}
	},
	"jassijs/remote/security/Rights.ts": {
		"date": 1622985522637,
		"jassijs.security.Rights": {}
	},
	"jassijs/remote/security/Setting.ts": {
		"date": 1624296035777,
		"jassijs.security.Setting": {
			"$DBObject": [
				{
					"name": "jassijs_setting"
				}
			]
		}
	},
	"jassijs/remote/security/User.ts": {
		"date": 1623528369317,
		"jassijs.security.User": {
			"$DBObject": [
				{
					"name": "jassijs_user"
				}
			]
		}
	},
	"jassijs/remote/Server.ts": {
		"date": 1624997181352,
		"jassijs.remote.Server": {}
	},
	"jassijs/remote/Settings.ts": {
		"date": 1624297039992,
		"jassijs.remote.Settings": {}
	},
	"jassijs/remote/Test.ts": {
		"date": 1624296336207,
		"jassijs.remote.Test": {}
	},
	"jassijs/remote/Transaction.ts": {
		"date": 1622985430225,
		"jassijs.remote.Transaction": {}
	},
	"jassijs/server/Compile.ts": {
		"date": 1624998421169
	},
	"jassijs/server/DBManager.ts": {
		"date": 1625000487229,
		"jassi_localserver.DBManager": {}
	},
	"jassijs/server/DoRemoteProtocol.ts": {
		"date": 1624297017569
	},
	"jassijs/server/Filesystem.ts": {
		"date": 1625332810889
	},
	"jassijs/server/Indexer.ts": {
		"date": 1624998850503
	},
	"jassijs/server/JassiServer.ts": {
		"date": 1622984045173
	},
	"jassijs/server/PassportLoginRegister.ts": {
		"date": 1622984045173
	},
	"jassijs/server/PassportSetup.ts": {
		"date": 1623702075461
	},
	"jassijs/server/RawBody.ts": {
		"date": 1589573020012
	},
	"jassijs/server/RegistryIndexer.ts": {
		"date": 1624137152110
	},
	"jassijs/server/Zip.ts": {
		"date": 1622984045173
	},
	"jassijs/UserModel.ts": {
		"date": 1622984045177
	},
	"jassijs/util/DatabaseSchema.ts": {
		"date": 1611490790268
	}
}